#DEFINE CUMMULATIVE_REPORT_FILENAME "SEM_NOT"

#DEFINE WEEKLY_CUMMULATIVE_REPORT_DEP_FILENAME "CUMPLIMIENTO_DEP"
#DEFINE WEEKLY_CUMMULATIVE_REPORT_MUN_FILENAME "CUMPLIMIENTO_MUN"
#DEFINE WEEKLY_CUMMULATIVE_REPORT_UPGD_FILENAME "CUMPLIMIENTO_UPGD"

#DEFINE SILENT_REPORT_UPGD_FILENAME "PositivesNegativesSilence"
#DEFINE HIGH_RISK_PERCENTAGE 10

#DEFINE FULFILLMENT_REPORT_UPGD_FILENAME "Fulfillment"

#DEFINE sWindowTitle "Resultados de reportes - SIVIGILA"

#DEFINE nMaxRowsForXLS 65000
#DEFINE sExportingMsg "Exportando a excel..."

#DEFINE MAX_RECORDS_TO_XLS 1500000 && Ambiente producción
*#DEFINE MAX_RECORDS_TO_XLS 500 && Ambiente de pruebas
*Máximo número de registros en la tabla de datos básicos con los que se puede producir salidas XLS sin necesidad de particionarlo

*#DEFINE MAX_BATCH_SIZE 350000  &&500000
*#DEFINE MAX_BATCH_SIZE 100

#DEFINE MULTIPLICATION_FACTOR 5