FUNCTION FieldRuleFor_eventos_01_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_CARNE_VACU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_VACU,'1','2')) AND ( .NOT. EMPTY(CARNE_VACU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_VAC_FA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_FA1,'1','2','3')) OR ( EMPTY(VAC_FA1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_MALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALGIAS,'1','2')) AND ( .NOT. EMPTY(MALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_ARTRALGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIA,'1','2')) AND ( .NOT. EMPTY(ARTRALGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_ICTERICIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICTERICIA,'1','2')) AND ( .NOT. EMPTY(ICTERICIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_HEMOPTISIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMOPTISIS,'1','2')) AND ( .NOT. EMPTY(HEMOPTISIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_SFAGET
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SFAGET,'1','2')) AND ( .NOT. EMPTY(SFAGET)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_HIPIREMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPIREMIA,'1','2')) AND ( .NOT. EMPTY(HIPIREMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_HEMATEMESI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATEMESI,'1','2')) AND ( .NOT. EMPTY(HEMATEMESI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_OLIGURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OLIGURIA,'1','2')) AND ( .NOT. EMPTY(OLIGURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_PETEQUIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PETEQUIAS,'1','2')) AND ( .NOT. EMPTY(PETEQUIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_METRORRAGI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(METRORRAGI,'1','2')) AND ( .NOT. EMPTY(METRORRAGI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_CHOQUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CHOQUE,'1','2')) AND ( .NOT. EMPTY(CHOQUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_BRADICARDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BRADICARDI,'1','2')) AND ( .NOT. EMPTY(BRADICARDI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_MELENAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MELENAS,'1','2')) AND ( .NOT. EMPTY(MELENAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_EQUIMOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EQUIMOSIS,'1','2')) AND ( .NOT. EMPTY(EQUIMOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_EPISTAXIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPISTAXIS,'1','2')) AND ( .NOT. EMPTY(EPISTAXIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_HEMATURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATURIA,'1','2')) AND ( .NOT. EMPTY(HEMATURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_FALLA_RENA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_RENA,'1','2')) AND ( .NOT. EMPTY(FALLA_RENA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_FALLA_HEPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_HEPA,'1','2')) AND ( .NOT. EMPTY(FALLA_HEPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2')) AND ( .NOT. EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_CAS_FA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_FA,'1','2')) AND ( .NOT. EMPTY(CAS_FA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_CODMUNINFE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CODMUNINFE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_01_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


