FUNCTION FieldRuleFor_eventos_83_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PRI_NOM_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PRI_NOM_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PRI_APE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PRI_APE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS','PE')) AND ( .NOT. EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_NUM_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_NIV_EDUCAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV_EDUCAT,'1','2','3','4','5')) OR ( EMPTY(NIV_EDUCAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_MENORES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((MENORES>=0  AND MENORES <= 20 AND ISNUMERIC(MENORES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PESO_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_NAC>=900  AND PESO_NAC <=5000 AND ISNUMERIC(PESO_NAC)) OR (PESO_NAC=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_TALLA_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_NAC>= 30.0  AND TALLA_NAC <= 55.0 AND ISNUMERIC(TALLA_NAC)) OR (TALLA_NAC=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_EDAD_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_GES>=20  AND EDAD_GES <= 45 AND ISNUMERIC(EDAD_GES)) OR (EDAD_GES=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_T_LECHEM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((T_LECHEM>=0 AND ISNUMERIC(T_LECHEM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_E_COMPLEM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((E_COMPLEM>=0 AND ISNUMERIC(E_COMPLEM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_CREC_DLLO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CREC_DLLO,'1','2')) AND ( .NOT. EMPTY(CREC_DLLO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_ESQ_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESQ_VAC,'1','2','3')) AND ( .NOT. EMPTY(ESQ_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_CARNE_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_VAC,'1','2')) OR ( EMPTY(CARNE_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=1.0  AND PESO_ACT <= 50.0 AND ISNUMERIC(PESO_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_TALLA_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_ACT>=45.0  AND TALLA_ACT <= 150.0 AND ISNUMERIC(TALLA_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PER_BRAQUI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PER_BRAQUI>=6.0  AND PER_BRAQUI <= 30.0 AND ISNUMERIC(PER_BRAQUI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_ZSCORE_TE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((ZSCORE_TE>=-8  AND ZSCORE_TE <=6 AND ISNUMERIC(ZSCORE_TE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_CLAS_TALLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_TALLA,'1','2','3')) OR ( EMPTY(CLAS_TALLA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) AND ( .NOT. EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_DELGADEZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DELGADEZ,'1','2')) AND ( .NOT. EMPTY(DELGADEZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PIEL_RESE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PIEL_RESE,'1','2')) AND ( .NOT. EMPTY(PIEL_RESE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_HIPERPIGM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPERPIGM,'1','2')) AND ( .NOT. EMPTY(HIPERPIGM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_LES_CABEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LES_CABEL,'1','2')) AND ( .NOT. EMPTY(LES_CABEL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_PALIDEZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PALIDEZ,'1','2')) AND ( .NOT. EMPTY(PALIDEZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_RUTA_ATENC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RUTA_ATENC,'1','2')) AND ( .NOT. EMPTY(RUTA_ATENC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_TIPO_MANEJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_MANEJ,'1','2')) OR ( EMPTY(TIPO_MANEJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_83_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


