FUNCTION FieldRuleFor_eventos_91_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_COD_MUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_MUN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_AGUA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGUA,'1','2')) AND ( .NOT. EMPTY(AGUA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ALIMENTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALIMENTOS,'1','2')) AND ( .NOT. EMPTY(ALIMENTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_PERS_PERS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PERS_PERS,'1','2')) AND ( .NOT. EMPTY(PERS_PERS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CONT_AMBIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONT_AMBIE,'1','2')) AND ( .NOT. EMPTY(CONT_AMBIE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_OTRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO,'1','2')) AND ( .NOT. EMPTY(OTRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_DESCONOCID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESCONOCID,'1','2')) AND ( .NOT. EMPTY(DESCONOCID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ESTADO_BRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADO_BRO,'1','2','3')) AND ( .NOT. EMPTY(ESTADO_BRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ORAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ORAL,'1','2')) AND ( .NOT. EMPTY(ORAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ORAL_FECAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ORAL_FECAL,'1','2')) AND ( .NOT. EMPTY(ORAL_FECAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CRUZADA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRUZADA,'1','2')) AND ( .NOT. EMPTY(CRUZADA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_ENFERMO)>=0 AND ISNUMERIC(G1_ENFERMO)) OR ( EMPTY(G1_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_EXPUEST)>=0 AND ISNUMERIC(G1_EXPUEST)) OR ( EMPTY(G1_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_HOMBRES)>=0 AND ISNUMERIC(G1_HOMBRES)) OR ( EMPTY(G1_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_MUJERES)>=0 AND ISNUMERIC(G1_MUJERES)) OR ( EMPTY(G1_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_VIVOS)>=0 AND ISNUMERIC(G1_VIVOS)) OR ( EMPTY(G1_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G1_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G1_MUERTOS)>=0 AND ISNUMERIC(G1_MUERTOS)) OR ( EMPTY(G1_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_ENFERMO)>=0 AND ISNUMERIC(G2_ENFERMO)) OR ( EMPTY(G2_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_EXPUEST)>=0 AND ISNUMERIC(G2_EXPUEST)) OR ( EMPTY(G2_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_HOMBRES)>=0 AND ISNUMERIC(G2_HOMBRES)) OR ( EMPTY(G2_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_MUJERES)>=0 AND ISNUMERIC(G2_MUJERES)) OR ( EMPTY(G2_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_VIVOS)>=0 AND ISNUMERIC(G2_VIVOS)) OR ( EMPTY(G2_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G2_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G2_MUERTOS)>=0 AND ISNUMERIC(G2_MUERTOS)) OR ( EMPTY(G2_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_ENFERMO)>=0 AND ISNUMERIC(G3_ENFERMO)) OR ( EMPTY(G3_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_EXPUEST)>=0 AND ISNUMERIC(G3_EXPUEST)) OR ( EMPTY(G3_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_HOMBRES)>=0 AND ISNUMERIC(G3_HOMBRES)) OR ( EMPTY(G3_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_MUJERES)>=0 AND ISNUMERIC(G3_MUJERES)) OR ( EMPTY(G3_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_VIVOS)>=0 AND ISNUMERIC(G3_VIVOS)) OR ( EMPTY(G3_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G3_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G3_MUERTOS)>=0 AND ISNUMERIC(G3_MUERTOS)) OR ( EMPTY(G3_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_ENFERMO)>=0 AND ISNUMERIC(G4_ENFERMO)) OR ( EMPTY(G4_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_EXPUEST)>=0 AND ISNUMERIC(G4_EXPUEST)) OR ( EMPTY(G4_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_HOMBRES)>=0 AND ISNUMERIC(G4_HOMBRES)) OR ( EMPTY(G4_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_MUJERES)>=0 AND ISNUMERIC(G4_MUJERES)) OR ( EMPTY(G4_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_VIVOS)>=0 AND ISNUMERIC(G4_VIVOS)) OR ( EMPTY(G4_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G4_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G4_MUERTOS)>=0 AND ISNUMERIC(G4_MUERTOS)) OR ( EMPTY(G4_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_ENFERMO)>=0 AND ISNUMERIC(G5_ENFERMO)) OR ( EMPTY(G5_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_EXPUEST)>=0 AND ISNUMERIC(G5_EXPUEST)) OR ( EMPTY(G5_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_HOMBRES)>=0 AND ISNUMERIC(G5_HOMBRES)) OR ( EMPTY(G5_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_MUJERES)>=0 AND ISNUMERIC(G5_MUJERES)) OR ( EMPTY(G5_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_VIVOS)>=0 AND ISNUMERIC(G5_VIVOS)) OR ( EMPTY(G5_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G5_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G5_MUERTOS)>=0 AND ISNUMERIC(G5_MUERTOS)) OR ( EMPTY(G5_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_ENFERMO)>=0 AND ISNUMERIC(G6_ENFERMO)) OR ( EMPTY(G6_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_EXPUEST)>=0 AND ISNUMERIC(G6_EXPUEST)) OR ( EMPTY(G6_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_HOMBRES)>=0 AND ISNUMERIC(G6_HOMBRES)) OR ( EMPTY(G6_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_MUJERES)>=0 AND ISNUMERIC(G6_MUJERES)) OR ( EMPTY(G6_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_VIVOS)>=0 AND ISNUMERIC(G6_VIVOS)) OR ( EMPTY(G6_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G6_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G6_MUERTOS)>=0 AND ISNUMERIC(G6_MUERTOS)) OR ( EMPTY(G6_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_ENFERMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_ENFERMO)>=0 AND ISNUMERIC(G7_ENFERMO)) OR ( EMPTY(G7_ENFERMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_EXPUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_EXPUEST)>=0 AND ISNUMERIC(G7_EXPUEST)) OR ( EMPTY(G7_EXPUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_HOMBRES)>=0 AND ISNUMERIC(G7_HOMBRES)) OR ( EMPTY(G7_HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_MUJERES)>=0 AND ISNUMERIC(G7_MUJERES)) OR ( EMPTY(G7_MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_VIVOS)>=0 AND ISNUMERIC(G7_VIVOS)) OR ( EMPTY(G7_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_G7_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G7_MUERTOS)>=0 AND ISNUMERIC(G7_MUERTOS)) OR ( EMPTY(G7_MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM1)>=0 AND ISNUMERIC(ENF_ALIM1)) OR ( EMPTY(ENF_ALIM1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM1)>=0 AND ISNUMERIC(EXP_ALIM1)) OR ( EMPTY(EXP_ALIM1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM2)>=0 AND ISNUMERIC(ENF_ALIM2)) OR ( EMPTY(ENF_ALIM2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM2)>=0 AND ISNUMERIC(EXP_ALIM2)) OR ( EMPTY(EXP_ALIM2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM3
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM3)>=0 AND ISNUMERIC(ENF_ALIM3)) OR ( EMPTY(ENF_ALIM3)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM3
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM3)>=0 AND ISNUMERIC(EXP_ALIM3)) OR ( EMPTY(EXP_ALIM3)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM4
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM4)>=0 AND ISNUMERIC(ENF_ALIM4)) OR ( EMPTY(ENF_ALIM4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM4
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM4)>=0 AND ISNUMERIC(EXP_ALIM4)) OR ( EMPTY(EXP_ALIM4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM5
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM5)>=0 AND ISNUMERIC(ENF_ALIM5)) OR ( EMPTY(ENF_ALIM5)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM5
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM5)>=0 AND ISNUMERIC(EXP_ALIM5)) OR ( EMPTY(EXP_ALIM5)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM6
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM6)>=0 AND ISNUMERIC(ENF_ALIM6)) OR ( EMPTY(ENF_ALIM6)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM6
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM6)>=0 AND ISNUMERIC(EXP_ALIM6)) OR ( EMPTY(EXP_ALIM6)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM7
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM7)>=0 AND ISNUMERIC(ENF_ALIM7)) OR ( EMPTY(ENF_ALIM7)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM7
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM7)>=0 AND ISNUMERIC(EXP_ALIM7)) OR ( EMPTY(EXP_ALIM7)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM8
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM8)>=0 AND ISNUMERIC(ENF_ALIM8)) OR ( EMPTY(ENF_ALIM8)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM8
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM8)>=0 AND ISNUMERIC(EXP_ALIM8)) OR ( EMPTY(EXP_ALIM8)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM9
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM9)>=0 AND ISNUMERIC(ENF_ALIM9)) OR ( EMPTY(ENF_ALIM9)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM9
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM9)>=0 AND ISNUMERIC(EXP_ALIM9)) OR ( EMPTY(EXP_ALIM9)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_ENF_ALIM10
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(ENF_ALIM10)>=0 AND ISNUMERIC(ENF_ALIM10)) OR ( EMPTY(ENF_ALIM10)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_EXP_ALIM10
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EXP_ALIM10)>=0 AND ISNUMERIC(EXP_ALIM10)) OR ( EMPTY(EXP_ALIM10)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_NINGUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_NINGUN)>=0 AND ISNUMERIC(CAS_NINGUN)) OR ( EMPTY(CAS_NINGUN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_NAUSEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_NAUSEA)>=0 AND ISNUMERIC(CAS_NAUSEA)) OR ( EMPTY(CAS_NAUSEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_VOMITO)>=0 AND ISNUMERIC(CAS_VOMITO)) OR ( EMPTY(CAS_VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_DIARRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_DIARRE)>=0 AND ISNUMERIC(CAS_DIARRE)) OR ( EMPTY(CAS_DIARRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_Fiebre
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_Fiebre)>=0 AND ISNUMERIC(CAS_Fiebre)) OR ( EMPTY(CAS_Fiebre)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_DOLABD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_DOLABD)>=0 AND ISNUMERIC(CAS_DOLABD)) OR ( EMPTY(CAS_DOLABD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_CEFALE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_CEFALE)>=0 AND ISNUMERIC(CAS_CEFALE)) OR ( EMPTY(CAS_CEFALE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_DESHID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_DESHID)>=0 AND ISNUMERIC(CAS_DESHID)) OR ( EMPTY(CAS_DESHID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_CIANOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_CIANOS)>=0 AND ISNUMERIC(CAS_CIANOS)) OR ( EMPTY(CAS_CIANOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_MIALGI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_MIALGI)>=0 AND ISNUMERIC(CAS_MIALGI)) OR ( EMPTY(CAS_MIALGI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_ALTRAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_ALTRAL)>=0 AND ISNUMERIC(CAS_ALTRAL)) OR ( EMPTY(CAS_ALTRAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_Mareo
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_Mareo)>=0 AND ISNUMERIC(CAS_Mareo)) OR ( EMPTY(CAS_Mareo)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_ESTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_ESTRE)>=0 AND ISNUMERIC(CAS_ESTRE)) OR ( EMPTY(CAS_ESTRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_ESCALO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_ESCALO)>=0 AND ISNUMERIC(CAS_ESCALO)) OR ( EMPTY(CAS_ESCALO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_PAREST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_PAREST)>=0 AND ISNUMERIC(CAS_PAREST)) OR ( EMPTY(CAS_PAREST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_ICTERI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_ICTERI)>=0 AND ISNUMERIC(CAS_ICTERI)) OR ( EMPTY(CAS_ICTERI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_Acolia
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_Acolia)>=0 AND ISNUMERIC(CAS_Acolia)) OR ( EMPTY(CAS_Acolia)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_COLURI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_COLURI)>=0 AND ISNUMERIC(CAS_COLURI)) OR ( EMPTY(CAS_COLURI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_LESMAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_LESMAC)>=0 AND ISNUMERIC(CAS_LESMAC)) OR ( EMPTY(CAS_LESMAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_ANOREX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_ANOREX)>=0 AND ISNUMERIC(CAS_ANOREX)) OR ( EMPTY(CAS_ANOREX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_BRADIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_BRADIC)>=0 AND ISNUMERIC(CAS_BRADIC)) OR ( EMPTY(CAS_BRADIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_SIALOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_SIALOR)>=0 AND ISNUMERIC(CAS_SIALOR)) OR ( EMPTY(CAS_SIALOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_Miosis
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_Miosis)>=0 AND ISNUMERIC(CAS_Miosis)) OR ( EMPTY(CAS_Miosis)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_CAS_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_OTROS)>=0 AND ISNUMERIC(CAS_OTROS)) OR ( EMPTY(CAS_OTROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_LUGAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LUGAR,'1','2','3','4','5','6','8','9','10','11')) AND ( .NOT. EMPTY(LUGAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_ENF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_ENF>=2 AND ISNUMERIC(TOTAL_ENF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_EXP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_EXP>=2 AND ISNUMERIC(TOTAL_EXP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_HOM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_HOM>=0 AND ISNUMERIC(TOTAL_HOM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_MUJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_MUJ>=0 AND ISNUMERIC(TOTAL_MUJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_VIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_VIVO>=0 AND ISNUMERIC(TOTAL_VIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_TOTAL_MUER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TOTAL_MUER>=0 AND ISNUMERIC(TOTAL_MUER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_91_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


