FUNCTION FieldRuleFor_eventos_40_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_VIAJO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIAJO,'1','2','3')) AND ( .NOT. EMPTY(VIAJO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_RATAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RATAS,'1','2')) OR ( EMPTY(RATAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_PERROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PERROS,'1','2')) OR ( EMPTY(PERROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CERDOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CERDOS,'1','2')) OR ( EMPTY(CERDOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CONTAC_ACC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONTAC_ACC,'1','2','3')) AND ( .NOT. EMPTY(CONTAC_ACC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_RECIBIO_TR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RECIBIO_TR,'1','2','3')) AND ( .NOT. EMPTY(RECIBIO_TR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ESCALOFRIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCALOFRIO,'1','2')) AND ( .NOT. EMPTY(ESCALOFRIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DOLOR_RETR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR_RETR,'1','2')) AND ( .NOT. EMPTY(DOLOR_RETR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DABDOMINAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DABDOMINAL,'1','2')) AND ( .NOT. EMPTY(DABDOMINAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ICTERICIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICTERICIA,'1','2')) AND ( .NOT. EMPTY(ICTERICIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_PETEQUIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PETEQUIAS,'1','2')) OR ( EMPTY(PETEQUIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_EQUIMOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EQUIMOSIS,'1','2')) OR ( EMPTY(EQUIMOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_HEMOPTISIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMOPTISIS,'1','2')) OR ( EMPTY(HEMOPTISIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_GINGIVORRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GINGIVORRA,'1','2')) OR ( EMPTY(GINGIVORRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_METRORRAGI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(METRORRAGI,'1','2')) OR ( EMPTY(METRORRAGI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_HEMATURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATURIA,'1','2')) OR ( EMPTY(HEMATURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_MELENAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MELENAS,'1','2')) OR ( EMPTY(MELENAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIALGIAS,'1','2')) AND ( .NOT. EMPTY(MIALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ARTRALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIAS,'1','2')) AND ( .NOT. EMPTY(ARTRALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2')) AND ( .NOT. EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ESPLENOMEG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESPLENOMEG,'1','2')) AND ( .NOT. EMPTY(ESPLENOMEG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ADENOPATIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADENOPATIA,'1','2')) AND ( .NOT. EMPTY(ADENOPATIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DISNEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISNEA,'1','2')) AND ( .NOT. EMPTY(DISNEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DESHIDRATA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESHIDRATA,'1','2')) AND ( .NOT. EMPTY(DESHIDRATA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_SIG_MENING
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIG_MENING,'1','2')) AND ( .NOT. EMPTY(SIG_MENING)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_EXANTEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EXANTEMA,'1','2')) AND ( .NOT. EMPTY(EXANTEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) AND ( .NOT. EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CONVULSION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONVULSION,'1','2')) AND ( .NOT. EMPTY(CONVULSION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_HEMORRAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMORRAGIA,'1','2')) AND ( .NOT. EMPTY(HEMORRAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DOLOR_PANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR_PANT,'1','2')) AND ( .NOT. EMPTY(DOLOR_PANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_SUDOR_NOCT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUDOR_NOCT,'1','2')) AND ( .NOT. EMPTY(SUDOR_NOCT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_EPIDIDIMIT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPIDIDIMIT,'1','2')) AND ( .NOT. EMPTY(EPIDIDIMIT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ORQUITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ORQUITIS,'1','2')) AND ( .NOT. EMPTY(ORQUITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_OLIGURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OLIGURIA,'1','2')) AND ( .NOT. EMPTY(OLIGURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_ANIM_EN_CA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANIM_EN_CA,'1','2')) AND ( .NOT. EMPTY(ANIM_EN_CA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_GATOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GATOS,'1','2')) OR ( EMPTY(GATOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_BOVINOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BOVINOS,'1','2')) OR ( EMPTY(BOVINOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_EQUINOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EQUINOS,'1','2')) OR ( EMPTY(EQUINOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_SILVESTRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SILVESTRES,'1','2')) OR ( EMPTY(SILVESTRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_OTR_ANIMAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_ANIMAL,'1','2')) OR ( EMPTY(OTR_ANIMAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_PICAD_GARR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PICAD_GARR,'1','2')) AND ( .NOT. EMPTY(PICAD_GARR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_PICAD_PIOJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PICAD_PIOJ,'1','2')) AND ( .NOT. EMPTY(PICAD_PIOJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_PICAD_PULG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PICAD_PULG,'1','2')) AND ( .NOT. EMPTY(PICAD_PULG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CONS_LECHE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONS_LECHE,'1','2')) AND ( .NOT. EMPTY(CONS_LECHE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_MULT_PAREJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MULT_PAREJ,'1','2')) AND ( .NOT. EMPTY(MULT_PAREJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_USA_HEMODI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USA_HEMODI,'1','2')) AND ( .NOT. EMPTY(USA_HEMODI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_USA_DROG_I
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USA_DROG_I,'1','2')) AND ( .NOT. EMPTY(USA_DROG_I)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CONT_HBSAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONT_HBSAG,'1','2')) AND ( .NOT. EMPTY(CONT_HBSAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_MANIP_SECR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MANIP_SECR,'1','2')) AND ( .NOT. EMPTY(MANIP_SECR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_DET_RAPIDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DET_RAPIDO,'1','2')) AND ( .NOT. EMPTY(DET_RAPIDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_CONJ_NO_SU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONJ_NO_SU,'1','2')) AND ( .NOT. EMPTY(CONJ_NO_SU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_40_MANIF_PURP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MANIF_PURP,'1','2')) OR ( EMPTY(MANIF_PURP)))
	ENDIF
ENDFUNC


