FUNCTION FieldRuleFor_eventos_90_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MES)>=1  AND  VAL(MES) <=12 AND ISNUMERIC(MES)) AND ( .NOT. EMPTY(MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(AÑO)>=2011 AND ISNUMERIC(AÑO)) AND ( .NOT. EMPTY(AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_N_COLECIST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_COLECIST>=0  AND N_COLECIST <=99 AND ISNUMERIC(N_COLECIST)) OR (N_COLECIST=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_D_COLECIST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_COLECIST)>=0  AND  VAL(D_COLECIST) <=9999 AND ISNUMERIC(D_COLECIST)) OR ( EMPTY(D_COLECIST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_N_HERNIORR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_HERNIORR>=0  AND N_HERNIORR <=99 AND ISNUMERIC(N_HERNIORR)) OR (N_HERNIORR=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_D_HERNIORR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_HERNIORR)>=0  AND  VAL(D_HERNIORR) <=9999 AND ISNUMERIC(D_HERNIORR)) OR ( EMPTY(D_HERNIORR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_N_REVASCUL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_REVASCUL>=0  AND N_REVASCUL <=99 AND ISNUMERIC(N_REVASCUL)) OR (N_REVASCUL=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_D_REVASCUL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_REVASCUL)>=0  AND  VAL(D_REVASCUL) <=9999 AND ISNUMERIC(D_REVASCUL)) OR ( EMPTY(D_REVASCUL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_N_CESAREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_CESAREA>=0  AND N_CESAREA <=99 AND ISNUMERIC(N_CESAREA)) OR (N_CESAREA=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_D_CESAREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_CESAREA)>=0  AND  VAL(D_CESAREA) <=9999 AND ISNUMERIC(D_CESAREA)) OR ( EMPTY(D_CESAREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_N_POSTPART
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_POSTPART>=0  AND N_POSTPART <=99 AND ISNUMERIC(N_POSTPART)) OR (N_POSTPART=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_D_POSTPART
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_POSTPART)>=0  AND  VAL(D_POSTPART) <=9999 AND ISNUMERIC(D_POSTPART)) OR ( EMPTY(D_POSTPART)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_90_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


