FUNCTION FieldRuleFor_eventos_88_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MES)>=1  AND  VAL(MES) <=12 AND ISNUMERIC(MES)) AND ( .NOT. EMPTY(MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(AÑO)>=2011 AND ISNUMERIC(AÑO)) AND ( .NOT. EMPTY(AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_SER_UCI_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCI_A)>=1  AND  VAL(SER_UCI_A) <= 99 AND ISNUMERIC(SER_UCI_A)) OR ( EMPTY(SER_UCI_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_CAM_UCI_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCI_A)>=1  AND  VAL(CAM_UCI_A) <= 999 AND ISNUMERIC(CAM_UCI_A)) OR ( EMPTY(CAM_UCI_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_DIA_PAC_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DIA_PAC_A)>= 1  AND  VAL(DIA_PAC_A) <= 9999 AND ISNUMERIC(DIA_PAC_A)) OR ( EMPTY(DIA_PAC_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_ITSAC_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_ITSAC_A>=0  AND N_ITSAC_A <=99 AND ISNUMERIC(N_ITSAC_A)) OR (N_ITSAC_A=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_ITSAC_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_ITSAC_A)>=0  AND  VAL(D_ITSAC_A) <=9999 AND ISNUMERIC(D_ITSAC_A)) OR ( EMPTY(D_ITSAC_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_ISTUA_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_ISTUA_A>=0  AND N_ISTUA_A <=99 AND ISNUMERIC(N_ISTUA_A)) OR (N_ISTUA_A=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_ISTUA_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_ISTUA_A)>=0  AND  VAL(D_ISTUA_A) <=9999 AND ISNUMERIC(D_ISTUA_A)) OR ( EMPTY(D_ISTUA_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_NAV_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_NAV_A>=0  AND N_NAV_A <=99 AND ISNUMERIC(N_NAV_A)) OR (N_NAV_A=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_NAV_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_NAV_A)>=0  AND  VAL(D_NAV_A) <=9999 AND ISNUMERIC(D_NAV_A)) OR ( EMPTY(D_NAV_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_SER_UCI_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCI_P)>=1  AND  VAL(SER_UCI_P) <= 99 AND ISNUMERIC(SER_UCI_P)) OR ( EMPTY(SER_UCI_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_CAM_UCI_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCI_P)>=1  AND  VAL(CAM_UCI_P) <= 999 AND ISNUMERIC(CAM_UCI_P)) OR ( EMPTY(CAM_UCI_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_DIA_PAC_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DIA_PAC_P)>= 1  AND  VAL(DIA_PAC_P) <= 9999 AND ISNUMERIC(DIA_PAC_P)) OR ( EMPTY(DIA_PAC_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_ITSAC_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_ITSAC_P>=0  AND N_ITSAC_P <=99 AND ISNUMERIC(N_ITSAC_P)) OR (N_ITSAC_P=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_ITSAC_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_ITSAC_P)>=0  AND  VAL(D_ITSAC_P) <=9999 AND ISNUMERIC(D_ITSAC_P)) OR ( EMPTY(D_ITSAC_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_ISTUA_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_ISTUA_P>=0  AND N_ISTUA_P <=99 AND ISNUMERIC(N_ISTUA_P)) OR (N_ISTUA_P=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_ISTUA_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_ISTUA_P)>=0  AND  VAL(D_ISTUA_P) <=9999 AND ISNUMERIC(D_ISTUA_P)) OR ( EMPTY(D_ISTUA_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_NAV_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_NAV_P>=0  AND N_NAV_P <=99 AND ISNUMERIC(N_NAV_P)) OR (N_NAV_P=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_D_NAV_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(D_NAV_P)>=0  AND  VAL(D_NAV_P) <=9999 AND ISNUMERIC(D_NAV_P)) OR ( EMPTY(D_NAV_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_SER_UCI_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCI_N)>=1  AND  VAL(SER_UCI_N) <=99 AND ISNUMERIC(SER_UCI_N)) OR ( EMPTY(SER_UCI_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_CAM_UCI_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCI_N)>=1  AND  VAL(CAM_UCI_N) <=999 AND ISNUMERIC(CAM_UCI_N)) OR ( EMPTY(CAM_UCI_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_DIA_PAC_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DIA_PAC_N)>=1  AND  VAL(DIA_PAC_N) <=9999 AND ISNUMERIC(DIA_PAC_N)) OR ( EMPTY(DIA_PAC_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N1_S_N>=0  AND N_C_N1_S_N <=99 AND ISNUMERIC(N_C_N1_S_N)) OR (N_C_N1_S_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C1_S_N)>=0  AND  VAL(N_D_C1_S_N) <=9999 AND ISNUMERIC(N_D_C1_S_N)) OR ( EMPTY(N_D_C1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P1_S_N)>=0  AND  VAL(N_D_P1_S_N) <=9999 AND ISNUMERIC(N_D_P1_S_N)) OR ( EMPTY(N_D_P1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N2_S_N>=0  AND N_C_N2_S_N <=99 AND ISNUMERIC(N_C_N2_S_N)) OR (N_C_N2_S_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C2_S_N)>=0  AND  VAL(N_D_C2_S_N) <=9999 AND ISNUMERIC(N_D_C2_S_N)) OR ( EMPTY(N_D_C2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P2_S_N)>=0  AND  VAL(N_D_P2_S_N) <=9999 AND ISNUMERIC(N_D_P2_S_N)) OR ( EMPTY(N_D_P2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N3_S_N>=0  AND N_C_N3_S_N <=99 AND ISNUMERIC(N_C_N3_S_N)) OR (N_C_N3_S_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C3_S_N)>=0  AND  VAL(N_D_C3_S_N) <=9999 AND ISNUMERIC(N_D_C3_S_N)) OR ( EMPTY(N_D_C3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P3_S_N)>=0  AND  VAL(N_D_P3_S_N) <=9999 AND ISNUMERIC(N_D_P3_S_N)) OR ( EMPTY(N_D_P3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N4_S_N>=0  AND N_C_N4_S_N <=99 AND ISNUMERIC(N_C_N4_S_N)) OR (N_C_N4_S_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C4_S_N)>=0  AND  VAL(N_D_C4_S_N) <=9999 AND ISNUMERIC(N_D_C4_S_N)) OR ( EMPTY(N_D_C4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P4_S_N)>=0  AND  VAL(N_D_P4_S_N) <=9999 AND ISNUMERIC(N_D_P4_S_N)) OR ( EMPTY(N_D_P4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N5_S_N>=0  AND N_C_N5_S_N <=99 AND ISNUMERIC(N_C_N5_S_N)) OR (N_C_N5_S_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C5_S_N)>=0  AND  VAL(N_D_C5_S_N) <=9999 AND ISNUMERIC(N_D_C5_S_N)) OR ( EMPTY(N_D_C5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P5_S_N)>=0  AND  VAL(N_D_P5_S_N) <=9999 AND ISNUMERIC(N_D_P5_S_N)) OR ( EMPTY(N_D_P5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N1_V_N>=0  AND N_C_N1_V_N <=99 AND ISNUMERIC(N_C_N1_V_N)) OR (N_C_N1_V_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C1_V_N)>=0  AND  VAL(N_D_C1_V_N) <=9999 AND ISNUMERIC(N_D_C1_V_N)) OR ( EMPTY(N_D_C1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P1_V_N)>=0  AND  VAL(N_D_P1_V_N) <=9999 AND ISNUMERIC(N_D_P1_V_N)) OR ( EMPTY(N_D_P1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N2_V_N>=0  AND N_C_N2_V_N <=99 AND ISNUMERIC(N_C_N2_V_N)) OR (N_C_N2_V_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C2_V_N)>=0  AND  VAL(N_D_C2_V_N) <=9999 AND ISNUMERIC(N_D_C2_V_N)) OR ( EMPTY(N_D_C2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P2_V_N)>=0  AND  VAL(N_D_P2_V_N) <=9999 AND ISNUMERIC(N_D_P2_V_N)) OR ( EMPTY(N_D_P2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N3_V_N>=0  AND N_C_N3_V_N <=99 AND ISNUMERIC(N_C_N3_V_N)) OR (N_C_N3_V_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C3_V_N)>=0  AND  VAL(N_D_C3_V_N) <=9999 AND ISNUMERIC(N_D_C3_V_N)) OR ( EMPTY(N_D_C3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P3_V_N)>=0  AND  VAL(N_D_P3_V_N) <=9999 AND ISNUMERIC(N_D_P3_V_N)) OR ( EMPTY(N_D_P3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N4_V_N>=0  AND N_C_N4_V_N <=99 AND ISNUMERIC(N_C_N4_V_N)) OR (N_C_N4_V_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C4_V_N)>=0  AND  VAL(N_D_C4_V_N) <=9999 AND ISNUMERIC(N_D_C4_V_N)) OR ( EMPTY(N_D_C4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P4_V_N)>=0  AND  VAL(N_D_P4_V_N) <=9999 AND ISNUMERIC(N_D_P4_V_N)) OR ( EMPTY(N_D_P4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_C_N5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_C_N5_V_N>=0  AND N_C_N5_V_N <=99 AND ISNUMERIC(N_C_N5_V_N)) OR (N_C_N5_V_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_C5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C5_V_N)>=0  AND  VAL(N_D_C5_V_N) <=9999 AND ISNUMERIC(N_D_C5_V_N)) OR ( EMPTY(N_D_C5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_N_D_P5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P5_V_N)>=0  AND  VAL(N_D_P5_V_N) <=9999 AND ISNUMERIC(N_D_P5_V_N)) OR ( EMPTY(N_D_P5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_88_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


