FUNCTION FieldRuleFor_eventos_77_PROB_FAMIL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_FAMIL,'1','2')) AND ( .NOT. EMPTY(PROB_FAMIL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ESTADO_CIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADO_CIV,'1','2','3','4','5')) AND ( .NOT. EMPTY(ESTADO_CIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_MUERTE_FAM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUERTE_FAM,'1','2')) AND ( .NOT. EMPTY(MUERTE_FAM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PROB_LEGAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_LEGAL,'1','2')) AND ( .NOT. EMPTY(PROB_LEGAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PSICOLOGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSICOLOGIA,'1','2')) OR ( EMPTY(PSICOLOGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PSIQUIATRI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSIQUIATRI,'1','2')) OR ( EMPTY(PSIQUIATRI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_INTEN_PREV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INTEN_PREV,'1','2')) AND ( .NOT. EMPTY(INTEN_PREV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_INTENTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INTENTOS,'1','2','3','4','99')) OR ( EMPTY(INTENTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PROB_ECONO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_ECONO,'1','2')) AND ( .NOT. EMPTY(PROB_ECONO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PROB_PAREJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_PAREJ,'1','2')) AND ( .NOT. EMPTY(PROB_PAREJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PROB_CONSU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_CONSU,'1','2')) AND ( .NOT. EMPTY(PROB_CONSU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ANTEC_TRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANTEC_TRAN,'1','2')) AND ( .NOT. EMPTY(ANTEC_TRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_HIST_FAMIL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIST_FAMIL,'1','2')) AND ( .NOT. EMPTY(HIST_FAMIL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_IDEA_SUICI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDEA_SUICI,'1','2')) AND ( .NOT. EMPTY(IDEA_SUICI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ENFER_GRAV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENFER_GRAV,'1','2')) AND ( .NOT. EMPTY(ENFER_GRAV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_TRAN_DEPRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAN_DEPRE,'1','2')) OR ( EMPTY(TRAN_DEPRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ESQUIZOFRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESQUIZOFRE,'1','2')) OR ( EMPTY(ESQUIZOFRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ABUSO_ALCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ABUSO_ALCO,'1','2')) AND ( .NOT. EMPTY(ABUSO_ALCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_TRANS_PERS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRANS_PERS,'1','2')) OR ( EMPTY(TRANS_PERS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_AHORCAMIEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AHORCAMIEN,'1','2')) AND ( .NOT. EMPTY(AHORCAMIEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ARMA_CORTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARMA_CORTO,'1','2')) AND ( .NOT. EMPTY(ARMA_CORTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_INTOXICACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INTOXICACI,'1','2')) AND ( .NOT. EMPTY(INTOXICACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_TIPO_SUSTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_SUSTA,'1','2','3','4','5','6','7','8')) OR ( EMPTY(TIPO_SUSTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_LANZ_VACIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LANZ_VACIO,'1','2')) AND ( .NOT. EMPTY(LANZ_VACIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_LANZ_VEHIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LANZ_VEHIC,'1','2')) AND ( .NOT. EMPTY(LANZ_VEHIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ARMA_FUEGO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARMA_FUEGO,'1','2')) AND ( .NOT. EMPTY(ARMA_FUEGO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_TRAB_SOCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAB_SOCIA,'1','2')) OR ( EMPTY(TRAB_SOCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ESCOLARID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCOLARID,'1','2','3','5','7','8','9','10','11','12','13','14')) AND ( .NOT. EMPTY(ESCOLARID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_SUICI_FM_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUICI_FM_A,'1','2')) AND ( .NOT. EMPTY(SUICI_FM_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PROB_LABOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_LABOR,'1','2')) OR ( EMPTY(PROB_LABOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_LANZ_AGUA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LANZ_AGUA,'1','2')) OR ( EMPTY(LANZ_AGUA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_MALTR_FPS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALTR_FPS,'1','2')) AND ( .NOT. EMPTY(MALTR_FPS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ANTEC_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANTEC_V_A,'1','2')) AND ( .NOT. EMPTY(ANTEC_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_INMOLACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INMOLACION,'1','2')) AND ( .NOT. EMPTY(INMOLACION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ESCO_EDUC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCO_EDUC,'1','2')) AND ( .NOT. EMPTY(ESCO_EDUC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_PLAN_SUICI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PLAN_SUICI,'1','2')) AND ( .NOT. EMPTY(PLAN_SUICI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_VIA_EXPOSI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIA_EXPOSI,'1','2','3','4','5','6','7')) OR ( EMPTY(VIA_EXPOSI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_LUGAR_INTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LUGAR_INTO,'1','2','3','4','5','6','7','8')) OR ( EMPTY(LUGAR_INTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_77_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2','3')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


