FUNCTION FieldRuleFor_eventos_75_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_ATEN_PARTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ATEN_PARTO,'1','2')) AND ( .NOT. EMPTY(ATEN_PARTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_FEC_PARTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_PARTO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_PROCEDIMIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROCEDIMIE,'1','2','3','4','5')) AND ( .NOT. EMPTY(PROCEDIMIE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_CONTE_PROC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONTE_PROC,'1','2','4')) AND ( .NOT. EMPTY(CONTE_PROC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_PRF_ANTIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRF_ANTIB,'1','2')) OR ( EMPTY(PRF_ANTIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_TIEMPO_RUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TIEMPO_RUP)>=0  AND  VAL(TIEMPO_RUP) <= 2880 AND ISNUMERIC(TIEMPO_RUP)) OR ( EMPTY(TIEMPO_RUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_REQ_INTERV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REQ_INTERV,'1','2')) AND ( .NOT. EMPTY(REQ_INTERV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_TIEM_ENTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIEM_ENTRE,'1','2','3')) OR ( EMPTY(TIEM_ENTRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_ATENC_UPGD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ATENC_UPGD,'1','2')) AND ( .NOT. EMPTY(ATENC_UPGD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_75_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'3','5','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


