FUNCTION FieldRuleFor_eventos_33_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_VAC_CON_RO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_CON_RO,'1','2','3')) AND ( .NOT. EMPTY(VAC_CON_RO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_TIENE_CARN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIENE_CARN,'1','2')) AND ( .NOT. EMPTY(TIENE_CARN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_PESO_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_NAC)>= 500  AND  VAL(PESO_NAC) <=6000 AND ISNUMERIC(PESO_NAC)) AND ( .NOT. EMPTY(PESO_NAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_REC_LECHE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REC_LECHE,'1','2','3')) AND ( .NOT. EMPTY(REC_LECHE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_ALIM_ACTUA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALIM_ACTUA,'1','2','3','4')) AND ( .NOT. EMPTY(ALIM_ACTUA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2','3')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2','3')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_FEC_INI_DI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INI_DI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_NO_DEPOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NO_DEPOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_FEC_TER_DI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_TER_DI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_CARAC_HECE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARAC_HECE,'1','2','3','4')) AND ( .NOT. EMPTY(CARAC_HECE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_ESTADO_ING
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADO_ING,'1','2')) AND ( .NOT. EMPTY(ESTADO_ING)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_GRAD_DESHI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GRAD_DESHI,'1','2','3','4')) OR ( EMPTY(GRAD_DESHI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_PESO_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_INGR)>=1000  AND  VAL(PESO_INGR) <=50000 AND ISNUMERIC(PESO_INGR)) AND ( .NOT. EMPTY(PESO_INGR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_TALLA_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TALLA_INGR)>=45  AND  VAL(TALLA_INGR) <=150 AND ISNUMERIC(TALLA_INGR)) AND ( .NOT. EMPTY(TALLA_INGR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_REC_ANTIBI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REC_ANTIBI,'1','2','3')) AND ( .NOT. EMPTY(REC_ANTIBI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_TRAT_HIDRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAT_HIDRA,'1','2')) AND ( .NOT. EMPTY(TRAT_HIDRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_COMP_HOSP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMP_HOSP,'1','2','3')) AND ( .NOT. EMPTY(COMP_HOSP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_REC_ANT_HO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REC_ANT_HO,'1','2','3')) AND ( .NOT. EMPTY(REC_ANT_HO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_DIAS_HOSP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIAS_HOSP))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_DIAS_H_URG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIAS_H_URG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_DIAS_H_PED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIAS_H_PED))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_DIAS_H_UCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIAS_H_UCI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_FEC_EGRESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_EGRESO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_MOTIVO_EGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOTIVO_EGR,'1','2','3')) AND ( .NOT. EMPTY(MOTIVO_EGR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_SAL_CON_DI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SAL_CON_DI,'1','2','3')) AND ( .NOT. EMPTY(SAL_CON_DI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_DIAG_EGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIAG_EGR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_IDENT_ROTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDENT_ROTA,'1','2')) OR ( EMPTY(IDENT_ROTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_IDENT_BACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDENT_BACT,'1','2')) OR ( EMPTY(IDENT_BACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_IDENT_PARA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDENT_PARA,'1','2')) OR ( EMPTY(IDENT_PARA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_GUARDERIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GUARDERIA,'1','2')) AND ( .NOT. EMPTY(GUARDERIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_MAS_PERSON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MAS_PERSON,'1','2','3')) AND ( .NOT. EMPTY(MAS_PERSON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_33_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


