FUNCTION FieldRuleFor_eventos_37_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TIPO_LEUCE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_LEUCE,'1','2','3','4')) AND ( .NOT. EMPTY(TIPO_LEUCE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_INFECCION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INFECCION,'1','2')) AND ( .NOT. EMPTY(INFECCION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_SLISIS_TUM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SLISIS_TUM,'1','2')) AND ( .NOT. EMPTY(SLISIS_TUM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TROMBOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TROMBOSIS,'1','2')) AND ( .NOT. EMPTY(TROMBOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_HEMORRAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMORRAGIA,'1','2')) AND ( .NOT. EMPTY(HEMORRAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_CCONVULSIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CCONVULSIV,'1','2')) AND ( .NOT. EMPTY(CCONVULSIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_DESCONOCID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESCONOCID,'1','2')) OR ( EMPTY(DESCONOCID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_OTRAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRAS,'1','2')) AND ( .NOT. EMPTY(OTRAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_SIT_DEF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_DEF,'1','2','3','4')) OR ( EMPTY(SIT_DEF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_CAUS_MUE_D
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAUS_MUE_D,'1','2','3')) OR ( EMPTY(CAUS_MUE_D)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_FEC_INI_TR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INI_TR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOR_DIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOR_DIAS)>= 0  AND  VAL(TPOR_DIAS) <= 30 AND ISNUMERIC(TPOR_DIAS)) OR ( EMPTY(TPOR_DIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOR_MESES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOR_MESES)>= 0  AND  VAL(TPOR_MESES) <= 12 AND ISNUMERIC(TPOR_MESES)) OR ( EMPTY(TPOR_MESES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOD_DIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOD_DIAS)>= 0  AND  VAL(TPOD_DIAS) <= 30 AND ISNUMERIC(TPOD_DIAS)) OR ( EMPTY(TPOD_DIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOD_MESES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOD_MESES)>= 0  AND  VAL(TPOD_MESES) <= 12 AND ISNUMERIC(TPOD_MESES)) OR ( EMPTY(TPOD_MESES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOI_DIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOI_DIAS)>= 0  AND  VAL(TPOI_DIAS) <= 30 AND ISNUMERIC(TPOI_DIAS)) OR ( EMPTY(TPOI_DIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_TPOI_MESES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TPOI_MESES)>= 0  AND  VAL(TPOI_MESES) <= 12 AND ISNUMERIC(TPOI_MESES)) OR ( EMPTY(TPOI_MESES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_37_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


