FUNCTION FieldRuleFor_Seguimient_ID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ID) OR NOTIF_IAAS!='1')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_ID_PERSONA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ID_PERSONA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_SINTOMATIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINTOMATIC,'1','2')) AND ( .NOT. EMPTY(SINTOMATIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_HOSPITALIZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HOSPITALIZ,'1','2')) OR ( EMPTY(HOSPITALIZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_FEC_SEGUMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_SEGUMI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_HORA_SEGUI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(HORA_SEGUI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_TOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOS,'1','2')) OR ( EMPTY(TOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) OR ( EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_DIF_RES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIF_RES,'1','2')) OR ( EMPTY(DIF_RES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_ODINOFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ODINOFAGIA,'1','2')) OR ( EMPTY(ODINOFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_ADINAMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADINAMIA,'1','2')) OR ( EMPTY(ADINAMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','6','7','D')) AND ( .NOT. EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_FEC_AJU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_AJU))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_EST_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_INGR,0,2,3)) OR (EST_INGR=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Seguimient_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'3','5','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


