FUNCTION FieldRuleFor_eventos_65_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_VIG_ACTIVA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIG_ACTIVA,'1','2')) AND ( .NOT. EMPTY(VIG_ACTIVA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_SINTOMATIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINTOMATIC,'1','2')) AND ( .NOT. EMPTY(SINTOMATIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_CLAS_CASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_CASO,'1','2')) AND ( .NOT. EMPTY(CLAS_CASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_RECRUDECE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RECRUDECE,'1','2')) AND ( .NOT. EMPTY(RECRUDECE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_TRIMESTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRIMESTRE,'1','2','3')) OR ( EMPTY(TRIMESTRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_TRATAMIENT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRATAMIENT,'1','2','3','5','6','7','8','9','10','11','12','13','14','15','16')) AND ( .NOT. EMPTY(TRATAMIENT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_TIPOEXAMEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(TIPOEXAMEN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_RECUENTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((RECUENTO>=16 AND ISNUMERIC(RECUENTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_GAMETOCITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GAMETOCITO,'1','2')) AND ( .NOT. EMPTY(GAMETOCITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COMPLICACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMPLICACI,'1','2')) AND ( .NOT. EMPTY(COMPLICACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_CEREBR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_CEREBR,'1','2')) OR ( EMPTY(COM_CEREBR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_RENAL,'1','2')) OR ( EMPTY(COM_RENAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_HEPATI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_HEPATI,'1','2')) OR ( EMPTY(COM_HEPATI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_PULMON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_PULMON,'1','2')) OR ( EMPTY(COM_PULMON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_HEMATO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_HEMATO,'1','2')) OR ( EMPTY(COM_HEMATO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_COM_OTRAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_OTRAS,'1','2')) OR ( EMPTY(COM_OTRAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_ESP_PLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESP_PLA,'1','2','3','4')) AND ( .NOT. EMPTY(ESP_PLA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_RESP_DIAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(RESP_DIAG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_FEC_RESULT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_RESULT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_65_DESPLAZAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESPLAZAMI,'1','2')) AND ( .NOT. EMPTY(DESPLAZAMI)))
	ENDIF
ENDFUNC


