FUNCTION FieldRuleFor_eventos_06_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_CAS_DETX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_DETX,'1','2','3','4','5','6','7','8')) AND ( .NOT. EMPTY(CAS_DETX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_VAC_SAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_SAR,'1','2','3')) AND ( .NOT. EMPTY(VAC_SAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FTE_SAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTE_SAR,'1','2','3')) OR ( EMPTY(FTE_SAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_TIP_VAC_SA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_VAC_SA,'1','2','3')) OR ( EMPTY(TIP_VAC_SA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_VAC_RUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_RUB,'1','2','3')) AND ( .NOT. EMPTY(VAC_RUB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FTE_RUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTE_RUB,'1','2','3')) OR ( EMPTY(FTE_RUB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_TIP_VAC_RU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_VAC_RU,'1','2','3')) OR ( EMPTY(TIP_VAC_RU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_DX_INI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DX_INI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_TIP_ERU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_ERU,'1','2','3','4')) AND ( .NOT. EMPTY(TIP_ERU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FINI_ERU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FINI_ERU))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_DUR_DIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DUR_DIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_TOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOS,'1','2','3')) AND ( .NOT. EMPTY(TOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_CORIZA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CORIZA,'1','2','3')) AND ( .NOT. EMPTY(CORIZA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_CONJUNTIVI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONJUNTIVI,'1','2','3')) AND ( .NOT. EMPTY(CONJUNTIVI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_ADENOPATIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADENOPATIA,'1','2','3')) AND ( .NOT. EMPTY(ADENOPATIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_ARTRALGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIA,'1','2','3')) AND ( .NOT. EMPTY(ARTRALGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_SAR_RUB_7
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SAR_RUB_7,'1','2','3','4','5')) AND ( .NOT. EMPTY(SAR_RUB_7)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_SAR_RUB_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SAR_RUB_A,'1','2','3','4','5')) AND ( .NOT. EMPTY(SAR_RUB_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_VIAJO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIAJO,'1','2','3')) AND ( .NOT. EMPTY(VIAJO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_CON_MUJ_E
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_MUJ_E,'1','2','3')) AND ( .NOT. EMPTY(CON_MUJ_E)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_VAC_BLOQ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_BLOQ,'1','2','3')) OR ( EMPTY(VAC_BLOQ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_MON_RAP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MON_RAP,'1','2','3')) OR ( EMPTY(MON_RAP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_SEG_CONT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEG_CONT,'1','2','3')) OR ( EMPTY(SEG_CONT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FTE_INFECC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTE_INFECC,'1','2','3','4')) OR ( EMPTY(FTE_INFECC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_CRI_DES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRI_DES,'1','2','3','4','5','6','7')) OR ( EMPTY(CRI_DES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FTE_CONTAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTE_CONTAG,'1','2','3','88','99')) AND ( .NOT. EMPTY(FTE_CONTAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_SOSPE_MISC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SOSPE_MISC,'1','2')) AND ( .NOT. EMPTY(SOSPE_MISC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_RT_PCR_POS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RT_PCR_POS,'1','2')) OR ( EMPTY(RT_PCR_POS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_ACIGMIGG_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACIGMIGG_P,'1','2')) OR ( EMPTY(ACIGMIGG_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_NEXO_POS_C
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NEXO_POS_C,'1','2')) OR ( EMPTY(NEXO_POS_C)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) OR ( EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) OR ( EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_ALT_CONCIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALT_CONCIE,'1','2')) OR ( EMPTY(ALT_CONCIE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FIBRIOGENO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((FIBRIOGENO>=0  AND FIBRIOGENO <=1000 AND ISNUMERIC(FIBRIOGENO)) OR (FIBRIOGENO=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_PROT_C_REA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PROT_C_REA>=0  AND PROT_C_REA <=1000 AND ISNUMERIC(PROT_C_REA)) OR (PROT_C_REA=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_FERRITINA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((FERRITINA>=0  AND FERRITINA <=5000 AND ISNUMERIC(FERRITINA)) OR (FERRITINA=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_DÍMERO_D
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((DÍMERO_D>=0  AND DÍMERO_D <=20000 AND ISNUMERIC(DÍMERO_D)) OR (DÍMERO_D=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_LINFOPENIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((LINFOPENIA>=0  AND LINFOPENIA <=4999 AND ISNUMERIC(LINFOPENIA)) OR (LINFOPENIA=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_06_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) OR ( EMPTY(DIARREA)))
	ENDIF
ENDFUNC


