FUNCTION FieldRuleFor_eventos_28_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_MOM_DX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOM_DX,'1','2')) AND ( .NOT. EMPTY(MOM_DX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_EDAD_GES_1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_GES_1)>= 0  AND  VAL(EDAD_GES_1) <= 45 AND ISNUMERIC(EDAD_GES_1)) AND ( .NOT. EMPTY(EDAD_GES_1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_EDAD_GESDX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_GESDX)>= 0  AND  VAL(EDAD_GESDX) <= 45 AND ISNUMERIC(EDAD_GESDX)) AND ( .NOT. EMPTY(EDAD_GESDX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_CD4
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CD4,'1','2')) AND ( .NOT. EMPTY(CD4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_CVIR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CVIR,'1','2')) AND ( .NOT. EMPTY(CVIR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_CVIR_2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CVIR_2,'1','2')) OR ( EMPTY(CVIR_2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_TTO_ARV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TTO_ARV,'1','2')) AND ( .NOT. EMPTY(TTO_ARV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_E_TTO_ARV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(E_TTO_ARV,'1','2','3','4')) OR ( EMPTY(E_TTO_ARV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_INI_TTO_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INI_TTO_IN,'1','2')) OR ( EMPTY(INI_TTO_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_E_TTO_INTR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(E_TTO_INTR,'1','2')) OR ( EMPTY(E_TTO_INTR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_TIPO_PAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_PAR,'1','2')) AND ( .NOT. EMPTY(TIPO_PAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_FEC_PARTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_PARTO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_CONDIC_RN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONDIC_RN,'1','2')) AND ( .NOT. EMPTY(CONDIC_RN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_MOTIVO_SAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOTIVO_SAL,'1','2','3','4')) AND ( .NOT. EMPTY(MOTIVO_SAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_28_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


