FUNCTION FieldRuleFor_eventos_19_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_ANT_HIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANT_HIB,'1','2','3')) AND ( .NOT. EMPTY(ANT_HIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_CARNE_HIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_HIB,'1','2')) OR ( EMPTY(CARNE_HIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_MENINGOCOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MENINGOCOC,'1','2','3')) AND ( .NOT. EMPTY(MENINGOCOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_CARNE_MEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_MEN,'1','2')) OR ( EMPTY(CARNE_MEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_NEUMOCOCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NEUMOCOCO,'1','2','3')) AND ( .NOT. EMPTY(NEUMOCOCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_CARNE_NEU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_NEU,'1','2')) OR ( EMPTY(CARNE_NEU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_RIG_NUCA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RIG_NUCA,'1','2')) AND ( .NOT. EMPTY(RIG_NUCA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_IRRI_MEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IRRI_MEN,'1','2')) AND ( .NOT. EMPTY(IRRI_MEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_RASH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RASH,'1','2')) AND ( .NOT. EMPTY(RASH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_AFONTANELA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AFONTANELA,'1','2')) AND ( .NOT. EMPTY(AFONTANELA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_ALT_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALT_CON,'1','2')) AND ( .NOT. EMPTY(ALT_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_USO_ANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USO_ANT,'1','2')) AND ( .NOT. EMPTY(USO_ANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_19_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


