FUNCTION FieldRuleFor_brotes_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRU_1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRU_1)>=0 AND ISNUMERIC(GRU_1)) OR  (EMPTY(GRU_1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRU_2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRU_2)>=0 AND ISNUMERIC(GRU_2)) OR  (EMPTY(GRU_2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_3
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_3)>=0 AND ISNUMERIC(GRUPO_3)) OR  (EMPTY(GRUPO_3)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_4
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_4)>=0 AND ISNUMERIC(GRUPO_4)) OR  (EMPTY(GRUPO_4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_5
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_5)>=0 AND ISNUMERIC(GRUPO_5)) OR  (EMPTY(GRUPO_5)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_6
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_6)>=0 AND ISNUMERIC(GRUPO_6)) OR  (EMPTY(GRUPO_6)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_7
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_7)>=0 AND ISNUMERIC(GRUPO_7)) OR  (EMPTY(GRUPO_7)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_8
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_8)>=0 AND ISNUMERIC(GRUPO_8)) OR  (EMPTY(GRUPO_8)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_9
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_9)>=0 AND ISNUMERIC(GRUPO_9)) OR  (EMPTY(GRUPO_9)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_10
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_10)>=0 AND ISNUMERIC(GRUPO_10)) OR  (EMPTY(GRUPO_10)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_11
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_11)>=0 AND ISNUMERIC(GRUPO_11)) OR  (EMPTY(GRUPO_11)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_12
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_12)>=0 AND ISNUMERIC(GRUPO_12)) OR  (EMPTY(GRUPO_12)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_13
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_13)>=0 AND ISNUMERIC(GRUPO_13)) OR  (EMPTY(GRUPO_13)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_14
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_14)>=0 AND ISNUMERIC(GRUPO_14)) OR  (EMPTY(GRUPO_14)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_15
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_15)>=0 AND ISNUMERIC(GRUPO_15)) OR  (EMPTY(GRUPO_15)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_16
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_16)>=0 AND ISNUMERIC(GRUPO_16)) OR  (EMPTY(GRUPO_16)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_17
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_17)>=0 AND ISNUMERIC(GRUPO_17)) OR  (EMPTY(GRUPO_17)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_GRUPO_18
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GRUPO_18)>=0 AND ISNUMERIC(GRUPO_18)) OR  (EMPTY(GRUPO_18)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_CAS_PRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_PRO)>=0 AND ISNUMERIC(CAS_PRO)) OR  (EMPTY(CAS_PRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_CAS_CONL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_CONL)>=0 AND ISNUMERIC(CAS_CONL)) OR  (EMPTY(CAS_CONL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_CAS_CONC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_CONC)>=0 AND ISNUMERIC(CAS_CONC)) OR  (EMPTY(CAS_CONC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_CAS_CONN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAS_CONN)>=0 AND ISNUMERIC(CAS_CONN)) OR  (EMPTY(CAS_CONN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_HOMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(HOMBRES)>=0 AND ISNUMERIC(HOMBRES)) AND  (.NOT. EMPTY(HOMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_MUJERES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MUJERES)>=0 AND ISNUMERIC(MUJERES)) AND  (.NOT. EMPTY(MUJERES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VIVOS)>=0 AND ISNUMERIC(VIVOS)) AND  (.NOT. EMPTY(VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MUERTOS)>=0 AND ISNUMERIC(MUERTOS)) AND  (.NOT. EMPTY(MUERTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR  (EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_FEC_AJU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(FEC_AJU))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_PTE_HOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PTE_HOS)>=0 AND ISNUMERIC(PTE_HOS)) AND  (.NOT. EMPTY(PTE_HOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_brotes_PTE_AMB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PTE_AMB)>=0 AND ISNUMERIC(PTE_AMB)) AND  (.NOT. EMPTY(PTE_AMB)))
	ENDIF
ENDFUNC


