FUNCTION FieldRuleFor_eventos_76_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_FEC_PROC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_PROC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_PROCEDIMIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROCEDIMIE,'1','2','3','4','5')) AND ( .NOT. EMPTY(PROCEDIMIE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_CLASIF_ASA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLASIF_ASA,'1','2','3','4','5')) OR ( EMPTY(CLASIF_ASA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_TIPOHERIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPOHERIDA,'1','2')) OR ( EMPTY(TIPOHERIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_CONTE_PROC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONTE_PROC,'1','2')) OR ( EMPTY(CONTE_PROC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_PRF_ANTIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRF_ANTIB,'1','2')) OR ( EMPTY(PRF_ANTIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_PROF_PRIMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROF_PRIMA,'1','2')) AND ( .NOT. EMPTY(PROF_PRIMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_PROF_SECUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROF_SECUN,'1','2')) AND ( .NOT. EMPTY(PROF_SECUN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_ORG_ESPACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ORG_ESPACI,'1','2')) AND ( .NOT. EMPTY(ORG_ESPACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_SUP_PRIMAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUP_PRIMAR,'1','2')) AND ( .NOT. EMPTY(SUP_PRIMAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_SUP_SECUND
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUP_SECUND,'1','2')) AND ( .NOT. EMPTY(SUP_SECUND)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_DUR_PROC_M
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((DUR_PROC_M>=1 AND ISNUMERIC(DUR_PROC_M)) OR (DUR_PROC_M=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_TIEM_ENTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIEM_ENTRE,'1','2','3')) OR ( EMPTY(TIEM_ENTRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_CUPS_PROCE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CUPS_PROCE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_TIEMPO_RUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TIEMPO_RUP)>=0  AND  VAL(TIEMPO_RUP) <= 2880 AND ISNUMERIC(TIEMPO_RUP)) OR ( EMPTY(TIEMPO_RUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_DIABET_MEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABET_MEL,'1','2')) OR ( EMPTY(DIABET_MEL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO>=1.0  AND PESO <=350.0 AND ISNUMERIC(PESO)) OR (PESO=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_TALLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA>= 0.30  AND TALLA <= 2.50 AND ISNUMERIC(TALLA)) OR (TALLA=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_76_DETEC_INFE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DETEC_INFE,'1','2','3','4')) AND ( .NOT. EMPTY(DETEC_INFE)))
	ENDIF
ENDFUNC


