FUNCTION FieldRuleFor_Eventos_45_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_VIG_ACTIVA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIG_ACTIVA,'1','2')) AND ( .NOT. EMPTY(VIG_ACTIVA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_SINTOMATIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINTOMATIC,'1','2')) AND ( .NOT. EMPTY(SINTOMATIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_CLAS_CASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_CASO,'1','2')) AND ( .NOT. EMPTY(CLAS_CASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_NUEVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NUEVO,'1','2')) AND ( .NOT. EMPTY(NUEVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_RECRUDECE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RECRUDECE,'1','2')) AND ( .NOT. EMPTY(RECRUDECE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_TRIMESTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRIMESTRE,'1','2','3')) OR ( EMPTY(TRIMESTRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_TIPOEXAMEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(TIPOEXAMEN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_TRATAMIENT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRATAMIENT,'1','2','3','4','5','6','7')) AND ( .NOT. EMPTY(TRATAMIENT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_GAMETOCITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GAMETOCITO,'1','2')) AND ( .NOT. EMPTY(GAMETOCITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_RESP_DIAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(RESP_DIAG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_RESULT_EXA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULT_EXA,'1','2')) AND ( .NOT. EMPTY(RESULT_EXA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_FEC_RESULT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_RESULT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_45_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


