FUNCTION FieldRuleFor_eventos_81_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MES)>=1  AND  VAL(MES) <=12 AND ISNUMERIC(MES)) AND ( .NOT. EMPTY(MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(AÑO)>=2011 AND ISNUMERIC(AÑO)) AND ( .NOT. EMPTY(AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_CAM_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_CAM_UCIA)>=1 AND ISNUMERIC(T_CAM_UCIA)) OR ( EMPTY(T_CAM_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_TIPOS_VIGI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPOS_VIGI,'1','2','3')) AND ( .NOT. EMPTY(TIPOS_VIGI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_DCO_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_DCO_UCIA)>=1 AND ISNUMERIC(T_DCO_UCIA)) OR ( EMPTY(T_DCO_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_DCD_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_DCD_UCIA)>=1 AND ISNUMERIC(T_DCD_UCIA)) OR ( EMPTY(T_DCD_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_PRO_O_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PRO_O_UCIA)>=0.00  AND  VAL(PRO_O_UCIA) <=1.00 AND ISNUMERIC(PRO_O_UCIA)) OR ( EMPTY(PRO_O_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CEF_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CEF_UCIA)>=0.0 AND ISNUMERIC(G_CEF_UCIA)) OR ( EMPTY(G_CEF_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CEF_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CEF_A)>= 0  AND  VAL(DDD_CEF_A) <=150 AND ISNUMERIC(DDD_CEF_A)) OR ( EMPTY(DDD_CEF_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_MER_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_MER_UCIA)>=0.0 AND ISNUMERIC(G_MER_UCIA)) OR ( EMPTY(G_MER_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_MER_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_MER_A)>= 0  AND  VAL(DDD_MER_A) <=150 AND ISNUMERIC(DDD_MER_A)) OR ( EMPTY(DDD_MER_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_PIP_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_PIP_UCIA)>=0.0 AND ISNUMERIC(G_PIP_UCIA)) OR ( EMPTY(G_PIP_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_PIP_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_PIP_A)>= 0  AND  VAL(DDD_PIP_A) <=150 AND ISNUMERIC(DDD_PIP_A)) OR ( EMPTY(DDD_PIP_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_VAN_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_VAN_UCIA)>=0.0 AND ISNUMERIC(G_VAN_UCIA)) OR ( EMPTY(G_VAN_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_VAN_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_VAN_A)>= 0  AND  VAL(DDD_VAN_A) <=150 AND ISNUMERIC(DDD_VAN_A)) OR ( EMPTY(DDD_VAN_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_CAM_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_CAM_SHA)>=1 AND ISNUMERIC(T_CAM_SHA)) OR ( EMPTY(T_CAM_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_DCO_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_DCO_SHA)>=1 AND ISNUMERIC(T_DCO_SHA)) OR ( EMPTY(T_DCO_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_T_DCD_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(T_DCD_SHA)>=1 AND ISNUMERIC(T_DCD_SHA)) OR ( EMPTY(T_DCD_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_PRO_O_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PRO_O_SHA)>=0.00  AND  VAL(PRO_O_SHA) <=1.00 AND ISNUMERIC(PRO_O_SHA)) OR ( EMPTY(PRO_O_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CEF_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CEF_SHA)>=0.0 AND ISNUMERIC(G_CEF_SHA)) OR ( EMPTY(G_CEF_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CEF_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CEF_S)>= 0  AND  VAL(DDD_CEF_S) <=150 AND ISNUMERIC(DDD_CEF_S)) OR ( EMPTY(DDD_CEF_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CIPP_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CIPP_SHA)>=0.0 AND ISNUMERIC(G_CIPP_SHA)) OR ( EMPTY(G_CIPP_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CIPP_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CIPP_S)>= 0  AND  VAL(DDD_CIPP_S) <=150 AND ISNUMERIC(DDD_CIPP_S)) OR ( EMPTY(DDD_CIPP_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CIPE_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CIPE_SHA)>=0.0 AND ISNUMERIC(G_CIPE_SHA)) OR ( EMPTY(G_CIPE_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CIPE_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CIPE_S)>= 0  AND  VAL(DDD_CIPE_S) <=150 AND ISNUMERIC(DDD_CIPE_S)) OR ( EMPTY(DDD_CIPE_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_MER_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_MER_SHA)>=0.0 AND ISNUMERIC(G_MER_SHA)) OR ( EMPTY(G_MER_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_MER_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_MER_S)>= 0  AND  VAL(DDD_MER_S) <=150 AND ISNUMERIC(DDD_MER_S)) OR ( EMPTY(DDD_MER_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_PIP_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_PIP_SHA)>=0.0 AND ISNUMERIC(G_PIP_SHA)) OR ( EMPTY(G_PIP_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_PIP_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_PIP_S)>= 0  AND  VAL(DDD_PIP_S) <=150 AND ISNUMERIC(DDD_PIP_S)) OR ( EMPTY(DDD_PIP_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_VAN_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_VAN_SHA)>=0.0 AND ISNUMERIC(G_VAN_SHA)) OR ( EMPTY(G_VAN_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_VAN_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_VAN_S)>= 0  AND  VAL(DDD_VAN_S) <=150 AND ISNUMERIC(DDD_VAN_S)) OR ( EMPTY(DDD_VAN_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_ERT_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_ERT_SHA)>=0.0 AND ISNUMERIC(G_ERT_SHA)) OR ( EMPTY(G_ERT_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_ERT_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_ERT_S)>= 0  AND  VAL(DDD_ERT_S) <=150 AND ISNUMERIC(DDD_ERT_S)) OR ( EMPTY(DDD_ERT_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CEFE_SHA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CEFE_SHA)>=0.0 AND ISNUMERIC(G_CEFE_SHA)) OR ( EMPTY(G_CEFE_SHA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CEFE_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CEFE_S)>= 0  AND  VAL(DDD_CEFE_S) <=150 AND ISNUMERIC(DDD_CEFE_S)) OR ( EMPTY(DDD_CEFE_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_ERT_UCIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_ERT_UCIA)>=0.0 AND ISNUMERIC(G_ERT_UCIA)) OR ( EMPTY(G_ERT_UCIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_ERT_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_ERT_A)>= 0  AND  VAL(DDD_ERT_A) <=150 AND ISNUMERIC(DDD_ERT_A)) OR ( EMPTY(DDD_ERT_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_G_CEFE_UCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(G_CEFE_UCI)>=0.0 AND ISNUMERIC(G_CEFE_UCI)) OR ( EMPTY(G_CEFE_UCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_81_DDD_CEFE_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(DDD_CEFE_A)>= 0  AND  VAL(DDD_CEFE_A) <=150 AND ISNUMERIC(DDD_CEFE_A)) OR ( EMPTY(DDD_CEFE_A)))
	ENDIF
ENDFUNC


