FUNCTION FieldRuleFor_Contactos_PRI_NOM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PRI_NOM))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_PRI_APE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PRI_APE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_EDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD)>=1  AND  VAL(EDAD) <=130 AND ISNUMERIC(EDAD)) AND ( .NOT. EMPTY(EDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_UNI_MED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UNI_MED,'1','2','3','4','5')) AND ( .NOT. EMPTY(UNI_MED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_SEXO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEXO,'M','F')) AND ( .NOT. EMPTY(SEXO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_DIR_RES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIR_RES)) OR INLIST(COD_EVE,'357','351','352')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_OCUPACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(OCUPACION)) OR INLIST(COD_EVE,'357','351','352')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TIP_SS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_SS,'C','S','P','E','N','I')) AND ( .NOT. EMPTY(TIP_SS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_COD_MUN_R
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_MUN_R))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) AND ( .NOT. EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TELEFONO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(TELEFONO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_DESPLAZAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESPLAZAMI,'1','2')) AND ( .NOT. EMPTY(DESPLAZAMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_ID_PADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ID_PADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TIPO_CONTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_CONTA,'1','2','3','4','5')) AND ( .NOT. EMPTY(TIPO_CONTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_ROL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ROL,'1','2')) AND ( .NOT. EMPTY(ROL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_FEC_AJU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_AJU))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'3','5','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_FECINI_GRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FECINI_GRA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_EST_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_INGR,0,2,3)) OR (EST_INGR=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_ID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ID) OR NOTIF_IAAS!='1')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TOMA_MUEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOMA_MUEST,'1','2')) AND ( .NOT. EMPTY(TOMA_MUEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_RESULTADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTADO,'1','2')) OR ( EMPTY(RESULTADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_TIPIDE_POS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPIDE_POS,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIPIDE_POS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_NUMIDE_POS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUMIDE_POS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_COD_EVEPOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVEPOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Contactos_SINTOMATIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINTOMATIC,'1','2')) AND ( .NOT. EMPTY(SINTOMATIC)))
	ENDIF
ENDFUNC


