FUNCTION FieldRuleFor_eventos_55_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_TIPO_CA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_CA,'1','2','3','4','5','6','7','8','9','10','11','12','13','14')) AND ( .NOT. EMPTY(TIPO_CA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_CLA_RIESGO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_RIESGO,'1','2','3')) OR ( EMPTY(CLA_RIESGO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_RECAIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RECAIDA,'1','2')) AND ( .NOT. EMPTY(RECAIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_DX_OTRO_CA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DX_OTRO_CA,'1','2','3','4','5','6','7','8')) OR ( EMPTY(DX_OTRO_CA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_CAUS_MUE_D
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAUS_MUE_D,'1','2','3')) OR ( EMPTY(CAUS_MUE_D)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_SIT_DEF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_DEF,'1','2','3','4')) OR ( EMPTY(SIT_DEF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_REM_INST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REM_INST,'1','2')) AND ( .NOT. EMPTY(REM_INST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_55_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


