FUNCTION FieldRuleFor_eventos_10_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_CLA_INI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_INI,'1','2')) AND ( .NOT. EMPTY(CLA_INI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_MUN_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MUN_NAC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_FUE_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUE_NOT,'1','2','3','4','5','8','9')) AND ( .NOT. EMPTY(FUE_NOT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_NOM_MAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_MAD))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_EDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD)>=6 AND ISNUMERIC(EDAD)) AND ( .NOT. EMPTY(EDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_NUM_EMB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NUM_EMB)>= 1  AND  VAL(NUM_EMB) <=25 AND ISNUMERIC(NUM_EMB)) AND ( .NOT. EMPTY(NUM_EMB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_VIAJES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIAJES,'1','2','9')) AND ( .NOT. EMPTY(VIAJES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_SE_VIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SE_VIA)>= 1  AND  VAL(SE_VIA) <= 45 AND ISNUMERIC(SE_VIA)) OR ( EMPTY(SE_VIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_APGAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(APGAR)>= 1  AND  VAL(APGAR) <= 10 AND ISNUMERIC(APGAR)) AND ( .NOT. EMPTY(APGAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_BPN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BPN,'1','2','9')) AND ( .NOT. EMPTY(BPN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PESO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_PEQ_EDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEQ_EDA,'1','2','9')) AND ( .NOT. EMPTY(PEQ_EDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_SEMANAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SEMANAS)>= 20  AND  VAL(SEMANAS) <= 45 AND ISNUMERIC(SEMANAS)) OR ( EMPTY(SEMANAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_CATARATAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CATARATAS,'1','2','9')) AND ( .NOT. EMPTY(CATARATAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_GLAUCOMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GLAUCOMA,'1','2','9')) AND ( .NOT. EMPTY(GLAUCOMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_RETINOPATI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RETINOPATI,'1','2','9')) AND ( .NOT. EMPTY(RETINOPATI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_OTR_OJO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_OJO,'1','2','9')) AND ( .NOT. EMPTY(OTR_OJO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_PER_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PER_CON,'1','2','9')) AND ( .NOT. EMPTY(PER_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_EST_ART
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_ART,'1','2','9')) AND ( .NOT. EMPTY(EST_ART)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_OTR_COR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_COR,'1','2','9')) AND ( .NOT. EMPTY(OTR_COR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_SORDERA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SORDERA,'1','2','9')) AND ( .NOT. EMPTY(SORDERA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_OTR_OID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_OID,'1','2','9')) AND ( .NOT. EMPTY(OTR_OID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_MICROCEFAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICROCEFAL,'1','2','9')) AND ( .NOT. EMPTY(MICROCEFAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_RET_DES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RET_DES,'1','2','9')) AND ( .NOT. EMPTY(RET_DES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_PURPURA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PURPURA,'1','2','9')) AND ( .NOT. EMPTY(PURPURA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2','9')) AND ( .NOT. EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_ICT_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICT_NAC,'1','2','9')) AND ( .NOT. EMPTY(ICT_NAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_ESPLENOMEG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESPLENOMEG,'1','2','9')) AND ( .NOT. EMPTY(ESPLENOMEG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_OST_RAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OST_RAD,'1','2','9')) AND ( .NOT. EMPTY(OST_RAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_MENINGOENC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MENINGOENC,'1','2','9')) AND ( .NOT. EMPTY(MENINGOENC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_OTRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO,'1','2','9')) AND ( .NOT. EMPTY(OTRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_DX_FIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DX_FIN,'1','2','9')) AND ( .NOT. EMPTY(DX_FIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_10_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


