FUNCTION FieldRuleFor_eventos_47_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_TIP_DOC_RN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_DOC_RN,'RC','MS','PE','CN')) AND ( .NOT. EMPTY(TIP_DOC_RN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_NO_IDE_RN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NO_IDE_RN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_FECHA_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FECHA_NAC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_EDAD_RN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_RN>=0 AND ISNUMERIC(EDAD_RN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_SEXO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEXO,'M','F')) AND ( .NOT. EMPTY(SEXO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_PESO_NACER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_NACER)>=900  AND  VAL(PESO_NACER) <=2499 AND ISNUMERIC(PESO_NACER)) AND ( .NOT. EMPTY(PESO_NACER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_TALLA_NACE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_NACE>=30.0  AND TALLA_NACE <=55.0 AND ISNUMERIC(TALLA_NACE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_SEM_GEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SEM_GEST)>=37  AND  VAL(SEM_GEST) <=45 AND ISNUMERIC(SEM_GEST)) AND ( .NOT. EMPTY(SEM_GEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_CLA_PES_NA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_PES_NA,'1','2')) AND ( .NOT. EMPTY(CLA_PES_NA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_SIT_ATE_PA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_ATE_PA,'1','2','3','4')) AND ( .NOT. EMPTY(SIT_ATE_PA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_MULT_EMBAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MULT_EMBAR,'1','2','3')) AND ( .NOT. EMPTY(MULT_EMBAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_NUM_EM_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_EM_PRE>= 0  AND NUM_EM_PRE <=20 AND ISNUMERIC(NUM_EM_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_NUM_HI_VIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_HI_VIV>= 1  AND NUM_HI_VIV <=20 AND ISNUMERIC(NUM_HI_VIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_NIV_EDU_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV_EDU_MA,'1','2','3','4')) OR ( EMPTY(NIV_EDU_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_47_EST_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_INGR,0,2,3)) OR (EST_INGR=0))
	ENDIF
ENDFUNC


