FUNCTION FieldRuleFor_eventos_85_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_COMPL_NEUR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMPL_NEUR,'1','2')) AND ( .NOT. EMPTY(COMPL_NEUR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_DESPLAZAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESPLAZAMI,'1','2')) OR ( EMPTY(DESPLAZAMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_HUBO_1_ECO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HUBO_1_ECO,'1','2')) OR ( EMPTY(HUBO_1_ECO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_EDAD_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_GES)>= 0  AND  VAL(EDAD_GES) <= 42 AND ISNUMERIC(EDAD_GES)) OR ( EMPTY(EDAD_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_SEG_EAPB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEG_EAPB,'1','2','3')) OR ( EMPTY(SEG_EAPB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_GES_TER_EM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GES_TER_EM,'1','2')) OR ( EMPTY(GES_TER_EM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_CON_FIN_PR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_FIN_PR,'1','2','3')) OR ( EMPTY(CON_FIN_PR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_PER_CEFALI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PER_CEFALI>=0  AND PER_CEFALI <= 99 AND ISNUMERIC(PER_CEFALI)) OR (PER_CEFALI=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_AUTOPSIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AUTOPSIA,'1','2')) OR ( EMPTY(AUTOPSIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_DEF_CONGEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEF_CONGEN,'1','2')) OR ( EMPTY(DEF_CONGEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_MUE_SUERO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_SUERO,'1','2')) OR ( EMPTY(MUE_SUERO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_MUE_CORDON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_CORDON,'1','2')) OR ( EMPTY(MUE_CORDON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_EXANTEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EXANTEMA,'1','2')) AND ( .NOT. EMPTY(EXANTEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_HIPEREMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPEREMIA,'1','2')) AND ( .NOT. EMPTY(HIPEREMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_ARTRALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIAS,'1','2')) AND ( .NOT. EMPTY(ARTRALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIALGIAS,'1','2')) AND ( .NOT. EMPTY(MIALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_85_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


