FUNCTION FieldRuleFor_eventos_48_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_PTE_REMTDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PTE_REMTDA,'1','2')) AND ( .NOT. EMPTY(PTE_REMTDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_TIEM_REMIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TIEM_REMIS)>=0 AND ISNUMERIC(TIEM_REMIS)) OR ( EMPTY(TIEM_REMIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_GESTAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_GESTAC>=1  AND NUM_GESTAC <=19 AND ISNUMERIC(NUM_GESTAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_PARVAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_PARVAG>=0  AND NUM_PARVAG <=19 AND ISNUMERIC(NUM_PARVAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_CESARE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_CESARE>=0  AND NUM_CESARE <=19 AND ISNUMERIC(NUM_CESARE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_ABORTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_ABORTO>=0  AND NUM_ABORTO <=19 AND ISNUMERIC(NUM_ABORTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_MOLAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MOLAS>=0  AND NUM_MOLAS <=19 AND ISNUMERIC(NUM_MOLAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_ECTOPI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_ECTOPI>=0  AND NUM_ECTOPI <=19 AND ISNUMERIC(NUM_ECTOPI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_MUERTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MUERTO>=0  AND NUM_MUERTO <=19 AND ISNUMERIC(NUM_MUERTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NUM_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_VIVOS>=0  AND NUM_VIVOS <=19 AND ISNUMERIC(NUM_VIVOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_NO_CON_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_CON_PRE>=0  AND NO_CON_PRE <=50 AND ISNUMERIC(NO_CON_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_SEM_C_PREN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((SEM_C_PREN>=0  AND SEM_C_PREN <=40 AND ISNUMERIC(SEM_C_PREN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_TERM_GESTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TERM_GESTA,'1','2','3','4','5')) AND ( .NOT. EMPTY(TERM_GESTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_MOC_REL_TG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOC_REL_TG,'1','2','3')) AND ( .NOT. EMPTY(MOC_REL_TG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_ECLAMPSIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ECLAMPSIA,'1','2')) AND ( .NOT. EMPTY(ECLAMPSIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CHOQ_SEPTI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CHOQ_SEPTI,'1','2')) AND ( .NOT. EMPTY(CHOQ_SEPTI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CHOQ_HIPOV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CHOQ_HIPOV,'1','2')) AND ( .NOT. EMPTY(CHOQ_HIPOV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_CARD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_CARD,'1','2')) AND ( .NOT. EMPTY(FALLA_CARD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_RENA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_RENA,'1','2')) AND ( .NOT. EMPTY(FALLA_RENA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_HEPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_HEPA,'1','2')) AND ( .NOT. EMPTY(FALLA_HEPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_CERE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_CERE,'1','2')) AND ( .NOT. EMPTY(FALLA_CERE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_RESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_RESP,'1','2')) AND ( .NOT. EMPTY(FALLA_RESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_FALLA_COAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_COAG,'1','2')) AND ( .NOT. EMPTY(FALLA_COAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CIR_ADICIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIR_ADICIO,'1','2')) AND ( .NOT. EMPTY(CIR_ADICIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_TTL_CRITER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TTL_CRITER>=1  AND TTL_CRITER <=32 AND ISNUMERIC(TTL_CRITER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_DIAS_HOSPI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((DIAS_HOSPI>=0 AND ISNUMERIC(DIAS_HOSPI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CIR_ADIC_1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIR_ADIC_1,'1','2','3','4')) OR ( EMPTY(CIR_ADIC_1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CIR_ADIC_2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIR_ADIC_2,'1','2','3','4')) OR ( EMPTY(CIR_ADIC_2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CAUS_PRINC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CAUS_PRINC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_CAUS_AGRUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CAUS_AGRUP))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_PRECLAMPSI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRECLAMPSI,'1','2')) AND ( .NOT. EMPTY(PRECLAMPSI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_RUPT_UTERI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RUPT_UTERI,'1','2')) AND ( .NOT. EMPTY(RUPT_UTERI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_48_EGRESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EGRESO,'1','2')) OR ( EMPTY(EGRESO)))
	ENDIF
ENDFUNC


