FUNCTION FieldRuleFor_eventos_16_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_CLAS_FINAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_FINAL,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(CLAS_FINAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_HIJ_MAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIJ_MAD,'1','2')) AND ( .NOT. EMPTY(HIJ_MAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_COM_SEX_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_SEX_IN,'1','2')) AND ( .NOT. EMPTY(COM_SEX_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_MULTITRANS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MULTITRANS,'1','2')) AND ( .NOT. EMPTY(MULTITRANS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_HEMODIALIZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMODIALIZ,'1','2')) AND ( .NOT. EMPTY(HEMODIALIZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_TRA_SAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRA_SAL,'1','2')) AND ( .NOT. EMPTY(TRA_SAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_DRO_PAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DRO_PAR,'1','2')) AND ( .NOT. EMPTY(DRO_PAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_CON_POR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_POR,'1','2')) AND ( .NOT. EMPTY(CON_POR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_CON_SEX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_SEX,'1','2')) AND ( .NOT. EMPTY(CON_SEX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_MET_TRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MET_TRA,'1','2','3','4')) AND ( .NOT. EMPTY(MET_TRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_DON_SAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DON_SAN,'1','2')) AND ( .NOT. EMPTY(DON_SAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_SEM_GES_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SEM_GES_IN)>=0  AND  VAL(SEM_GES_IN) <=45 AND ISNUMERIC(SEM_GES_IN)) OR ( EMPTY(SEM_GES_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_VAC_ANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_ANT,'1','2')) AND ( .NOT. EMPTY(VAC_ANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_FUENTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUENTE,'1','2','3')) AND ( .NOT. EMPTY(FUENTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_PRES_SYS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRES_SYS,'1','2')) AND ( .NOT. EMPTY(PRES_SYS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_CUALES_COM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CUALES_COM,'1','2','3','4','5')) AND ( .NOT. EMPTY(CUALES_COM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS','PE')) OR ( EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_VAC_REC_NA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_REC_NA,'1','2','3','4','5')) OR ( EMPTY(VAC_REC_NA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_GAM_REC_NA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GAM_REC_NA,'1','2','3','4','5')) OR ( EMPTY(GAM_REC_NA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_HOMOSEXUAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HOMOSEXUAL,'1','2')) AND ( .NOT. EMPTY(HOMOSEXUAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_BISEXUAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BISEXUAL,'1','2')) AND ( .NOT. EMPTY(BISEXUAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_ACC_LABORA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACC_LABORA,'1','2')) AND ( .NOT. EMPTY(ACC_LABORA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_TRANS_ORGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRANS_ORGA,'1','2')) AND ( .NOT. EMPTY(TRANS_ORGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_PROCEDIMIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROCEDIMIE,'1','2')) AND ( .NOT. EMPTY(PROCEDIMIE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_ACUPUNTURA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACUPUNTURA,'1','2')) AND ( .NOT. EMPTY(ACUPUNTURA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_COINF_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COINF_VIH,'1','2')) AND ( .NOT. EMPTY(COINF_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_16_MOMDIAG_GE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOMDIAG_GE,'1','2','3','4')) OR ( EMPTY(MOMDIAG_GE)))
	ENDIF
ENDFUNC


