FUNCTION FieldRuleFor_eventos_09_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_TIP_PAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_PAR,'1','2','3','4','5')) OR ( EMPTY(TIP_PAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_SIT_DEF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_DEF,'6','8','9','10','11','12','13','7')) AND ( .NOT. EMPTY(SIT_DEF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_GESTACIONE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GESTACIONE)>=1  AND  VAL(GESTACIONE) <= 25 AND ISNUMERIC(GESTACIONE)) AND ( .NOT. EMPTY(GESTACIONE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_PARTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PARTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_CESAREAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CESAREAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_ABORTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ABORTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MUERTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(VIVOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NUM_CON)>=0  AND  VAL(NUM_CON) <=25 AND ISNUMERIC(NUM_CON)) AND ( .NOT. EMPTY(NUM_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_SI_CTRL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SI_CTRL)>= 1  AND  VAL(SI_CTRL) <= 45 AND ISNUMERIC(SI_CTRL)) OR ( EMPTY(SI_CTRL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_PAR_ATE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PAR_ATE,'1','2','3','4','5','6','7','8')) OR ( EMPTY(PAR_ATE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_SITIO_PART
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SITIO_PART,'1','2','3')) OR ( EMPTY(SITIO_PART)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_NIV_ATE_PA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV_ATE_PA,'1','2','3')) OR ( EMPTY(NIV_ATE_PA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_MOM_OCU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOM_OCU,'1','2','3','5','6','7')) AND ( .NOT. EMPTY(MOM_OCU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_EDA_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDA_GES)>= 20  AND  VAL(EDA_GES) <= 45 AND ISNUMERIC(EDA_GES)) AND ( .NOT. EMPTY(EDA_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_EDAD_NEO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_NEO)>=0  AND  VAL(EDAD_NEO) <=28 AND ISNUMERIC(EDAD_NEO)) OR ( EMPTY(EDAD_NEO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO)>= 300  AND  VAL(PESO) <= 6000 AND ISNUMERIC(PESO)) AND ( .NOT. EMPTY(PESO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_TALLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TALLA)>=18  AND  VAL(TALLA) <=53 AND ISNUMERIC(TALLA)) AND ( .NOT. EMPTY(TALLA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_SEXO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEXO,'M','F','I')) AND ( .NOT. EMPTY(SEXO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_CAU_MTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAU_MTE,'1','2','3')) AND ( .NOT. EMPTY(CAU_MTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_09_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


