FUNCTION FieldRuleFor_eventos_42_HIPOTENSIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOTENSIO,'1','2')) OR ( EMPTY(HIPOTENSIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_HEPATOMEG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEG,'1','2')) OR ( EMPTY(HEPATOMEG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_DESPLAZAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESPLAZAMI,'1','2')) AND ( .NOT. EMPTY(DESPLAZAMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_FAMANTDNGU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FAMANTDNGU,'1','2','3')) AND ( .NOT. EMPTY(FAMANTDNGU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) OR ( EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALGIAS,'1','2')) OR ( EMPTY(MALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) OR ( EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_DOLRRETROO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLRRETROO,'1','2')) OR ( EMPTY(DOLRRETROO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_ARTRALGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIA,'1','2')) OR ( EMPTY(ARTRALGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_ERUPCIONR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ERUPCIONR,'1','2')) OR ( EMPTY(ERUPCIONR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_HEM_MUCOSA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEM_MUCOSA,'1','2')) OR ( EMPTY(HEM_MUCOSA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_HIPOTERMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOTERMIA,'1','2')) OR ( EMPTY(HIPOTERMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_AUM_HEMATO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AUM_HEMATO,'1','2')) OR ( EMPTY(AUM_HEMATO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_CAIDA_PLAQ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAIDA_PLAQ,'1','2')) OR ( EMPTY(CAIDA_PLAQ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_ACUM_LIQUI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACUM_LIQUI,'1','2')) OR ( EMPTY(ACUM_LIQUI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_EXTRAVASAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EXTRAVASAC,'1','2')) OR ( EMPTY(EXTRAVASAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_HEMORR_HEM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMORR_HEM,'1','2')) OR ( EMPTY(HEMORR_HEM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_DAÑO_ORGAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DAÑO_ORGAN,'1','2')) OR ( EMPTY(DAÑO_ORGAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_CHOQUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CHOQUE,'1','2')) OR ( EMPTY(CHOQUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) OR ( EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_SOMNOLENCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SOMNOLENCI,'1','2')) OR ( EMPTY(SOMNOLENCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_DOLOR_ABDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR_ABDO,'1','2')) OR ( EMPTY(DOLOR_ABDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) OR ( EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESTTEJID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESTTEJID,'1','2')) OR ( EMPTY(MUESTTEJID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESHIGADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESHIGADO,'1','2')) OR ( EMPTY(MUESHIGADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESBAZO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESBAZO,'1','2')) OR ( EMPTY(MUESBAZO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESPULMON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESPULMON,'1','2')) OR ( EMPTY(MUESPULMON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESCEREBR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESCEREBR,'1','2')) OR ( EMPTY(MUESCEREBR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESMIOCAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESMIOCAR,'1','2')) OR ( EMPTY(MUESMIOCAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESMEDULA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESMEDULA,'1','2')) OR ( EMPTY(MUESMEDULA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_MUESRIÑON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUESRIÑON,'1','2')) OR ( EMPTY(MUESRIÑON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_CLASFINAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLASFINAL,'0','1','2','3')) AND ( .NOT. EMPTY(CLASFINAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_CONDUCTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONDUCTA,'0','1','2','3','4','5')) AND ( .NOT. EMPTY(CONDUCTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_42_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


