FUNCTION FieldRuleFor_eventos_17_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_CARA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARA,'1','2')) OR ( EMPTY(CARA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_TRONCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRONCO,'1','2')) OR ( EMPTY(TRONCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_MIE_SUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIE_SUP,'1','2')) OR ( EMPTY(MIE_SUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_MIE_INF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIE_INF,'1','2')) OR ( EMPTY(MIE_INF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_MUC_AFE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUC_AFE,'1','2','3','4','5','6','7')) OR ( EMPTY(MUC_AFE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_RINORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RINORREA,'1','2')) OR ( EMPTY(RINORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_EPISTAXIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPISTAXIS,'1','2')) OR ( EMPTY(EPISTAXIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_ONASAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ONASAL,'1','2')) OR ( EMPTY(ONASAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_DISFONÍA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISFONÍA,'1','2')) OR ( EMPTY(DISFONÍA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_DISFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISFAGIA,'1','2')) OR ( EMPTY(DISFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_HIPEREMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPEREMIA,'1','2')) OR ( EMPTY(HIPEREMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_ULCERACIÓN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ULCERACIÓN,'1','2')) OR ( EMPTY(ULCERACIÓN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_PERFORACIÓ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PERFORACIÓ,'1','2')) OR ( EMPTY(PERFORACIÓ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_DESTRUCCIÓ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESTRUCCIÓ,'1','2')) OR ( EMPTY(DESTRUCCIÓ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) OR ( EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2')) OR ( EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_ESPLENOMEG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESPLENOMEG,'1','2')) OR ( EMPTY(ESPLENOMEG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_ANEMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANEMIA,'1','2')) OR ( EMPTY(ANEMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_LEUCOPENIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LEUCOPENIA,'1','2')) OR ( EMPTY(LEUCOPENIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_TROMBOCITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TROMBOCITO,'1','2')) OR ( EMPTY(TROMBOCITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_COINFE_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COINFE_VIH,'1','2','3')) AND ( .NOT. EMPTY(COINFE_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_REC_TTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REC_TTO,'1','2')) AND ( .NOT. EMPTY(REC_TTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_PES_PTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PES_PTE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_MED_FOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MED_FOR,'1','2','3','4','5','6','7','8')) AND ( .NOT. EMPTY(MED_FOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_DIA_TTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIA_TTO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_TOT_AMP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TOT_AMP)>=0  AND  VAL(TOT_AMP) <=180 AND ISNUMERIC(TOT_AMP)) AND ( .NOT. EMPTY(TOT_AMP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_17_TTO_LOCAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TTO_LOCAL,'1','2')) OR ( EMPTY(TTO_LOCAL)))
	ENDIF
ENDFUNC


