FUNCTION FieldRuleFor_eventos_36_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIALGIAS,'1','2')) AND ( .NOT. EMPTY(MIALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2')) AND ( .NOT. EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_ICTERICIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICTERICIA,'1','2')) AND ( .NOT. EMPTY(ICTERICIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_PERROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PERROS,'1','2')) AND ( .NOT. EMPTY(PERROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_GATOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GATOS,'1','2')) AND ( .NOT. EMPTY(GATOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_BOVINOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BOVINOS,'1','2')) AND ( .NOT. EMPTY(BOVINOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_EQUINOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EQUINOS,'1','2')) AND ( .NOT. EMPTY(EQUINOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_PORCINOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PORCINOS,'1','2')) AND ( .NOT. EMPTY(PORCINOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_NINGUNO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NINGUNO,'1','2')) AND ( .NOT. EMPTY(NINGUNO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS,'1','2')) AND ( .NOT. EMPTY(OTROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_RATAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RATAS,'1','2')) AND ( .NOT. EMPTY(RATAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_ACUEDUCTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACUEDUCTO,'1','2')) AND ( .NOT. EMPTY(ACUEDUCTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_POZO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(POZO,'1','2')) AND ( .NOT. EMPTY(POZO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_RIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RIO,'1','2')) AND ( .NOT. EMPTY(RIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_TANQUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TANQUE,'1','2')) AND ( .NOT. EMPTY(TANQUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_ALCAN_DES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALCAN_DES,'1','2')) AND ( .NOT. EMPTY(ALCAN_DES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_C_AGU_ESTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(C_AGU_ESTA,'1','2')) AND ( .NOT. EMPTY(C_AGU_ESTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_REPRESA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REPRESA,'1','2')) AND ( .NOT. EMPTY(REPRESA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_RÍO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RÍO,'1','2')) AND ( .NOT. EMPTY(RÍO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_ARROYO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARROYO,'1','2')) AND ( .NOT. EMPTY(ARROYO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_LAGOLAGUNA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAGOLAGUNA,'1','2')) AND ( .NOT. EMPTY(LAGOLAGUNA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_SINANTECED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINANTECED,'1','2')) AND ( .NOT. EMPTY(SINANTECED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_D_RES_SOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(D_RES_SOL,'1','2')) AND ( .NOT. EMPTY(D_RES_SOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_36_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


