FUNCTION FieldRuleFor_eventos_80_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MES)>=1  AND  VAL(MES) <=12 AND ISNUMERIC(MES)) AND ( .NOT. EMPTY(MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(AÑO)>=2011 AND ISNUMERIC(AÑO)) AND ( .NOT. EMPTY(AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_SER_UCIV_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCIV_A)>=1  AND  VAL(SER_UCIV_A) <= 99 AND ISNUMERIC(SER_UCIV_A)) OR ( EMPTY(SER_UCIV_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAM_UCIV_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCIV_A)>=1  AND  VAL(CAM_UCIV_A) <= 99 AND ISNUMERIC(CAM_UCIV_A)) OR ( EMPTY(CAM_UCIV_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DIAS_P_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DIAS_P_A)>= 1  AND  VAL(N_DIAS_P_A) <= 9999 AND ISNUMERIC(N_DIAS_P_A)) OR ( EMPTY(N_DIAS_P_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_S_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_S_A)>=0  AND  VAL(N_C_NV_S_A) <=99 AND ISNUMERIC(N_C_NV_S_A)) OR ( EMPTY(N_C_NV_S_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_S_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_S_A)>=1  AND  VAL(N_DS_D_S_A) <=999 AND ISNUMERIC(N_DS_D_S_A)) OR ( EMPTY(N_DS_D_S_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_S_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_S_A)>=0.00  AND  VAL(TAS_IN_S_A) <=1000.00 AND ISNUMERIC(TAS_IN_S_A)) OR ( EMPTY(TAS_IN_S_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_V_A,'1','2')) OR ( EMPTY(CAS_PL_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_V_A)>=1  AND  VAL(N_C_PL_V_A) <=999 AND ISNUMERIC(N_C_PL_V_A)) OR ( EMPTY(N_C_PL_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_SER_UCIV_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCIV_N)>=1  AND  VAL(SER_UCIV_N) <=99 AND ISNUMERIC(SER_UCIV_N)) OR ( EMPTY(SER_UCIV_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAM_UCIV_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCIV_N)>=1  AND  VAL(CAM_UCIV_N) <=99 AND ISNUMERIC(CAM_UCIV_N)) OR ( EMPTY(CAM_UCIV_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DIAS_P_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DIAS_P_N)>=1  AND  VAL(N_DIAS_P_N) <=9999 AND ISNUMERIC(N_DIAS_P_N)) OR ( EMPTY(N_DIAS_P_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N1_S_N)>=0  AND  VAL(N_C_N1_S_N) <=99 AND ISNUMERIC(N_C_N1_S_N)) OR ( EMPTY(N_C_N1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C1_S_N)>=0  AND  VAL(N_D_C1_S_N) <=9999 AND ISNUMERIC(N_D_C1_S_N)) OR ( EMPTY(N_D_C1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P1_S_N)>=0  AND  VAL(N_D_P1_S_N) <=9999 AND ISNUMERIC(N_D_P1_S_N)) OR ( EMPTY(N_D_P1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I1_S_N)>=0.00  AND  VAL(TAS_I1_S_N) <=1000.00 AND ISNUMERIC(TAS_I1_S_N)) OR ( EMPTY(TAS_I1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D1_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D1_S_N)>=0  AND  VAL(P_U_D1_S_N) <=100.00 AND ISNUMERIC(P_U_D1_S_N)) OR ( EMPTY(P_U_D1_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N2_S_N)>=0  AND  VAL(N_C_N2_S_N) <=99 AND ISNUMERIC(N_C_N2_S_N)) OR ( EMPTY(N_C_N2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C2_S_N)>=0  AND  VAL(N_D_C2_S_N) <=9999 AND ISNUMERIC(N_D_C2_S_N)) OR ( EMPTY(N_D_C2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P2_S_N)>=0  AND  VAL(N_D_P2_S_N) <=9999 AND ISNUMERIC(N_D_P2_S_N)) OR ( EMPTY(N_D_P2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I2_S_N)>=0.00  AND  VAL(TAS_I2_S_N) <=1000.00 AND ISNUMERIC(TAS_I2_S_N)) OR ( EMPTY(TAS_I2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D2_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D2_S_N)>=0  AND  VAL(P_U_D2_S_N) <=100.00 AND ISNUMERIC(P_U_D2_S_N)) OR ( EMPTY(P_U_D2_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N3_S_N)>=0  AND  VAL(N_C_N3_S_N) <=99 AND ISNUMERIC(N_C_N3_S_N)) OR ( EMPTY(N_C_N3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C3_S_N)>=0  AND  VAL(N_D_C3_S_N) <=9999 AND ISNUMERIC(N_D_C3_S_N)) OR ( EMPTY(N_D_C3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P3_S_N)>=0  AND  VAL(N_D_P3_S_N) <=9999 AND ISNUMERIC(N_D_P3_S_N)) OR ( EMPTY(N_D_P3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I3_S_N)>=0.00  AND  VAL(TAS_I3_S_N) <=1000.00 AND ISNUMERIC(TAS_I3_S_N)) OR ( EMPTY(TAS_I3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D3_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D3_S_N)>=0  AND  VAL(P_U_D3_S_N) <=100.00 AND ISNUMERIC(P_U_D3_S_N)) OR ( EMPTY(P_U_D3_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N4_S_N)>=0  AND  VAL(N_C_N4_S_N) <=99 AND ISNUMERIC(N_C_N4_S_N)) OR ( EMPTY(N_C_N4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C4_S_N)>=0  AND  VAL(N_D_C4_S_N) <=9999 AND ISNUMERIC(N_D_C4_S_N)) OR ( EMPTY(N_D_C4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P4_S_N)>=0  AND  VAL(N_D_P4_S_N) <=9999 AND ISNUMERIC(N_D_P4_S_N)) OR ( EMPTY(N_D_P4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I4_S_N)>=0.00  AND  VAL(TAS_I4_S_N) <=1000.00 AND ISNUMERIC(TAS_I4_S_N)) OR ( EMPTY(TAS_I4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_USO_DI_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_USO_DI_S)>=1.00  AND  VAL(P_USO_DI_S) <=100.00 AND ISNUMERIC(P_USO_DI_S)) OR ( EMPTY(P_USO_DI_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_U_A)>=0  AND  VAL(N_C_NV_U_A) <=99 AND ISNUMERIC(N_C_NV_U_A)) OR ( EMPTY(N_C_NV_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_U_A)>=1  AND  VAL(N_DS_D_U_A) <=999 AND ISNUMERIC(N_DS_D_U_A)) OR ( EMPTY(N_DS_D_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_U_A)>=0.00  AND  VAL(TAS_IN_U_A) <=1000.00 AND ISNUMERIC(TAS_IN_U_A)) OR ( EMPTY(TAS_IN_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_PR_U_D_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PR_U_D_U_A)>=1.00  AND  VAL(PR_U_D_U_A) <=100.00 AND ISNUMERIC(PR_U_D_U_A)) OR ( EMPTY(PR_U_D_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_V_A)>=0  AND  VAL(N_C_NV_V_A) <=99 AND ISNUMERIC(N_C_NV_V_A)) OR ( EMPTY(N_C_NV_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_V_A)>=1  AND  VAL(N_DS_D_V_A) <=999 AND ISNUMERIC(N_DS_D_V_A)) OR ( EMPTY(N_DS_D_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_V_A)>=0.00  AND  VAL(TAS_IN_V_A) <=1000.00 AND ISNUMERIC(TAS_IN_V_A)) OR ( EMPTY(TAS_IN_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_PR_U_D_V_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PR_U_D_V_A)>=1.00  AND  VAL(PR_U_D_V_A) <=100.00 AND ISNUMERIC(PR_U_D_V_A)) OR ( EMPTY(PR_U_D_V_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_S_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_S_A,'1','2')) OR ( EMPTY(CAS_PL_S_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_S_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_S_A)>=1  AND  VAL(N_C_PL_S_A) <=999 AND ISNUMERIC(N_C_PL_S_A)) OR ( EMPTY(N_C_PL_S_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D4_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D4_S_N)>=0  AND  VAL(P_U_D4_S_N) <=100.00 AND ISNUMERIC(P_U_D4_S_N)) OR ( EMPTY(P_U_D4_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N5_S_N)>=0  AND  VAL(N_C_N5_S_N) <=99 AND ISNUMERIC(N_C_N5_S_N)) OR ( EMPTY(N_C_N5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C5_S_N)>=0  AND  VAL(N_D_C5_S_N) <=9999 AND ISNUMERIC(N_D_C5_S_N)) OR ( EMPTY(N_D_C5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P5_S_N)>=0  AND  VAL(N_D_P5_S_N) <=9999 AND ISNUMERIC(N_D_P5_S_N)) OR ( EMPTY(N_D_P5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I5_S_N)>=0.00  AND  VAL(TAS_I5_S_N) <=1000.00 AND ISNUMERIC(TAS_I5_S_N)) OR ( EMPTY(TAS_I5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D5_S_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D5_S_N)>=0  AND  VAL(P_U_D5_S_N) <=100.00 AND ISNUMERIC(P_U_D5_S_N)) OR ( EMPTY(P_U_D5_S_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N1_V_N)>=0  AND  VAL(N_C_N1_V_N) <=99 AND ISNUMERIC(N_C_N1_V_N)) OR ( EMPTY(N_C_N1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C1_V_N)>=0  AND  VAL(N_D_C1_V_N) <=9999 AND ISNUMERIC(N_D_C1_V_N)) OR ( EMPTY(N_D_C1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P1_V_N)>=0  AND  VAL(N_D_P1_V_N) <=9999 AND ISNUMERIC(N_D_P1_V_N)) OR ( EMPTY(N_D_P1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I1_V_N)>=0.00  AND  VAL(TAS_I1_V_N) <=1000.00 AND ISNUMERIC(TAS_I1_V_N)) OR ( EMPTY(TAS_I1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D1_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D1_V_N)>=0  AND  VAL(P_U_D1_V_N) <=100.00 AND ISNUMERIC(P_U_D1_V_N)) OR ( EMPTY(P_U_D1_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N2_V_N)>=0  AND  VAL(N_C_N2_V_N) <=99 AND ISNUMERIC(N_C_N2_V_N)) OR ( EMPTY(N_C_N2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C2_V_N)>=0  AND  VAL(N_D_C2_V_N) <=9999 AND ISNUMERIC(N_D_C2_V_N)) OR ( EMPTY(N_D_C2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P2_V_N)>=0  AND  VAL(N_D_P2_V_N) <=9999 AND ISNUMERIC(N_D_P2_V_N)) OR ( EMPTY(N_D_P2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I2_V_N)>=0.00  AND  VAL(TAS_I2_V_N) <=1000.00 AND ISNUMERIC(TAS_I2_V_N)) OR ( EMPTY(TAS_I2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D2_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D2_V_N)>=0  AND  VAL(P_U_D2_V_N) <=100.00 AND ISNUMERIC(P_U_D2_V_N)) OR ( EMPTY(P_U_D2_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N3_V_N)>=0  AND  VAL(N_C_N3_V_N) <=99 AND ISNUMERIC(N_C_N3_V_N)) OR ( EMPTY(N_C_N3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C3_V_N)>=0  AND  VAL(N_D_C3_V_N) <=9999 AND ISNUMERIC(N_D_C3_V_N)) OR ( EMPTY(N_D_C3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_U_A,'1','2')) OR ( EMPTY(CAS_PL_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_U_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_U_A)>=1  AND  VAL(N_C_PL_U_A) <=999 AND ISNUMERIC(N_C_PL_U_A)) OR ( EMPTY(N_C_PL_U_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P3_V_N)>=0  AND  VAL(N_D_P3_V_N) <=9999 AND ISNUMERIC(N_D_P3_V_N)) OR ( EMPTY(N_D_P3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I3_V_N)>=0.00  AND  VAL(TAS_I3_V_N) <=1000.00 AND ISNUMERIC(TAS_I3_V_N)) OR ( EMPTY(TAS_I3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D3_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D3_V_N)>=0  AND  VAL(P_U_D3_V_N) <=100.00 AND ISNUMERIC(P_U_D3_V_N)) OR ( EMPTY(P_U_D3_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N4_V_N)>=0  AND  VAL(N_C_N4_V_N) <=99 AND ISNUMERIC(N_C_N4_V_N)) OR ( EMPTY(N_C_N4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C4_V_N)>=0  AND  VAL(N_D_C4_V_N) <=9999 AND ISNUMERIC(N_D_C4_V_N)) OR ( EMPTY(N_D_C4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P4_V_N)>=0  AND  VAL(N_D_P4_V_N) <=9999 AND ISNUMERIC(N_D_P4_V_N)) OR ( EMPTY(N_D_P4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I4_V_N)>=0.00  AND  VAL(TAS_I4_V_N) <=1000.00 AND ISNUMERIC(TAS_I4_V_N)) OR ( EMPTY(TAS_I4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D4_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D4_V_N)>=0  AND  VAL(P_U_D4_V_N) <=100.00 AND ISNUMERIC(P_U_D4_V_N)) OR ( EMPTY(P_U_D4_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_N5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_N5_V_N)>=0  AND  VAL(N_C_N5_V_N) <=99 AND ISNUMERIC(N_C_N5_V_N)) OR ( EMPTY(N_C_N5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_C5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_C5_V_N)>=0  AND  VAL(N_D_C5_V_N) <=9999 AND ISNUMERIC(N_D_C5_V_N)) OR ( EMPTY(N_D_C5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_D_P5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_D_P5_V_N)>=0  AND  VAL(N_D_P5_V_N) <=9999 AND ISNUMERIC(N_D_P5_V_N)) OR ( EMPTY(N_D_P5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_I5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_I5_V_N)>=0.00  AND  VAL(TAS_I5_V_N) <=1000.00 AND ISNUMERIC(TAS_I5_V_N)) OR ( EMPTY(TAS_I5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_U_D5_V_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_U_D5_V_N)>=0  AND  VAL(P_U_D5_V_N) <=100.00 AND ISNUMERIC(P_U_D5_V_N)) OR ( EMPTY(P_U_D5_V_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_SER_UCIV_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SER_UCIV_P)>=1  AND  VAL(SER_UCIV_P) <= 99 AND ISNUMERIC(SER_UCIV_P)) OR ( EMPTY(SER_UCIV_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAM_UCIV_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CAM_UCIV_P)>=1  AND  VAL(CAM_UCIV_P) <= 99 AND ISNUMERIC(CAM_UCIV_P)) OR ( EMPTY(CAM_UCIV_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DIAS_P_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DIAS_P_P)>= 1  AND  VAL(N_DIAS_P_P) <= 9999 AND ISNUMERIC(N_DIAS_P_P)) OR ( EMPTY(N_DIAS_P_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_S_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_S_P)>=0  AND  VAL(N_C_NV_S_P) <=99 AND ISNUMERIC(N_C_NV_S_P)) OR ( EMPTY(N_C_NV_S_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_S_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_S_P)>=1  AND  VAL(N_DS_D_S_P) <=999 AND ISNUMERIC(N_DS_D_S_P)) OR ( EMPTY(N_DS_D_S_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_S_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_S_P)>=0.00  AND  VAL(TAS_IN_S_P) <=1000.00 AND ISNUMERIC(TAS_IN_S_P)) OR ( EMPTY(TAS_IN_S_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_P_USO_DI_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(P_USO_DI_P)>=1.00  AND  VAL(P_USO_DI_P) <=100.00 AND ISNUMERIC(P_USO_DI_P)) OR ( EMPTY(P_USO_DI_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_U_P)>=0  AND  VAL(N_C_NV_U_P) <=99 AND ISNUMERIC(N_C_NV_U_P)) OR ( EMPTY(N_C_NV_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_U_P)>=1  AND  VAL(N_DS_D_U_P) <=999 AND ISNUMERIC(N_DS_D_U_P)) OR ( EMPTY(N_DS_D_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_U_P)>=0.00  AND  VAL(TAS_IN_U_P) <=1000.00 AND ISNUMERIC(TAS_IN_U_P)) OR ( EMPTY(TAS_IN_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_PR_U_D_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PR_U_D_U_P)>=1.00  AND  VAL(PR_U_D_U_P) <=100.00 AND ISNUMERIC(PR_U_D_U_P)) OR ( EMPTY(PR_U_D_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_NV_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_NV_V_P)>=0  AND  VAL(N_C_NV_V_P) <=99 AND ISNUMERIC(N_C_NV_V_P)) OR ( EMPTY(N_C_NV_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_DS_D_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_DS_D_V_P)>=1  AND  VAL(N_DS_D_V_P) <=999 AND ISNUMERIC(N_DS_D_V_P)) OR ( EMPTY(N_DS_D_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_TAS_IN_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TAS_IN_V_P)>=0.00  AND  VAL(TAS_IN_V_P) <=1000.00 AND ISNUMERIC(TAS_IN_V_P)) OR ( EMPTY(TAS_IN_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_PR_U_D_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PR_U_D_V_P)>=1.00  AND  VAL(PR_U_D_V_P) <=100.00 AND ISNUMERIC(PR_U_D_V_P)) OR ( EMPTY(PR_U_D_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_S_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_S_P,'1','2')) OR ( EMPTY(CAS_PL_S_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_S_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_S_P)>=1  AND  VAL(N_C_PL_S_P) <=999 AND ISNUMERIC(N_C_PL_S_P)) OR ( EMPTY(N_C_PL_S_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_U_P,'1','2')) OR ( EMPTY(CAS_PL_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_U_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_U_P)>=1  AND  VAL(N_C_PL_U_P) <=999 AND ISNUMERIC(N_C_PL_U_P)) OR ( EMPTY(N_C_PL_U_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_CAS_PL_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAS_PL_V_P,'1','2')) OR ( EMPTY(CAS_PL_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_N_C_PL_V_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(N_C_PL_V_P)>=1  AND  VAL(N_C_PL_V_P) <=999 AND ISNUMERIC(N_C_PL_V_P)) OR ( EMPTY(N_C_PL_V_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN1_N_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN1_N_A>=1 AND ISNUMERIC(AS_MN1_N_A)) OR (AS_MN1_N_A=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN1_M_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN1_M_N>=0  AND AS_MN1_M_N <=999 AND ISNUMERIC(AS_MN1_M_N)) OR (AS_MN1_M_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN2_M_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN2_M_N>=0  AND AS_MN2_M_N <=999 AND ISNUMERIC(AS_MN2_M_N)) OR (AS_MN2_M_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN3_M_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN3_M_N>=0  AND AS_MN3_M_N <=999 AND ISNUMERIC(AS_MN3_M_N)) OR (AS_MN3_M_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN4_N_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN4_N_N>=0  AND AS_MN4_N_N <=999 AND ISNUMERIC(AS_MN4_N_N)) OR (AS_MN4_N_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN5_N_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN5_N_N>=0  AND AS_MN5_N_N <=999 AND ISNUMERIC(AS_MN5_N_N)) OR (AS_MN5_N_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN1_O_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN1_O_N>=0  AND AS_MN1_O_N <=999 AND ISNUMERIC(AS_MN1_O_N)) OR (AS_MN1_O_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN2_P_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN2_P_N>=0  AND AS_MN2_P_N <=999 AND ISNUMERIC(AS_MN2_P_N)) OR (AS_MN2_P_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN3_P_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN3_P_N>=0  AND AS_MN3_P_N <=999 AND ISNUMERIC(AS_MN3_P_N)) OR (AS_MN3_P_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN4_Q_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN4_Q_N>=0  AND AS_MN4_Q_N <=999 AND ISNUMERIC(AS_MN4_Q_N)) OR (AS_MN4_Q_N=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_80_AS_MN5_R_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((AS_MN5_R_N>=0  AND AS_MN5_R_N <=999 AND ISNUMERIC(AS_MN5_R_N)) OR (AS_MN5_R_N=0))
	ENDIF
ENDFUNC


