FUNCTION FieldRuleFor_eventos_61_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_T_EN_RESID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(T_EN_RESID,'1','2','3')) AND ( .NOT. EMPTY(T_EN_RESID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_TRIQ_PREVI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRIQ_PREVI,'1','2')) AND ( .NOT. EMPTY(TRIQ_PREVI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_OJO_CIRUGI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OJO_CIRUGI,'1','2','3')) OR ( EMPTY(OJO_CIRUGI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PAR_OJODER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PAR_OJODER,'1','2','3')) OR ( EMPTY(PAR_OJODER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PAR_OJOIZQ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PAR_OJOIZQ,'1','2','3')) OR ( EMPTY(PAR_OJOIZQ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_CIC_MUCOSA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIC_MUCOSA,'1','2')) AND ( .NOT. EMPTY(CIC_MUCOSA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_CIC_MUC_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIC_MUC_OJ,'1','2','3')) OR ( EMPTY(CIC_MUC_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_DEP_PARSUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEP_PARSUP,'1','2')) AND ( .NOT. EMPTY(DEP_PARSUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_DEP_PS_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEP_PS_OJ,'1','2','3')) OR ( EMPTY(DEP_PS_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_PS_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_PS_OD,'0','1','2','3','4')) OR ( EMPTY(PEST_PS_OD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_PS_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_PS_OI,'0','1','2','3','4')) OR ( EMPTY(PEST_PS_OI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_DEP_PARINF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEP_PARINF,'1','2')) AND ( .NOT. EMPTY(DEP_PARINF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_DEP_PI_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEP_PI_OJ,'1','2','3')) OR ( EMPTY(DEP_PI_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_PI_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_PI_OD,'0','1','2','3','4')) OR ( EMPTY(PEST_PI_OD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_PI_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_PI_OI,'0','1','2','3','4')) OR ( EMPTY(PEST_PI_OI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_GO_PS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_GO_PS,'1','2')) AND ( .NOT. EMPTY(PEST_GO_PS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PS_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PS_OJ,'1','2','3')) OR ( EMPTY(PEGO_PS_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PS_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PS_OD,'1','2','3','4')) OR ( EMPTY(PEGO_PS_OD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PS_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PS_OI,'1','2','3','4')) OR ( EMPTY(PEGO_PS_OI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEST_GO_PI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEST_GO_PI,'1','2')) AND ( .NOT. EMPTY(PEST_GO_PI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PI_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PI_OJ,'1','2','3')) OR ( EMPTY(PEGO_PI_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PI_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PI_OD,'1','2','3','4')) OR ( EMPTY(PEGO_PI_OD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PEGO_PI_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEGO_PI_OI,'1','2','3','4')) OR ( EMPTY(PEGO_PI_OI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PESTCORNEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PESTCORNEA,'1','2')) AND ( .NOT. EMPTY(PESTCORNEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PES_COR_OJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PES_COR_OJ,'1','2','3')) OR ( EMPTY(PES_COR_OJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PES_COR_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PES_COR_OD,'1','2','3','4')) OR ( EMPTY(PES_COR_OD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PES_COR_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PES_COR_OI,'1','2','3','4')) OR ( EMPTY(PES_COR_OI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_OPC_CORNEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OPC_CORNEA,'1','2','3','4')) AND ( .NOT. EMPTY(OPC_CORNEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_ENG_PARPAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENG_PARPAD,'1','2','3','4')) AND ( .NOT. EMPTY(ENG_PARPAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_PES_MALPOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PES_MALPOS,'1','2','3','4')) AND ( .NOT. EMPTY(PES_MALPOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_CUERPO_EXT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CUERPO_EXT,'1','2','3','4')) AND ( .NOT. EMPTY(CUERPO_EXT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_FOTOFOBIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FOTOFOBIA,'1','2','3','4')) AND ( .NOT. EMPTY(FOTOFOBIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_AGUDEZA_OD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AGUDEZA_OD))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_AGUDEZA_OI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AGUDEZA_OI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_61_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


