FUNCTION FieldRuleFor_eventos_27_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_CLAS_CASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_CASO,'1','2')) AND ( .NOT. EMPTY(CLAS_CASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_FIEBRE_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE_AG,'1','2')) OR ( EMPTY(FIEBRE_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_DISNEA_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISNEA_AG,'1','2')) OR ( EMPTY(DISNEA_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_EDE_FAC_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDE_FAC_AG,'1','2')) OR ( EMPTY(EDE_FAC_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ED_MI_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ED_MI_AG,'1','2')) OR ( EMPTY(ED_MI_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_DER_PERI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DER_PERI,'1','2')) OR ( EMPTY(DER_PERI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_HEP_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEP_AG,'1','2')) OR ( EMPTY(HEP_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ADENO_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADENO_AG,'1','2')) OR ( EMPTY(ADENO_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ROMAÑA_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ROMAÑA_AG,'1','2')) OR ( EMPTY(ROMAÑA_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_CHAGOMA_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CHAGOMA_AG,'1','2')) OR ( EMPTY(CHAGOMA_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_F_CARD_CR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(F_CARD_CR,'1','2')) AND ( .NOT. EMPTY(F_CARD_CR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_TORAC_CR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TORAC_CR,'1','2')) AND ( .NOT. EMPTY(TORAC_CR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_BRADI_CR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BRADI_CR,'1','2')) AND ( .NOT. EMPTY(BRADI_CR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_DISFAG_CR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISFAG_CR,'1','2')) AND ( .NOT. EMPTY(DISFAG_CR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ARRITMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARRITMIA,'1','2')) AND ( .NOT. EMPTY(ARRITMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_GOTA_GRUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GOTA_GRUE,'1','2','3')) OR ( EMPTY(GOTA_GRUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_MICRO_HEM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICRO_HEM,'1','2','3')) OR ( EMPTY(MICRO_HEM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_STROUT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(STROUT,'1','2','3')) OR ( EMPTY(STROUT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ELISA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ELISA,'1','2','3')) OR ( EMPTY(ELISA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_INMUNOFLUO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INMUNOFLUO,'1','2','3')) OR ( EMPTY(INMUNOFLUO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_PROB_VIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROB_VIA,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(PROB_VIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_INMONOBLOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INMONOBLOT,'1','2','3')) OR ( EMPTY(INMONOBLOT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_REACTIVACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REACTIVACI,'1','2')) OR ( EMPTY(REACTIVACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_ELISA_NOCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ELISA_NOCO,'1','2','3')) OR ( EMPTY(ELISA_NOCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_27_MICROMETOD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICROMETOD,'1','2','3')) OR ( EMPTY(MICROMETOD)))
	ENDIF
ENDFUNC


