FUNCTION FieldRuleFor_eventos_52_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_P_NOMBRE_M
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(P_NOMBRE_M))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_P_APELL_M
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(P_APELL_M))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_TIDE_MAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIDE_MAD,'RC','TI','CC','CE','PA','MS','AS','PE')) AND ( .NOT. EMPTY(TIDE_MAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_NUMID_MAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUMID_MAD))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_N_EDUCAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(N_EDUCAT,'1','2','3','4','5')) OR ( EMPTY(N_EDUCAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_ESTRATO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTRATO,'1','2','3','4','5','6')) OR ( EMPTY(ESTRATO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_MENORES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((MENORES>=0  AND MENORES <= 20 AND ISNUMERIC(MENORES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_SITIO_DEF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SITIO_DEF,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(SITIO_DEF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_PESO_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_NAC)>=900  AND  VAL(PESO_NAC) <=5000 AND ISNUMERIC(PESO_NAC)) OR ( EMPTY(PESO_NAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_TALLA_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TALLA_NAC)>= 30.0  AND  VAL(TALLA_NAC) <= 55.0 AND ISNUMERIC(TALLA_NAC)) OR ( EMPTY(TALLA_NAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_EDAD_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_GES)>= 0  AND  VAL(EDAD_GES) <= 45 AND ISNUMERIC(EDAD_GES)) OR ( EMPTY(EDAD_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_CREC_DLLO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CREC_DLLO,'1','2')) AND ( .NOT. EMPTY(CREC_DLLO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=1  AND PESO_ACT <= 30 AND ISNUMERIC(PESO_ACT)) OR (PESO_ACT=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_TALLA_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_ACT>=45.0  AND TALLA_ACT <= 120.0 AND ISNUMERIC(TALLA_ACT)) OR (TALLA_ACT=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_ESQ_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESQ_VAC,'1','2','3')) AND ( .NOT. EMPTY(ESQ_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_CARNE_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARNE_VAC,'1','2')) OR ( EMPTY(CARNE_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_CLAS_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_PESO,'5','6','7')) AND ( .NOT. EMPTY(CLAS_PESO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_CLAS_TALLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_TALLA,'1','4','3')) AND ( .NOT. EMPTY(CLAS_TALLA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_C_PES_TAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(C_PES_TAL))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) AND ( .NOT. EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DELGADEZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DELGADEZ,'1','2')) AND ( .NOT. EMPTY(DELGADEZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_PIEL_RESE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PIEL_RESE,'1','2')) AND ( .NOT. EMPTY(PIEL_RESE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_HIPERPIGM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPERPIGM,'1','2')) AND ( .NOT. EMPTY(HIPERPIGM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_LES_CABEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LES_CABEL,'1','2')) AND ( .NOT. EMPTY(LES_CABEL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_PALIDEZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PALIDEZ,'1','2')) AND ( .NOT. EMPTY(PALIDEZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_C_DIRECT_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(C_DIRECT_A))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_C_DETERM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(C_DETERM,'1','2','3')) AND ( .NOT. EMPTY(C_DETERM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DES_CBMTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DES_CBMTE,'1','2')) OR ( EMPTY(DES_CBMTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DES_CPAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DES_CPAT,'1','2')) OR ( EMPTY(DES_CPAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DEMORA_1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEMORA_1,'1','2')) OR ( EMPTY(DEMORA_1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DEMORA_2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEMORA_2,'1','2')) OR ( EMPTY(DEMORA_2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DEMORA_3
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEMORA_3,'1','2')) OR ( EMPTY(DEMORA_3)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_DEMORA_4
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEMORA_4,'1','2')) OR ( EMPTY(DEMORA_4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_52_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


