FUNCTION FieldRuleFor_eventos_21_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_VAC_EI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_EI,'1','2','3')) OR ( EMPTY(VAC_EI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_ASOC_BROTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASOC_BROTE,'1','2')) OR ( EMPTY(ASOC_BROTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_VIAJÓ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIAJÓ,'1','2')) OR ( EMPTY(VIAJÓ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_CON_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_CON,'1','2')) OR ( EMPTY(CON_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_CON_EST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_EST,'1','2')) OR ( EMPTY(CON_EST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_ASMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASMA,'1','2')) AND ( .NOT. EMPTY(ASMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_EPOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPOC,'1','2')) AND ( .NOT. EMPTY(EPOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) AND ( .NOT. EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIH,'1','2')) AND ( .NOT. EMPTY(VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_ENF_CARD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENF_CARD,'1','2')) AND ( .NOT. EMPTY(ENF_CARD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_CANCER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CANCER,'1','2')) AND ( .NOT. EMPTY(CANCER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_MALNUTRI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALNUTRI,'1','2')) AND ( .NOT. EMPTY(MALNUTRI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_OBESIDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OBESIDAD,'1','2')) AND ( .NOT. EMPTY(OBESIDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_INS_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INS_RENAL,'1','2')) AND ( .NOT. EMPTY(INS_RENAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_OTR_MEDINM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_MEDINM,'1','2')) AND ( .NOT. EMPTY(OTR_MEDINM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_FUMADOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUMADOR,'1','2')) AND ( .NOT. EMPTY(FUMADOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_OTROS_DC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_DC,'1','2')) AND ( .NOT. EMPTY(OTROS_DC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_TOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOS,'1','2')) AND ( .NOT. EMPTY(TOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_RINORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RINORREA,'1','2')) OR ( EMPTY(RINORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_CONJUNTIVI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONJUNTIVI,'1','2')) OR ( EMPTY(CONJUNTIVI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) OR ( EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DIF_RES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIF_RES,'1','2')) OR ( EMPTY(DIF_RES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) OR ( EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_HALLAZ_RAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HALLAZ_RAD,'1','2','3','4')) OR ( EMPTY(HALLAZ_RAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_USO_ANTIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USO_ANTIB,'1','2')) OR ( EMPTY(USO_ANTIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_USO_ANTIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USO_ANTIV,'1','2')) OR ( EMPTY(USO_ANTIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_SERV_HOSP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SERV_HOSP,'1','3')) OR ( EMPTY(SERV_HOSP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DER_PLE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DER_PLE,'1','2')) AND ( .NOT. EMPTY(DER_PLE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DER_PER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DER_PER,'1','2')) AND ( .NOT. EMPTY(DER_PER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_MIOCARDITI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIOCARDITI,'1','2')) AND ( .NOT. EMPTY(MIOCARDITI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_SEPTICEMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEPTICEMIA,'1','2')) AND ( .NOT. EMPTY(SEPTICEMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_FALLA_RESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_RESP,'1','2')) AND ( .NOT. EMPTY(FALLA_RESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS,'1','2')) AND ( .NOT. EMPTY(OTROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_TRAB_SALUD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAB_SALUD,'1','2')) OR ( EMPTY(TRAB_SALUD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_DETER_CLIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DETER_CLIN,'1','2')) OR ( EMPTY(DETER_CLIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_TROMBOCITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TROMBOCITO,'1','2')) OR ( EMPTY(TROMBOCITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_PLAQUETAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PLAQUETAS>=0  AND PLAQUETAS <=800000 AND ISNUMERIC(PLAQUETAS)) OR (PLAQUETAS=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_TUBERCULOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TUBERCULOS,'1','2')) OR ( EMPTY(TUBERCULOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_ODINOFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ODINOFAGIA,'1','2')) OR ( EMPTY(ODINOFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_ADINAMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADINAMIA,'1','2')) OR ( EMPTY(ADINAMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_HIPERTENSI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPERTENSI,'1','2')) OR ( EMPTY(HIPERTENSI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_PERD_GUSTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PERD_GUSTO,'1','2')) OR ( EMPTY(PERD_GUSTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_21_OTROS_SINT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_SINT,'1','2')) OR ( EMPTY(OTROS_SINT)))
	ENDIF
ENDFUNC


