FUNCTION FieldRuleFor_eventos_57_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_VAC_HEP_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_HEP_A,'1','2','3')) AND ( .NOT. EMPTY(VAC_HEP_A)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_NUM_DOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NUM_DOSIS)>=1  AND  VAL(NUM_DOSIS) <=3 AND ISNUMERIC(NUM_DOSIS)) OR ( EMPTY(NUM_DOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_FUENTE_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUENTE_VAC,'1','2','3')) AND ( .NOT. EMPTY(FUENTE_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_MALESTAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALESTAR,'1','2')) AND ( .NOT. EMPTY(MALESTAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ASTENIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASTENIA,'1','2')) AND ( .NOT. EMPTY(ASTENIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ADINAMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADINAMIA,'1','2')) AND ( .NOT. EMPTY(ADINAMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_HEPATOMEGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOMEGA,'1','2')) AND ( .NOT. EMPTY(HEPATOMEGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIALGIAS,'1','2')) AND ( .NOT. EMPTY(MIALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ICTERICIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICTERICIA,'1','2')) AND ( .NOT. EMPTY(ICTERICIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_DABDOMINAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DABDOMINAL,'1','2')) AND ( .NOT. EMPTY(DABDOMINAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_PRURITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRURITO,'1','2')) AND ( .NOT. EMPTY(PRURITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COLURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COLURIA,'1','2')) AND ( .NOT. EMPTY(COLURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ERUPCION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ERUPCION,'1','2')) AND ( .NOT. EMPTY(ERUPCION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ACOLIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACOLIA,'1','2')) AND ( .NOT. EMPTY(ACOLIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COMPLICACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMPLICACI,'1','2')) AND ( .NOT. EMPTY(COMPLICACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ICT_PROLON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ICT_PROLON,'1','2')) OR ( EMPTY(ICT_PROLON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_HEP_COLEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEP_COLEST,'1','2')) OR ( EMPTY(HEP_COLEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_HEP_RECIDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEP_RECIDI,'1','2')) OR ( EMPTY(HEP_RECIDI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_FALLA_HEPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_HEPA,'1','2')) OR ( EMPTY(FALLA_HEPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_COM_NEUROL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM_NEUROL,'1','2')) OR ( EMPTY(COM_NEUROL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_SEPSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEPSIS,'1','2')) OR ( EMPTY(SEPSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_VIAJO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIAJO,'1','2')) AND ( .NOT. EMPTY(VIAJO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ANTEC_CONT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANTEC_CONT,'1','2')) AND ( .NOT. EMPTY(ANTEC_CONT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_LUGAR_ASOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LUGAR_ASOC,'1','2','3','4','5')) OR ( EMPTY(LUGAR_ASOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ASOC_BROTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASOC_BROTE,'1','2')) OR ( EMPTY(ASOC_BROTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_ORIG_HIDRI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ORIG_HIDRI,'1','2')) OR ( EMPTY(ORIG_HIDRI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_FUEN_PROGA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUEN_PROGA,'1','2')) OR ( EMPTY(FUEN_PROGA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_MON_RAP_VA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MON_RAP_VA,'1','2')) OR ( EMPTY(MON_RAP_VA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_VAC_BLOQUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_BLOQUE,'1','2')) OR ( EMPTY(VAC_BLOQUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_SEG_CONTAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEG_CONTAC,'1','2')) OR ( EMPTY(SEG_CONTAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_57_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


