FUNCTION FieldRuleFor_eventos_41_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NOM_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_MADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS')) AND ( .NOT. EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NUM_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NO_EMBARAZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_EMBARAZ>=0 AND ISNUMERIC(NO_EMBARAZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_TOM_SER_SI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOM_SER_SI,'1','2','3')) AND ( .NOT. EMPTY(TOM_SER_SI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_RES_SEROLO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_SEROLO,'1','2')) OR ( EMPTY(RES_SEROLO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_TOMA_IGM_T
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOMA_IGM_T,'1','2')) AND ( .NOT. EMPTY(TOMA_IGM_T)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_RES_IGM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_IGM,'1','2')) OR ( EMPTY(RES_IGM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_VAC_ANTIRU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_ANTIRU,'1','2','3')) AND ( .NOT. EMPTY(VAC_ANTIRU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_SIN_RUBEOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIN_RUBEOL,'1','2')) AND ( .NOT. EMPTY(SIN_RUBEOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OE_BILOGIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OE_BILOGIC,'1','2')) AND ( .NOT. EMPTY(OE_BILOGIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OE_MEDIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OE_MEDIC,'1','2')) AND ( .NOT. EMPTY(OE_MEDIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OE_AMB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OE_AMB,'1','2')) AND ( .NOT. EMPTY(OE_AMB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OE_OTRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OE_OTRA,'1','2')) AND ( .NOT. EMPTY(OE_OTRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OE_NINGUNA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OE_NINGUNA,'1','2')) AND ( .NOT. EMPTY(OE_NINGUNA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_GEMELO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GEMELO,'1','2')) AND ( .NOT. EMPTY(GEMELO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NATIVIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NATIVIVO,'1','2')) AND ( .NOT. EMPTY(NATIVIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_NATIMORTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NATIMORTO,'1','2')) AND ( .NOT. EMPTY(NATIMORTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_SEM_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((SEM_GES>=22  AND SEM_GES <=45 AND ISNUMERIC(SEM_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_EDAD_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_GES>=22  AND EDAD_GES <=45 AND ISNUMERIC(EDAD_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_STORCH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(STORCH,'1','2')) OR ( EMPTY(STORCH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ANENCEFALI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANENCEFALI,'1','2')) AND ( .NOT. EMPTY(ANENCEFALI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ANO_IMPERF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANO_IMPERF,'1','2')) AND ( .NOT. EMPTY(ANO_IMPERF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ANOM_OCU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANOM_OCU,'1','2')) AND ( .NOT. EMPTY(ANOM_OCU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ANOTIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANOTIA,'1','2')) AND ( .NOT. EMPTY(ANOTIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ATRESIA_ES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ATRESIA_ES,'1','2')) AND ( .NOT. EMPTY(ATRESIA_ES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ATRESIA_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ATRESIA_IN,'1','2')) AND ( .NOT. EMPTY(ATRESIA_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_CARDIOPATI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARDIOPATI,'1','2')) AND ( .NOT. EMPTY(CARDIOPATI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_CATARATA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CATARATA,'1','2')) AND ( .NOT. EMPTY(CATARATA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_CEFALOCELE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALOCELE,'1','2')) AND ( .NOT. EMPTY(CEFALOCELE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_CRIPTORQUI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRIPTORQUI,'1','2')) AND ( .NOT. EMPTY(CRIPTORQUI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_DEFE_PARED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEFE_PARED,'1','2')) AND ( .NOT. EMPTY(DEFE_PARED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_DISP_ESQUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISP_ESQUE,'1','2')) AND ( .NOT. EMPTY(DISP_ESQUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ESPINA_BIF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESPINA_BIF,'1','2')) AND ( .NOT. EMPTY(ESPINA_BIF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_FISURA_ORA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FISURA_ORA,'1','2')) AND ( .NOT. EMPTY(FISURA_ORA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_GEMELOS_AC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GEMELOS_AC,'1','2')) AND ( .NOT. EMPTY(GEMELOS_AC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_GENITALES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GENITALES,'1','2')) AND ( .NOT. EMPTY(GENITALES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_HEMANGIOM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMANGIOM,'1','2')) AND ( .NOT. EMPTY(HEMANGIOM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_HEPATOESPL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATOESPL,'1','2')) AND ( .NOT. EMPTY(HEPATOESPL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_HIDROCEFAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIDROCEFAL,'1','2')) AND ( .NOT. EMPTY(HIDROCEFAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_HIPOACUSIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOACUSIA,'1','2')) AND ( .NOT. EMPTY(HIPOACUSIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_HIPOSPADIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOSPADIA,'1','2')) AND ( .NOT. EMPTY(HIPOSPADIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_MICROCEFAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICROCEFAL,'1','2')) AND ( .NOT. EMPTY(MICROCEFAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_POLIDACTI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(POLIDACTI,'1','2')) AND ( .NOT. EMPTY(POLIDACTI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_POLIMALFOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(POLIMALFOR,'1','2')) AND ( .NOT. EMPTY(POLIMALFOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_PURPURA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PURPURA,'1','2')) AND ( .NOT. EMPTY(PURPURA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_RED_MIEMBR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RED_MIEMBR,'1','2')) AND ( .NOT. EMPTY(RED_MIEMBR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_SINDACTIL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SINDACTIL,'1','2')) AND ( .NOT. EMPTY(SINDACTIL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_DOWN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOWN,'1','2')) AND ( .NOT. EMPTY(DOWN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_TALIPES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TALIPES,'1','2')) AND ( .NOT. EMPTY(TALIPES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_BAJO_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BAJO_PESO,'1','2')) AND ( .NOT. EMPTY(BAJO_PESO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_ANOM_FUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANOM_FUN,'1','2')) AND ( .NOT. EMPTY(ANOM_FUN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_INFEC_CONG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INFEC_CONG,'1','2')) AND ( .NOT. EMPTY(INFEC_CONG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_OTRAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRAS,'1','2')) AND ( .NOT. EMPTY(OTRAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_41_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


