FUNCTION FieldRuleFor_eventos_23_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COD_MUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_MUN)) OR INLIST(COD_EVE,'855','339','344','207','745','896','467')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_FEC_INV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INV))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_DSS_NINGUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DSS_NINGUN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NAUSEAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NAUSEAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_VÓMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(VÓMITO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIARREA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FIEBRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_DOLOR_ABDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DOLOR_ABDO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CEFALEA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_DESHIDRATA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DESHIDRATA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CIANOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CIANOSIS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MIALGIAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ARTRALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ARTRALGIAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MAREO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MAREO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ESTREÑIMIE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ESTREÑIMIE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ESCALOFRÍO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ESCALOFRÍO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_PARESTESIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PARESTESIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ICTERICIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ICTERICIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ACOLIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ACOLIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COLURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COLURIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_LESIONESMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(LESIONESMA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ANOREXIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ANOREXIA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MALESTAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MALESTAR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_BRADICARDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(BRADICARDI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_SIALORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SIALORREA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MIOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MIOSIS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(OTROS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_PER_IN_COR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PER_IN_COR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_PER_IN_LAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PER_IN_LAR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MUE_BIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_BIO,'2','3','4','5','6','7','8')) AND ( .NOT. EMPTY(MUE_BIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MUE_ALI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_ALI,'1','2')) AND ( .NOT. EMPTY(MUE_ALI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MUE_SUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_SUP,'1','2')) AND ( .NOT. EMPTY(MUE_SUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_EST_MAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_MAN,'2','3','4','5','6','7')) AND ( .NOT. EMPTY(EST_MAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_LUG_CON_IM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(LUG_CON_IM))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_LUG_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LUG_CON,'1','2','3','4','5','6','7','8','9')) AND ( .NOT. EMPTY(LUG_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CAD_FRIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAD_FRIO,'1','2')) AND ( .NOT. EMPTY(CAD_FRIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CONSERVACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONSERVACI,'1','2')) AND ( .NOT. EMPTY(CONSERVACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ALMACENADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALMACENADO,'1','2')) AND ( .NOT. EMPTY(ALMACENADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_COCION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COCION,'1','2')) AND ( .NOT. EMPTY(COCION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_HIG_PER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIG_PER,'1','2')) AND ( .NOT. EMPTY(HIG_PER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CON_CRU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_CRU,'1','2')) AND ( .NOT. EMPTY(CON_CRU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_LIM_UTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LIM_UTE,'1','2')) AND ( .NOT. EMPTY(LIM_UTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_AMBIENTAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AMBIENTAL,'1','2')) AND ( .NOT. EMPTY(AMBIENTAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_FTE_ALI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTE_ALI,'1','2')) AND ( .NOT. EMPTY(FTE_ALI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_UTE_TOX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UTE_TOX,'1','2')) AND ( .NOT. EMPTY(UTE_TOX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ADI_TOX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADI_TOX,'1','2')) AND ( .NOT. EMPTY(ADI_TOX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_AGUA_NO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGUA_NO,'1','2')) AND ( .NOT. EMPTY(AGUA_NO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_TOX_TEJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOX_TEJ,'1','2')) AND ( .NOT. EMPTY(TOX_TEJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ING_EXE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ING_EXE,'1','2')) AND ( .NOT. EMPTY(ING_EXE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MAN_INF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MAN_INF,'1','2')) AND ( .NOT. EMPTY(MAN_INF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ACIDIFICAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACIDIFICAC,'1','2')) AND ( .NOT. EMPTY(ACIDIFICAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_ENFRIADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENFRIADO,'1','2')) AND ( .NOT. EMPTY(ENFRIADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_FAC_DET_EX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FAC_DET_EX,'1','2')) AND ( .NOT. EMPTY(FAC_DET_EX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_FAC_DET_AB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FAC_DET_AB,'1','2')) AND ( .NOT. EMPTY(FAC_DET_AB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NINGUNA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NINGUNA,'1','2')) AND ( .NOT. EMPTY(NINGUNA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CLAUSURA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAUSURA,'1','2')) AND ( .NOT. EMPTY(CLAUSURA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_SUSPENSION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUSPENSION,'1','2')) AND ( .NOT. EMPTY(SUSPENSION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CONGELACIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONGELACIO,'1','2')) AND ( .NOT. EMPTY(CONGELACIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_DECOMISO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DECOMISO,'1','2')) AND ( .NOT. EMPTY(DECOMISO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_AISLAMENTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AISLAMENTO,'1','2')) AND ( .NOT. EMPTY(AISLAMENTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_VACUNACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VACUNACION,'1','2')) AND ( .NOT. EMPTY(VACUNACION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CTRL_INS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CTRL_INS,'1','2')) AND ( .NOT. EMPTY(CTRL_INS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MEDIDA_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MEDIDA_PRE,'1','2')) AND ( .NOT. EMPTY(MEDIDA_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_CLA_ETA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_ETA,'1','2')) AND ( .NOT. EMPTY(CLA_ETA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_MUE_BIO2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_BIO2,'2','3','4','5','6','7','8')) AND ( .NOT. EMPTY(MUE_BIO2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NUM_MU_EM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MU_EM1>=1 AND ISNUMERIC(NUM_MU_EM1)) OR (NUM_MU_EM1=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_EST_MAN_2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_MAN_2,'2','3','4','5','6','7')) AND ( .NOT. EMPTY(EST_MAN_2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NUM_MU_EM2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MU_EM2>=1 AND ISNUMERIC(NUM_MU_EM2)) OR (NUM_MU_EM2=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NUM_MU_BI1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MU_BI1>=1 AND ISNUMERIC(NUM_MU_BI1)) OR (NUM_MU_BI1=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_23_NUM_MU_BI2
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_MU_BI2>=1 AND ISNUMERIC(NUM_MU_BI2)) OR (NUM_MU_BI2=0))
	ENDIF
ENDFUNC


