FUNCTION FieldRuleFor_eventos_30_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'CC','CE','PA','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_FEC_INV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INV))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ENT_REA_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENT_REA_IN,'1','2','3')) AND ( .NOT. EMPTY(ENT_REA_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_MUE_DETX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUE_DETX,'1','2','3')) AND ( .NOT. EMPTY(MUE_DETX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_SITIO_MUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SITIO_MUE,'1','2','3','4','5')) AND ( .NOT. EMPTY(SITIO_MUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_NOMBRE_ENT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOMBRE_ENT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_TIP_DOC_EN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_DOC_EN,'CC','CE','PA','AS')) AND ( .NOT. EMPTY(TIP_DOC_EN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_NUM_IDE_EN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_EN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_PARENTESCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARENTESCO,'1','2','3','4','5')) AND ( .NOT. EMPTY(PARENTESCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ESCOLA_MAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCOLA_MAD,'1','2','3','4','5')) AND ( .NOT. EMPTY(ESCOLA_MAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ESTRATO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTRATO,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(ESTRATO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ESTADO_CIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADO_CIV,'1','2','3','4','5')) AND ( .NOT. EMPTY(ESTADO_CIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_OCUPACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(OCUPACION)) OR INLIST(COD_EVE,'357','351','352')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_PESO_NACER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_NACER)>=100  AND  VAL(PESO_NACER) <=6000 AND ISNUMERIC(PESO_NACER)) OR ( EMPTY(PESO_NACER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ANT_DES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANT_DES,'1','2','3')) OR ( EMPTY(ANT_DES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ESQ_VACUNA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESQ_VACUNA,'1','2','3')) OR ( EMPTY(ESQ_VACUNA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_HACINAMIEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HACINAMIEN,'1','2')) AND ( .NOT. EMPTY(HACINAMIEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_POCA_VENTI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(POCA_VENTI,'1','2')) AND ( .NOT. EMPTY(POCA_VENTI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_HUMEDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HUMEDAD,'1','2')) AND ( .NOT. EMPTY(HUMEDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ACUEDUCTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACUEDUCTO,'1','2')) AND ( .NOT. EMPTY(ACUEDUCTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ALCANTARIL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALCANTARIL,'1','2')) AND ( .NOT. EMPTY(ALCANTARIL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_GAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GAS,'1','2')) AND ( .NOT. EMPTY(GAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ELECTRICID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ELECTRICID,'1','2')) AND ( .NOT. EMPTY(ELECTRICID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_SE_FUMA_VI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SE_FUMA_VI,'1','2')) AND ( .NOT. EMPTY(SE_FUMA_VI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_COCINA_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COCINA_CON,'1','2','3','4')) AND ( .NOT. EMPTY(COCINA_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_FTES_CONTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FTES_CONTA,'1','2')) AND ( .NOT. EMPTY(FTES_CONTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_TRAFICO_VE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAFICO_VE,'1','2')) AND ( .NOT. EMPTY(TRAFICO_VE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_SIGNOS_ALA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIGNOS_ALA,'1','2','3')) OR ( EMPTY(SIGNOS_ALA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_AYUDA_MÉD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AYUDA_MÉD,'1','2','3')) OR ( EMPTY(AYUDA_MÉD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_FACIL_TRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FACIL_TRAN,'1','2','3')) AND ( .NOT. EMPTY(FACIL_TRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_DIF_ADMITI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIF_ADMITI,'1','2','3')) AND ( .NOT. EMPTY(DIF_ADMITI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_CUAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CUAL,'1','2','3')) OR ( EMPTY(CUAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_ATE_OPORTU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ATE_OPORTU,'1','2','3')) AND ( .NOT. EMPTY(ATE_OPORTU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_CAL_ATENCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAL_ATENCI,'1','2','3','4')) OR ( EMPTY(CAL_ATENCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_30_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


