FUNCTION FieldRuleFor_eventos_22_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_NAUSEAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NAUSEAS,'1','2')) AND ( .NOT. EMPTY(NAUSEAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_CALAMBRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CALAMBRES,'1','2')) AND ( .NOT. EMPTY(CALAMBRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_DESHIDRATA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESHIDRATA,'1','2')) AND ( .NOT. EMPTY(DESHIDRATA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_CIANOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIANOSIS,'1','2')) AND ( .NOT. EMPTY(CIANOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MIALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIALGIAS,'1','2')) AND ( .NOT. EMPTY(MIALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ARTRALGIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIAS,'1','2')) AND ( .NOT. EMPTY(ARTRALGIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MAREO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MAREO,'1','2')) AND ( .NOT. EMPTY(MAREO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_LMACULOPAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LMACULOPAL,'1','2')) AND ( .NOT. EMPTY(LMACULOPAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ESCALOFRIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCALOFRIO,'1','2')) AND ( .NOT. EMPTY(ESCALOFRIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_PARESTESIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARESTESIA,'1','2')) AND ( .NOT. EMPTY(PARESTESIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_SIALORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIALORREA,'1','2')) AND ( .NOT. EMPTY(SIALORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MIOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIOSIS,'1','2')) AND ( .NOT. EMPTY(MIOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS,'1','2')) AND ( .NOT. EMPTY(OTROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_HORA_INI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(HORA_INI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ALI_IN_NA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ALI_IN_NA1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ALI_IN_HM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ALI_IN_HM1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ALI_IN_LC1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ALI_IN_LC1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_ANT_NA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_ANT_NA1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_ANT_HM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_ANT_HM1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_ANT_LC1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_ANT_LC1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_AN2_NA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_AN2_NA1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_AN2_HM1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_AN2_HM1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AI_AN2_LC1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AI_AN2_LC1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_NOM_LUG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_LUG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_DIR_LUG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIR_LUG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_ASO_BRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASO_BRO,'1','2')) AND ( .NOT. EMPTY(ASO_BRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_CAPTADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAPTADO,'1','2')) AND ( .NOT. EMPTY(CAPTADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_RELACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RELACION,'1','2')) AND ( .NOT. EMPTY(RELACION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MTRA_BIOLO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MTRA_BIOLO,'1','2')) AND ( .NOT. EMPTY(MTRA_BIOLO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MTRA_HECES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MTRA_HECES,'1','2')) OR ( EMPTY(MTRA_HECES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MTRA_VOMIT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MTRA_VOMIT,'1','2')) OR ( EMPTY(MTRA_VOMIT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MTRA_SANGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MTRA_SANGR,'1','2')) OR ( EMPTY(MTRA_SANGR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_MTRA_OTRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MTRA_OTRA,'1','2')) OR ( EMPTY(MTRA_OTRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_22_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


