FUNCTION FieldRuleFor_eventos_24_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_CLA_INI_CA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_INI_CA,'1','2')) OR ( EMPTY(CLA_INI_CA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_ESP_ANI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESP_ANI,'1','2','3','4','5','6','7')) AND ( .NOT. EMPTY(ESP_ANI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_UNI_MED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UNI_MED,'1','2')) OR ( EMPTY(UNI_MED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_ANT_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANT_VAC,'1','2','3')) OR ( EMPTY(ANT_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_AREA_PRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AREA_PRO,'1','2','3')) OR ( EMPTY(AREA_PRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_AGRESIVIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGRESIVIDA,'1','2')) AND ( .NOT. EMPTY(AGRESIVIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_PARALISIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARALISIS,'1','2')) AND ( .NOT. EMPTY(PARALISIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_SALIVACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SALIVACION,'1','2')) AND ( .NOT. EMPTY(SALIVACION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_APETITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(APETITO,'1','2')) AND ( .NOT. EMPTY(APETITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_VORACIDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VORACIDAD,'1','2')) AND ( .NOT. EMPTY(VORACIDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_DEGLUCION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEGLUCION,'1','2')) AND ( .NOT. EMPTY(DEGLUCION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_LADRIDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LADRIDO,'1','2')) AND ( .NOT. EMPTY(LADRIDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_MANDIBULA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MANDIBULA,'1','2')) AND ( .NOT. EMPTY(MANDIBULA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_ANISOCORIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANISOCORIA,'1','2')) AND ( .NOT. EMPTY(ANISOCORIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_OTRO_SS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO_SS,'1','2')) AND ( .NOT. EMPTY(OTRO_SS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_MUERTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MUERTE,'1','2','3','4')) AND ( .NOT. EMPTY(MUERTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_F_TOM_MUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(F_TOM_MUE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_PR_DIA_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PR_DIA_CON,'1','2')) OR ( EMPTY(PR_DIA_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_RESULTADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTADO,'1','2','3','4')) OR ( EMPTY(RESULTADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_IDE_VV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDE_VV,'1','2')) OR ( EMPTY(IDE_VV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_VAR_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAR_IDE,'1','3','4','5','8','0')) OR ( EMPTY(VAR_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COD_EVE,'650','652')) AND ( .NOT. EMPTY(COD_EVE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_24_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','2','7','D','6')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


