FUNCTION FieldRuleFor_Eventos_92_FEC_INGRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INGRES))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CODMUN1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CODMUN1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CODDEP1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CODDEP1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CODPAIS1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CODPAIS1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_FEC_DESP1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_DESP1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_SANGRADOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SANGRADOS,'1','2')) AND ( .NOT. EMPTY(SANGRADOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) AND ( .NOT. EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_DOLOR_ABDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR_ABDO,'1','2')) AND ( .NOT. EMPTY(DOLOR_ABDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_ASTE_ADINI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASTE_ADINI,'1','2')) AND ( .NOT. EMPTY(ASTE_ADINI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_ERUPCION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ERUPCION,'1','2')) AND ( .NOT. EMPTY(ERUPCION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_DOLOR_MUS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR_MUS,'1','2')) AND ( .NOT. EMPTY(DOLOR_MUS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_ANOREXIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANOREXIA,'1','2')) AND ( .NOT. EMPTY(ANOREXIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CONJUNTIVI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONJUNTIVI,'1','2')) AND ( .NOT. EMPTY(CONJUNTIVI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_OTROS_SIGN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_SIGN,'1','2')) AND ( .NOT. EMPTY(OTROS_SIGN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_NOM_CONTA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_CONTA1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_FEC_CONTA1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_CONTA1))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_FEC_ENTREV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_ENTREV))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_HORA_ENTRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(HORA_ENTRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_CARGO_ENTR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CARGO_ENTR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_92_NOM_FAMILI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_FAMILI))
	ENDIF
ENDFUNC


