FUNCTION FieldRuleFor_eventos_54_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TIP_TUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_TUB,'1','2')) AND ( .NOT. EMPTY(TIP_TUB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_LOCTBREXTR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LOCTBREXTR,'1','2','3','4','5','7','8','9','10','11','12')) OR ( EMPTY(LOCTBREXTR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_CLASCASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLASCASO,'1','2','3','4','5')) AND ( .NOT. EMPTY(CLASCASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_CIC_VCG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIC_VCG,'1','2')) AND ( .NOT. EMPTY(CIC_VCG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_VCNBCGCN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VCNBCGCN,'1','2')) AND ( .NOT. EMPTY(VCNBCGCN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TRAB_SALUD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAB_SALUD,'1','2')) AND ( .NOT. EMPTY(TRAB_SALUD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_PREV_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PREV_VIH,'1','2')) AND ( .NOT. EMPTY(PREV_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_CONSPREVIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONSPREVIH,'1','2')) OR ( EMPTY(CONSPREVIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_PRUEBDIAGN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUEBDIAGN,'1','2')) OR ( EMPTY(PRUEBDIAGN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TER_PREV_T
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TER_PREV_T,'1','2')) OR ( EMPTY(TER_PREV_T)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TRAT_ANTIR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAT_ANTIR,'1','2')) OR ( EMPTY(TRAT_ANTIR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=2.0  AND PESO_ACT <=250.0 AND ISNUMERIC(PESO_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TALLA_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_ACT>=0.20  AND TALLA_ACT <=2.5 AND ISNUMERIC(TALLA_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_INI_TRAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INI_TRAT,'1','2')) AND ( .NOT. EMPTY(INI_TRAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_BACILOSCOP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BACILOSCOP,'1','2')) AND ( .NOT. EMPTY(BACILOSCOP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_RES_BK
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BK,'1','2','3','4')) OR ( EMPTY(RES_BK)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_REA_CUL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REA_CUL,'1','2')) AND ( .NOT. EMPTY(REA_CUL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_RESCULTIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESCULTIVO,'1','2')) OR ( EMPTY(RESCULTIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_RES_CULT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_CULT,'1','2','3','4','5','6','7')) OR ( EMPTY(RES_CULT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_HISTOPATOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HISTOPATOL,'1','2')) AND ( .NOT. EMPTY(HISTOPATOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_RESHISTOPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESHISTOPA,'1','2')) OR ( EMPTY(RESHISTOPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_PRUEB_MOLE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUEB_MOLE,'1','2')) AND ( .NOT. EMPTY(PRUEB_MOLE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_NOM_PMOLEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NOM_PMOLEC,'1','2','3')) OR ( EMPTY(NOM_PMOLEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_CLI_PTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLI_PTA,'1','2')) AND ( .NOT. EMPTY(CLI_PTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_NEX_EPI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NEX_EPI,'1','2')) AND ( .NOT. EMPTY(NEX_EPI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_REDIOLOGIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REDIOLOGIC,'1','2')) AND ( .NOT. EMPTY(REDIOLOGIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_ADA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADA,'1','2')) AND ( .NOT. EMPTY(ADA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_TUBERCULIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TUBERCULIN,'1','2')) AND ( .NOT. EMPTY(TUBERCULIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_RES_PRUVIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_PRUVIH,'1','2','3')) OR ( EMPTY(RES_PRUVIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) AND ( .NOT. EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_SILICOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SILICOSIS,'1','2')) AND ( .NOT. EMPTY(SILICOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_54_ENFE_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENFE_RENAL,'1','2')) AND ( .NOT. EMPTY(ENFE_RENAL)))
	ENDIF
ENDFUNC


