FUNCTION FieldRuleFor_eventos_58_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SIT_DEF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_DEF,'1','2','3','4','5','6','7')) AND ( .NOT. EMPTY(SIT_DEF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CONVIVENCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONVIVENCI,'1','2','3','4')) AND ( .NOT. EMPTY(CONVIVENCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ESCOLARIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESCOLARIDA,'1','2','3','4','5')) AND ( .NOT. EMPTY(ESCOLARIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_REG_FEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REG_FEC,'1','2','3','4','5','6','7','8','9')) AND ( .NOT. EMPTY(REG_FEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_GESTACIONE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GESTACIONE)>=1  AND  VAL(GESTACIONE) <= 20 AND ISNUMERIC(GESTACIONE)) AND ( .NOT. EMPTY(GESTACIONE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_PARTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(PARTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CESAREAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CESAREAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ABORTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(ABORTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_MUERTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(MUERTOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_VIVOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(VIVOS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_NINGUNO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NINGUNO,'1','2')) AND ( .NOT. EMPTY(NINGUNO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_HIP_CRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIP_CRO,'1','2')) AND ( .NOT. EMPTY(HIP_CRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CARDIOPATÍ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CARDIOPATÍ,'1','2')) AND ( .NOT. EMPTY(CARDIOPATÍ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) AND ( .NOT. EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_MOLA_HIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOLA_HIDA,'1','2')) AND ( .NOT. EMPTY(MOLA_HIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_PRETERMINO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRETERMINO,'1','2')) AND ( .NOT. EMPTY(PRETERMINO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_BAJO_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BAJO_PESO,'1','2')) AND ( .NOT. EMPTY(BAJO_PESO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_MACROSOMIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MACROSOMIC,'1','2')) AND ( .NOT. EMPTY(MACROSOMIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_TRANSTORNO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRANSTORNO,'1','2')) AND ( .NOT. EMPTY(TRANSTORNO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_OBESIDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OBESIDAD,'1','2')) AND ( .NOT. EMPTY(OBESIDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_D_CRONICA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(D_CRONICA,'1','2')) AND ( .NOT. EMPTY(D_CRONICA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_INTER_GENE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INTER_GENE,'1','2')) AND ( .NOT. EMPTY(INTER_GENE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ITS_DIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ITS_DIS,'1','2')) AND ( .NOT. EMPTY(ITS_DIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_VIH_SIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIH_SIDA,'1','2')) AND ( .NOT. EMPTY(VIH_SIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_OTRAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRAS,'1','2')) AND ( .NOT. EMPTY(OTRAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_RH_NEGATIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RH_NEGATIV,'1','2')) AND ( .NOT. EMPTY(RH_NEGATIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_TABAQUISMO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TABAQUISMO,'1','2')) AND ( .NOT. EMPTY(TABAQUISMO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ALCOHOLISM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALCOHOLISM,'1','2')) AND ( .NOT. EMPTY(ALCOHOLISM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_PSICOACTIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSICOACTIV,'1','2')) AND ( .NOT. EMPTY(PSICOACTIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_DEF_CONDIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEF_CONDIC,'1','2')) AND ( .NOT. EMPTY(DEF_CONDIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SIFILIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIFILIS,'1','2')) AND ( .NOT. EMPTY(SIFILIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_HEPATITISB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEPATITISB,'1','2')) AND ( .NOT. EMPTY(HEPATITISB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_OTROS_FR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_FR,'1','2')) AND ( .NOT. EMPTY(OTROS_FR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_GINGIVITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GINGIVITIS,'1','2')) AND ( .NOT. EMPTY(GINGIVITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_PREECLAMPS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PREECLAMPS,'1','2')) AND ( .NOT. EMPTY(PREECLAMPS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ECLAMPSIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ECLAMPSIA,'1','2')) AND ( .NOT. EMPTY(ECLAMPSIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SIN_HELLP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIN_HELLP,'1','2')) AND ( .NOT. EMPTY(SIN_HELLP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_D_GESTACIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(D_GESTACIO,'1','2')) AND ( .NOT. EMPTY(D_GESTACIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SEPSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEPSIS,'1','2')) AND ( .NOT. EMPTY(SEPSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_HEM_1ER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEM_1ER,'1','2')) AND ( .NOT. EMPTY(HEM_1ER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_HEM_2DO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEM_2DO,'1','2')) AND ( .NOT. EMPTY(HEM_2DO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_HEM_3ER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEM_3ER,'1','2')) AND ( .NOT. EMPTY(HEM_3ER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_DESP_CEFAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESP_CEFAL,'1','2')) AND ( .NOT. EMPTY(DESP_CEFAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_RETARDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RETARDO,'1','2')) AND ( .NOT. EMPTY(RETARDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ENFER_AUTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENFER_AUTO,'1','2')) AND ( .NOT. EMPTY(ENFER_AUTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_MALARIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALARIA,'1','2')) AND ( .NOT. EMPTY(MALARIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_EMBARAZO_N
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EMBARAZO_N,'1','2')) AND ( .NOT. EMPTY(EMBARAZO_N)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_VIOLECIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIOLECIA,'1','2')) AND ( .NOT. EMPTY(VIOLECIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_GES_PRO_VS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GES_PRO_VS,'1','2')) AND ( .NOT. EMPTY(GES_PRO_VS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_FETO_INCOM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FETO_INCOM,'1','2')) AND ( .NOT. EMPTY(FETO_INCOM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SIN_DEPRES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIN_DEPRES,'1','2')) AND ( .NOT. EMPTY(SIN_DEPRES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_OTRAS_COMP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRAS_COMP,'1','2')) AND ( .NOT. EMPTY(OTRAS_COMP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_NUM_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NUM_CON)>=0  AND  VAL(NUM_CON) <=25 AND ISNUMERIC(NUM_CON)) AND ( .NOT. EMPTY(NUM_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SI_CTRL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SI_CTRL)>= 1  AND  VAL(SI_CTRL) <= 45 AND ISNUMERIC(SI_CTRL)) OR ( EMPTY(SI_CTRL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CON_REA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_REA,'1','2','3','4','5')) OR ( EMPTY(CON_REA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_NIV_ATE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV_ATE,'1','2','3','4')) OR ( EMPTY(NIV_ATE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_REM_OPO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REM_OPO,'1','2','3')) AND ( .NOT. EMPTY(REM_OPO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_MOM_OCU_P
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MOM_OCU_P,'1','2','3','4')) AND ( .NOT. EMPTY(MOM_OCU_P)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_SEM_MUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(SEM_MUE)>= 1  AND  VAL(SEM_MUE) <= 42 AND ISNUMERIC(SEM_MUE)) AND ( .NOT. EMPTY(SEM_MUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_TIP_PAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_PAR,'1','2','3','4','5')) OR ( EMPTY(TIP_PAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_PAR_ATE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PAR_ATE,'1','2','3','4','5','6','7')) OR ( EMPTY(PAR_ATE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_NIV_ATE_PA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV_ATE_PA,'1','2','3','4')) OR ( EMPTY(NIV_ATE_PA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CAU_BAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(CAU_BAS))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_CAU_MTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAU_MTE,'1','2','3')) AND ( .NOT. EMPTY(CAU_MTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_DEMORAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEMORAS,'1','2')) AND ( .NOT. EMPTY(DEMORAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'1','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_58_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


