FUNCTION FieldRuleFor_eventos_71_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_TIPO_PRUEB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_PRUEB,'1','2')) AND ( .NOT. EMPTY(TIPO_PRUEB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_IFI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IFI,'1','2')) OR ( EMPTY(IFI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_SEG_TAMIZA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEG_TAMIZA,'1','2')) OR ( EMPTY(SEG_TAMIZA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_RES_INMUNO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_INMUNO,'1','2','3')) OR ( EMPTY(RES_INMUNO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_UBIC_DONAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UBIC_DONAN,'1','2')) OR ( EMPTY(UBIC_DONAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_DONAN_ASIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DONAN_ASIS,'1','2')) OR ( EMPTY(DONAN_ASIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_CAUSA_NOUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAUSA_NOUB,'1','2','3','4')) OR ( EMPTY(CAUSA_NOUB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_INFORME_ST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INFORME_ST,'1','2','3')) OR ( EMPTY(INFORME_ST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_71_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


