FUNCTION FieldRuleFor_Eventos_93_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_PRE_CAR_V1
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRE_CAR_V1,'1','2')) AND ( .NOT. EMPTY(PRE_CAR_V1)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_VAC_SP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_SP,'1','2','3')) AND ( .NOT. EMPTY(VAC_SP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_VAC_EI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_EI,'1','2','3')) AND ( .NOT. EMPTY(VAC_EI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_ASMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASMA,'1','2')) AND ( .NOT. EMPTY(ASMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_EPOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPOC,'1','2')) AND ( .NOT. EMPTY(EPOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) AND ( .NOT. EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIH,'1','2')) AND ( .NOT. EMPTY(VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_ENF_CARD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENF_CARD,'1','2')) AND ( .NOT. EMPTY(ENF_CARD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_CANCER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CANCER,'1','2')) AND ( .NOT. EMPTY(CANCER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_MALNUTRI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MALNUTRI,'1','2')) AND ( .NOT. EMPTY(MALNUTRI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_OBESIDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OBESIDAD,'1','2')) AND ( .NOT. EMPTY(OBESIDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_INS_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INS_RENAL,'1','2')) AND ( .NOT. EMPTY(INS_RENAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_OTR_MEDINM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_MEDINM,'1','2')) AND ( .NOT. EMPTY(OTR_MEDINM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_FUMADOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FUMADOR,'1','2')) AND ( .NOT. EMPTY(FUMADOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_OTROS_DC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_DC,'1','2')) AND ( .NOT. EMPTY(OTROS_DC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_TOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOS,'1','2')) AND ( .NOT. EMPTY(TOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DOL_GAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOL_GAR,'1','2')) AND ( .NOT. EMPTY(DOL_GAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_RINORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RINORREA,'1','2')) AND ( .NOT. EMPTY(RINORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_CONJUNTIVI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONJUNTIVI,'1','2')) AND ( .NOT. EMPTY(CONJUNTIVI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DIF_RES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIF_RES,'1','2')) AND ( .NOT. EMPTY(DIF_RES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_RX_TORAX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RX_TORAX,'1','2','3')) AND ( .NOT. EMPTY(RX_TORAX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_HALLAZ_RAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HALLAZ_RAD,'1','2','3')) OR ( EMPTY(HALLAZ_RAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_USO_ANTIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USO_ANTIB,'1','2')) AND ( .NOT. EMPTY(USO_ANTIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_USO_ANTIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(USO_ANTIV,'1','2')) AND ( .NOT. EMPTY(USO_ANTIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_SERV_HOSP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SERV_HOSP,'1','3')) OR ( EMPTY(SERV_HOSP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DER_PLE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DER_PLE,'1','2')) AND ( .NOT. EMPTY(DER_PLE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DER_PER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DER_PER,'1','2')) AND ( .NOT. EMPTY(DER_PER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_MIOCARDITI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIOCARDITI,'1','2')) AND ( .NOT. EMPTY(MIOCARDITI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_SEPTICEMIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEPTICEMIA,'1','2')) AND ( .NOT. EMPTY(SEPTICEMIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_FALLA_RESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_RESP,'1','2')) AND ( .NOT. EMPTY(FALLA_RESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_OTROS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS,'1','2')) AND ( .NOT. EMPTY(OTROS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_DX_INI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DX_INI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_Eventos_93_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


