FUNCTION FieldRuleFor_eventos_35_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_TIP_AGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_AGR,'1','2','3','6','7','8')) AND ( .NOT. EMPTY(TIP_AGR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AREA_MORDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AREA_MORDE,'1','2')) OR ( EMPTY(AREA_MORDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AGR_PRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGR_PRO,'1','2')) AND ( .NOT. EMPTY(AGR_PRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_TIP_LES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_LES,'1','2')) AND ( .NOT. EMPTY(TIP_LES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PROFUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROFUN,'1','2')) AND ( .NOT. EMPTY(PROFUN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_CCC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CCC,'1','2')) AND ( .NOT. EMPTY(CCC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_MAN_DED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MAN_DED,'1','2')) AND ( .NOT. EMPTY(MAN_DED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_TRONCO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRONCO,'1','2')) AND ( .NOT. EMPTY(TRONCO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_MIE_SUP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIE_SUP,'1','2')) AND ( .NOT. EMPTY(MIE_SUP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_MIE_INF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIE_INF,'1','2')) AND ( .NOT. EMPTY(MIE_INF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PIES_DEDOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PIES_DEDOS,'1','2')) OR ( EMPTY(PIES_DEDOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_GENIT_EXT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GENIT_EXT,'1','2')) OR ( EMPTY(GENIT_EXT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_FEC_EXP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_EXP))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ESP_ANI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESP_ANI,'1','2','3','4','5','7','8','9','10','12','13','14')) AND ( .NOT. EMPTY(ESP_ANI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ANT_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANT_VAC,'1','2','3')) OR ( EMPTY(ANT_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_CAR_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAR_VAC,'1','2')) OR ( EMPTY(CAR_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_EST_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_MA,'1','2','3')) OR ( EMPTY(EST_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ESTADO_ANI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADO_ANI,'1','2','3')) OR ( EMPTY(ESTADO_ANI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_UBICACION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UBICACION,'1','2')) OR ( EMPTY(UBICACION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_SUE_ANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SUE_ANT,'1','2','3')) AND ( .NOT. EMPTY(SUE_ANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_VAC_ANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAC_ANT,'1','2','3')) AND ( .NOT. EMPTY(VAC_ANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_APL_SA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(APL_SA,'1','2')) AND ( .NOT. EMPTY(APL_SA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_APL_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(APL_VAC,'1','2')) AND ( .NOT. EMPTY(APL_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_OTROS_MEDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTROS_MEDI,'1','2')) AND ( .NOT. EMPTY(OTROS_MEDI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_HIPOREXIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOREXIA,'1','2')) AND ( .NOT. EMPTY(HIPOREXIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PARESIAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARESIAS,'1','2')) AND ( .NOT. EMPTY(PARESIAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PARESTESIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARESTESIA,'1','2')) AND ( .NOT. EMPTY(PARESTESIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_DISFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISFAGIA,'1','2')) AND ( .NOT. EMPTY(DISFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ODINOFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ODINOFAGIA,'1','2')) AND ( .NOT. EMPTY(ODINOFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ARREFLEXIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARREFLEXIA,'1','2')) AND ( .NOT. EMPTY(ARREFLEXIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PSICOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSICOSIS,'1','2')) AND ( .NOT. EMPTY(PSICOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_FASCIES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FASCIES,'1','2')) AND ( .NOT. EMPTY(FASCIES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_SIALORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIALORREA,'1','2')) AND ( .NOT. EMPTY(SIALORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AEROFOBIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AEROFOBIA,'1','2')) AND ( .NOT. EMPTY(AEROFOBIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_HIDROFOBIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIDROFOBIA,'1','2')) AND ( .NOT. EMPTY(HIDROFOBIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_TRANQ_EXCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRANQ_EXCI,'1','2')) AND ( .NOT. EMPTY(TRANQ_EXCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_DEPRESION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEPRESION,'1','2')) AND ( .NOT. EMPTY(DEPRESION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_HIPEREXITA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPEREXITA,'1','2')) AND ( .NOT. EMPTY(HIPEREXITA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AGRESIVIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGRESIVIDA,'1','2')) AND ( .NOT. EMPTY(AGRESIVIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ESPASMOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESPASMOS,'1','2')) AND ( .NOT. EMPTY(ESPASMOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_CONVULSION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONVULSION,'1','2')) AND ( .NOT. EMPTY(CONVULSION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PARALISIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARALISIS,'1','2')) AND ( .NOT. EMPTY(PARALISIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_CRIS_RESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRIS_RESP,'1','2')) AND ( .NOT. EMPTY(CRIS_RESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_COMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMA,'1','2')) AND ( .NOT. EMPTY(COMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PARO_RESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARO_RESP,'1','2')) AND ( .NOT. EMPTY(PARO_RESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_PR_DIAG_CO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PR_DIAG_CO,'1','2','3','4','5')) OR ( EMPTY(PR_DIAG_CO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_RESULTADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTADO,'1','2','4')) OR ( EMPTY(RESULTADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_ID_VARIANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ID_VARIANT,'1','2','3')) OR ( EMPTY(ID_VARIANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_VAR_IDENTI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VAR_IDENTI,'1','3','4','5','8','9','0')) OR ( EMPTY(VAR_IDENTI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_35_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


