FUNCTION FieldRuleFor_eventos_82_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_SIT_DEFUNC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIT_DEFUNC,'1','2','3','4','5','6','9')) AND ( .NOT. EMPTY(SIT_DEFUNC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_NOM_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_MADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_APEL_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(APEL_MADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS','PE')) AND ( .NOT. EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_NUM_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_EDAD_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_MADRE>= 10  AND EDAD_MADRE <=60 AND ISNUMERIC(EDAD_MADRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_NUM_HI_VIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_HI_VIV>= 0  AND NUM_HI_VIV <=20 AND ISNUMERIC(NUM_HI_VIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_NUM_HI_MUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NUM_HI_MUE>= 1  AND NUM_HI_MUE <=20 AND ISNUMERIC(NUM_HI_MUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_EST_CONYUG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_CONYUG,'1','2','3','4','5','6','9')) AND ( .NOT. EMPTY(EST_CONYUG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_ULT_AÑO_ES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((ULT_AÑO_ES>= 0  AND ULT_AÑO_ES <=11 AND ISNUMERIC(ULT_AÑO_ES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_ASIS_MEDIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASIS_MEDIC,'1','2','3')) AND ( .NOT. EMPTY(ASIS_MEDIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_C_DIRECT_A
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(C_DIRECT_A))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_CLAS_CASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_CASO,'1','2','3')) AND ( .NOT. EMPTY(CLAS_CASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_82_EST_INGR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EST_INGR,0,2,3)) OR (EST_INGR=0))
	ENDIF
ENDFUNC


