FUNCTION FieldRuleFor_upgd_FEC_CAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_CAR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_RAZ_SOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(RAZ_SOC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_DIR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(DIR)) OR INLIST(COD_EVE,'357','351','352')
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_REP_LEG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(REP_LEG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COR_ELE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COR_ELE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_RES_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(RES_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(TEL))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_FEC_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_CON))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NAT_JUR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NAT_JUR,1,2,3,4)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NIV,1,2,3)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_UNI_ANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(UNI_ANA,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COV,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TAL_HUM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TAL_HUM,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TEC_DIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TEC_DIS,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COM,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_FAX_MOD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FAX_MOD,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TIE_COR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIE_COR,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_INT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INT,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TEL_FAX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TEL_FAX,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_RAD_TEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RAD_TEL,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_ACT_SIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_SIV,1,2)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NIT_UPGD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NIT_UPGD))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_ES_UNI_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ES_UNI_NOT,'1','2')) AND ( .NOT. EMPTY(ES_UNI_NOT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_ESTADOUPGD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOUPGD,'1','2')) AND ( .NOT. EMPTY(ESTADOUPGD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_FEC_INICAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INICAR))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_HOSP_UNIVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HOSP_UNIVE,'1','2')) OR ( EMPTY(HOSP_UNIVE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_REG_EXCEPC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REG_EXCEPC,'1','2')) OR ( EMPTY(REG_EXCEPC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_TOT_CAMAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(TOT_CAMAS)>=1  AND  VAL(TOT_CAMAS) <= 99999 AND ISNUMERIC(TOT_CAMAS)) OR ( EMPTY(TOT_CAMAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_COMITE_INF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMITE_INF,'1','2')) OR ( EMPTY(COMITE_INF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_BI_PROFESI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BI_PROFESI,'1','2')) OR ( EMPTY(BI_PROFESI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_IAAS_ULTIM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(IAAS_ULTIM)>=0  AND  VAL(IAAS_ULTIM) <=100 AND ISNUMERIC(IAAS_ULTIM)) OR ( EMPTY(IAAS_ULTIM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_INF_TENDEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INF_TENDEN,'1','2')) OR ( EMPTY(INF_TENDEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SOCIAL_TEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SOCIAL_TEN,'1','2')) OR ( EMPTY(SOCIAL_TEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_MICROB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_MICROB,'1','2')) OR ( EMPTY(LAB_MICROB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_PROPIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_PROPIO,'1','2')) OR ( EMPTY(LAB_PROPIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_IDENT_GYE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IDENT_GYE,'1','2')) OR ( EMPTY(IDENT_GYE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_PRUE_SUCEP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUE_SUCEP,'1','2')) OR ( EMPTY(PRUE_SUCEP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_AUTOMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_AUTOMA,'1','2')) OR ( EMPTY(LAB_AUTOMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_VITEK
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VITEK,'1','2')) OR ( EMPTY(VITEK)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_MICROSCAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICROSCAN,'1','2')) OR ( EMPTY(MICROSCAN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_PHOENIX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PHOENIX,'1','2')) OR ( EMPTY(PHOENIX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_CCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_CCI,'1','2')) OR ( EMPTY(LAB_CCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_CCE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_CCE,'1','2')) OR ( EMPTY(LAB_CCE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_MICR_CDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICR_CDI,'1','2')) OR ( EMPTY(MICR_CDI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_WHONET
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(WHONET,'1','2')) OR ( EMPTY(WHONET)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_INFORM_PAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INFORM_PAT,'1','2')) OR ( EMPTY(INFORM_PAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_CON_PE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_CON_PE,'1','2')) OR ( EMPTY(LAB_CON_PE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_REM_CE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_REM_CE,'1','2')) OR ( EMPTY(LAB_REM_CE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_LAB_REPORT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LAB_REPORT,'1','2')) OR ( EMPTY(LAB_REPORT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_QUIEN_VCAB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUIEN_VCAB,'1','2','3')) OR ( EMPTY(QUIEN_VCAB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SER_CESARE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_CESARE,'1','2')) OR ( EMPTY(SER_CESARE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SER_PAR_VA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_PAR_VA,'1','2')) OR ( EMPTY(SER_PAR_VA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SER_COLECI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_COLECI,'1','2')) OR ( EMPTY(SER_COLECI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SER_HERNIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_HERNIO,'1','2')) OR ( EMPTY(SER_HERNIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_SER_REVASC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_REVASC,'1','2')) OR ( EMPTY(SER_REVASC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NOTIF_IAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NOTIF_IAD,'1','2')) AND ( .NOT. EMPTY(NOTIF_IAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NOTIF_ISO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NOTIF_ISO,'1','2')) AND ( .NOT. EMPTY(NOTIF_ISO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_NOTIF_CAB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NOTIF_CAB,'1','2')) AND ( .NOT. EMPTY(NOTIF_CAB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_upgd_ESTADOTRAN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTADOTRAN,'3','2')) AND ( .NOT. EMPTY(ESTADOTRAN)))
	ENDIF
ENDFUNC


