FUNCTION FieldRuleFor_eventos_53_TRIM_GEST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRIM_GEST,'1','2','3')) AND ( .NOT. EMPTY(TRIM_GEST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_CIR_BRAZO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((CIR_BRAZO>=8.0  AND CIR_BRAZO <=50.0 AND ISNUMERIC(CIR_BRAZO)) OR (CIR_BRAZO=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_TAMI_ALERT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(TAMI_ALERT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_N_GES_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_GES_ACT>=1  AND N_GES_ACT <=25 AND ISNUMERIC(N_GES_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_S_GES_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(S_GES_ACT,'1','2','3')) AND ( .NOT. EMPTY(S_GES_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_N_S_GES_AC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_S_GES_AC>=3  AND N_S_GES_AC <=45 AND ISNUMERIC(N_S_GES_AC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_PESO_PREG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_PREG>=30.0  AND PESO_PREG <=200.0 AND ISNUMERIC(PESO_PREG)) OR (PESO_PREG=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=30.0  AND PESO_ACT <=200.0 AND ISNUMERIC(PESO_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_TALLA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA>=120.0  AND TALLA <=220.0 AND ISNUMERIC(TALLA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_CLAS_IMC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_IMC,'1','2','3','4')) AND ( .NOT. EMPTY(CLAS_IMC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_EDA_GES_IN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDA_GES_IN>=2  AND EDA_GES_IN <=45 AND ISNUMERIC(EDA_GES_IN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_N_CONT_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((N_CONT_PRE>=1  AND N_CONT_PRE <=25 AND ISNUMERIC(N_CONT_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_MULT_EMB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MULT_EMB,'1','2','3')) AND ( .NOT. EMPTY(MULT_EMB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_HEMOGLOBIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((HEMOGLOBIN>=4.0  AND HEMOGLOBIN <=20.0 AND ISNUMERIC(HEMOGLOBIN)) OR (HEMOGLOBIN=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_HEMO_ALERT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(HEMO_ALERT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_MICR_CALC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICR_CALC,'1','2')) AND ( .NOT. EMPTY(MICR_CALC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_MICR_HIERR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICR_HIERR,'1','2')) AND ( .NOT. EMPTY(MICR_HIERR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_MICR_ACID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MICR_ACID,'1','2')) AND ( .NOT. EMPTY(MICR_ACID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_53_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


