FUNCTION FieldRuleFor_eventos_44_EDA_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDA_GES)>= 2  AND  VAL(EDA_GES) <= 42 AND ISNUMERIC(EDA_GES)) OR ( EMPTY(EDA_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_TOMASEROLO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TOMASEROLO,'1','2')) AND ( .NOT. EMPTY(TOMASEROLO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_EG_PRI_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EG_PRI_S)>= 2  AND  VAL(EG_PRI_S) <= 42 AND ISNUMERIC(EG_PRI_S)) OR ( EMPTY(EG_PRI_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_RESSERVDRL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESSERVDRL,'3','4','5','6','7','8','9','10','11','12','13')) OR ( EMPTY(RESSERVDRL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_PRUETREPON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUETREPON,'1','2')) AND ( .NOT. EMPTY(PRUETREPON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_EG_PR_TREP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EG_PR_TREP)>= 2  AND  VAL(EG_PR_TREP) <= 42 AND ISNUMERIC(EG_PR_TREP)) OR ( EMPTY(EG_PR_TREP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_QUE_PR_TRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUE_PR_TRE,'4','5')) OR ( EMPTY(QUE_PR_TRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_RESULTREPO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTREPO,'1','2')) OR ( EMPTY(RESULTREPO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_PEN_BENZAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEN_BENZAT,'0','1','2','3')) AND ( .NOT. EMPTY(PEN_BENZAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_TTO_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TTO_CON,'1','2')) AND ( .NOT. EMPTY(TTO_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_CONDENDIAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONDENDIAG,'1','2','3')) AND ( .NOT. EMPTY(CONDENDIAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_CON_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_PRE,'1','2')) AND ( .NOT. EMPTY(CON_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_NOM_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_MADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS','PE')) AND ( .NOT. EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_NUM_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_RES_GESTAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_GESTAC,'1','3')) AND ( .NOT. EMPTY(RES_GESTAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_NO_PRODUCT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NO_PRODUCT)>= 1 AND ISNUMERIC(NO_PRODUCT)) AND ( .NOT. EMPTY(NO_PRODUCT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_EDA_GES_NA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDA_GES_NA)>= 22  AND  VAL(EDA_GES_NA) <= 42 AND ISNUMERIC(EDA_GES_NA)) AND ( .NOT. EMPTY(EDA_GES_NA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_RES_SER_MP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_SER_MP,'3','4','5','6','7','8','9','10','11','12','13')) AND ( .NOT. EMPTY(RES_SER_MP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_RESULTSERO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTSERO,'3','4','5','6','7','8','9','10','11','12','13','14')) OR ( EMPTY(RESULTSERO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_DIA_EMBACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIA_EMBACT,'1','2')) AND ( .NOT. EMPTY(DIA_EMBACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_44_TIEM_RESID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIEM_RESID,'1','2')) OR ( EMPTY(TIEM_RESID)))
	ENDIF
ENDFUNC


