FUNCTION FieldRuleFor_eventos_14_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_CON_CC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_CC,'1','2','3')) AND ( .NOT. EMPTY(CON_CC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_CAR_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAR_VAC,'1','2')) AND ( .NOT. EMPTY(CAR_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_DOS_APLI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOS_APLI,'0','1','2','3','4','5')) AND ( .NOT. EMPTY(DOS_APLI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_TIP_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_VAC,'1','2','3','4')) OR ( EMPTY(TIP_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2','3')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_AMIGDALITI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AMIGDALITI,'1','2','3')) AND ( .NOT. EMPTY(AMIGDALITI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_FARINGITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FARINGITIS,'1','2','3')) AND ( .NOT. EMPTY(FARINGITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_LARINGITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LARINGITIS,'1','2','3')) AND ( .NOT. EMPTY(LARINGITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_PRE_MEM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRE_MEM,'1','2','3')) AND ( .NOT. EMPTY(PRE_MEM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_COMPLICACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMPLICACI,'1','2','3')) AND ( .NOT. EMPTY(COMPLICACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_TIP_COM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_COM,'1','2','3','4','5')) OR ( EMPTY(TIP_COM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_14_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


