FUNCTION FieldRuleFor_eventos_78_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_EDAD_INICI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_INICI>=6  AND EDAD_INICI <=70 AND ISNUMERIC(EDAD_INICI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_DROGA_INIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DROGA_INIC,'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20')) AND ( .NOT. EMPTY(DROGA_INIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_EDAD_INYEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_INYEC>=6  AND EDAD_INYEC <= 70 AND ISNUMERIC(EDAD_INYEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_DROG_VIA_I
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DROG_VIA_I,'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20')) AND ( .NOT. EMPTY(DROG_VIA_I)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_TRANQU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_TRANQU,'1','2')) AND ( .NOT. EMPTY(ACT_TRANQU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_ESTIMU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_ESTIMU,'1','2')) AND ( .NOT. EMPTY(ACT_ESTIMU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_ALCOHO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_ALCOHO,'1','2')) AND ( .NOT. EMPTY(ACT_ALCOHO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_COCAIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_COCAIN,'1','2')) AND ( .NOT. EMPTY(ACT_COCAIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_HEROIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_HEROIN,'1','2')) AND ( .NOT. EMPTY(ACT_HEROIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_METANF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_METANF,'1','2')) AND ( .NOT. EMPTY(ACT_METANF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_METADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_METADO,'1','2')) AND ( .NOT. EMPTY(ACT_METADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_ANALGE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_ANALGE,'1','2')) AND ( .NOT. EMPTY(ACT_ANALGE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_LSD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_LSD,'1','2')) AND ( .NOT. EMPTY(ACT_LSD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_KETAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_KETAMI,'1','2')) AND ( .NOT. EMPTY(ACT_KETAMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_GHB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_GHB,'1','2')) AND ( .NOT. EMPTY(ACT_GHB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_ACT_SPEEDB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_SPEEDB,'1','2')) AND ( .NOT. EMPTY(ACT_SPEEDB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_FREC_INYEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FREC_INYEC,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(FREC_INYEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_COMP_MATER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMP_MATER,'1','2')) AND ( .NOT. EMPTY(COMP_MATER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_RELSIN_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RELSIN_PRE,'1','2')) AND ( .NOT. EMPTY(RELSIN_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_SOBRED_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SOBRED_AÑO,'1','2')) AND ( .NOT. EMPTY(SOBRED_AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_SOBRED_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SOBRED_MES,'1','2')) AND ( .NOT. EMPTY(SOBRED_MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_78_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


