FUNCTION FieldRuleFor_eventos_03_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_CASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CASO,'1','2','3')) AND ( .NOT. EMPTY(CASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_CLA_CLINIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLA_CLINIC,'1','2')) AND ( .NOT. EMPTY(CLA_CLINIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_BACILOSCOP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BACILOSCOP,'1','2')) AND ( .NOT. EMPTY(BACILOSCOP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_RES_BACILO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(RES_BACILO)>=0.0  AND  VAL(RES_BACILO) <=6.0 AND ISNUMERIC(RES_BACILO)) OR ( EMPTY(RES_BACILO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_BIOPSIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BIOPSIA,'1','2')) AND ( .NOT. EMPTY(BIOPSIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_RES_BIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BIO,'1','2','3','4','5','6')) OR ( EMPTY(RES_BIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_MAX_GRA_DI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MAX_GRA_DI,'0','1','2')) AND ( .NOT. EMPTY(MAX_GRA_DI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_PRE_REA_LE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRE_REA_LE,'1','2','3')) AND ( .NOT. EMPTY(PRE_REA_LE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_NUM_LESION
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(NUM_LESION)>=1  AND  VAL(NUM_LESION) <=99 AND ISNUMERIC(NUM_LESION)) AND ( .NOT. EMPTY(NUM_LESION)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_03_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


