FUNCTION FieldRuleFor_eventos_87_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_TIPO_UCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_UCI,'1','2','3')) AND ( .NOT. EMPTY(TIPO_UCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_FEC_INGUCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_INGUCI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_REMITIDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REMITIDO,'1','2')) AND ( .NOT. EMPTY(REMITIDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CASO_EXTRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CASO_EXTRA,'1','2')) OR ( EMPTY(CASO_EXTRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_TIPO_IAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_IAD,'1','2','3')) AND ( .NOT. EMPTY(TIPO_IAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CRIT_NAV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRIT_NAV,'1','2','3')) OR ( EMPTY(CRIT_NAV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CRIT_ITSAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRIT_ITSAC,'1','2','3')) OR ( EMPTY(CRIT_ITSAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CRIT_ISTUA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CRIT_ISTUA,'1','2','3','4')) OR ( EMPTY(CRIT_ISTUA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_FEC_DIAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_DIAG))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_IAD_POLIM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IAD_POLIM,'1','2')) OR ( EMPTY(IAD_POLIM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_VENTILADOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VENTILADOR,'1','2')) AND ( .NOT. EMPTY(VENTILADOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CAT_CENTRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAT_CENTRA,'1','2')) AND ( .NOT. EMPTY(CAT_CENTRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CAT_URINAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CAT_URINAR,'1','2')) AND ( .NOT. EMPTY(CAT_URINAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_CANCER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CANCER,'1','2')) AND ( .NOT. EMPTY(CANCER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_DESNUTRIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESNUTRIC,'1','2')) AND ( .NOT. EMPTY(DESNUTRIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) AND ( .NOT. EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_ENF_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ENF_RENAL,'1','2')) AND ( .NOT. EMPTY(ENF_RENAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_EPOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPOC,'1','2')) AND ( .NOT. EMPTY(EPOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_INMUNOSUPR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INMUNOSUPR,'1','2')) AND ( .NOT. EMPTY(INMUNOSUPR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_VIH_SIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIH_SIDA,'1','2')) AND ( .NOT. EMPTY(VIH_SIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_INFEC_PREV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INFEC_PREV,'1','2')) AND ( .NOT. EMPTY(INFEC_PREV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_TRAUMATISM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAUMATISM,'1','2')) AND ( .NOT. EMPTY(TRAUMATISM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_OBESIDAD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OBESIDAD,'1','2')) AND ( .NOT. EMPTY(OBESIDAD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_OTRO_FACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO_FACT,'1','2')) AND ( .NOT. EMPTY(OTRO_FACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_VALOR_PESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((VALOR_PESO>=350  AND VALOR_PESO <=4500 AND ISNUMERIC(VALOR_PESO)) OR (VALOR_PESO=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_INSERT_UCI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INSERT_UCI,'1','2')) AND ( .NOT. EMPTY(INSERT_UCI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_87_RETIRO_48H
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RETIRO_48H,'1','2')) AND ( .NOT. EMPTY(RETIRO_48H)))
	ENDIF
ENDFUNC


