FUNCTION FieldRuleFor_eventos_13_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_TIP_TUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_TUB,'1','2')) AND ( .NOT. EMPTY(TIP_TUB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_LOCTBREXTR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LOCTBREXTR,'1','2','3','4','5','6','7','8','9','10','11','12')) OR ( EMPTY(LOCTBREXTR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_CLASCASO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLASCASO,'1','2','3','4')) AND ( .NOT. EMPTY(CLASCASO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_CIC_VCG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIC_VCG,'1','2')) AND ( .NOT. EMPTY(CIC_VCG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_VCNBCGCN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VCNBCGCN,'1','2')) AND ( .NOT. EMPTY(VCNBCGCN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_EMBARAZO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EMBARAZO,'1','2','3')) OR ( EMPTY(EMBARAZO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_CONSPREVIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONSPREVIH,'1','2')) AND ( .NOT. EMPTY(CONSPREVIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_PRUEBDIAGN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUEBDIAGN,'1','2')) AND ( .NOT. EMPTY(PRUEBDIAGN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_ASO_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ASO_VIH,'1','2','3')) AND ( .NOT. EMPTY(ASO_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=2.0  AND PESO_ACT <=250.0 AND ISNUMERIC(PESO_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_TALLA_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_ACT>=0.20  AND TALLA_ACT <=2.5 AND ISNUMERIC(TALLA_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_INI_TRAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INI_TRAT,'1','2')) AND ( .NOT. EMPTY(INI_TRAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_BACILOSCOP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BACILOSCOP,'1','2')) AND ( .NOT. EMPTY(BACILOSCOP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_RES_BK
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BK,'1','2','3','4')) OR ( EMPTY(RES_BK)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_REA_CUL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REA_CUL,'1','2')) AND ( .NOT. EMPTY(REA_CUL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_RESCULTIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESCULTIVO,'1','2')) OR ( EMPTY(RESCULTIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_RES_CULT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_CULT,'1','2','3','4','5','6','7')) OR ( EMPTY(RES_CULT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_HISTOPATOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HISTOPATOL,'1','2')) AND ( .NOT. EMPTY(HISTOPATOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_RESHISTOPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESHISTOPA,'1','2')) OR ( EMPTY(RESHISTOPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_CLI_PTA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLI_PTA,'1','2')) AND ( .NOT. EMPTY(CLI_PTA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_NEX_EPI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NEX_EPI,'1','2')) AND ( .NOT. EMPTY(NEX_EPI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_REDIOLOGIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REDIOLOGIC,'1','2')) AND ( .NOT. EMPTY(REDIOLOGIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_ADA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ADA,'1','2')) AND ( .NOT. EMPTY(ADA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_TUBERCULIN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TUBERCULIN,'1','2')) AND ( .NOT. EMPTY(TUBERCULIN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_MET_HALL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MET_HALL,'1','2','3')) AND ( .NOT. EMPTY(MET_HALL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_POSFTECNTC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(POSFTECNTC,'1','2','3')) AND ( .NOT. EMPTY(POSFTECNTC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_INVESCAMPO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INVESCAMPO,'1','2')) AND ( .NOT. EMPTY(INVESCAMPO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_13_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


