FUNCTION FieldRuleFor_eventos_08_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FEC_ACC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_ACC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ACT_REA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ACT_REA,'1','2','3','5','6','8','7')) AND ( .NOT. EMPTY(ACT_REA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_TIP_ATEN_I
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_ATEN_I,'1','2','3','4','5','6','9','7')) AND ( .NOT. EMPTY(TIP_ATEN_I)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_PRAC_NOMED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRAC_NOMED,'1','2','3','4','5','6')) AND ( .NOT. EMPTY(PRAC_NOMED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_LOC_MOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LOC_MOR,'1','2','3','4','5','6','7','9','10','11','12')) AND ( .NOT. EMPTY(LOC_MOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HUE_COL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HUE_COL,'1','2')) AND ( .NOT. EMPTY(HUE_COL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SER_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_IDE,'1','2')) AND ( .NOT. EMPTY(SER_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SER_CAP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SER_CAP,'1','2')) AND ( .NOT. EMPTY(SER_CAP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_AGE_AGRG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGE_AGRG,'1','2','3','4','7','8','9','6')) AND ( .NOT. EMPTY(AGE_AGRG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_AGE_AGRN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AGE_AGRN,'1','2','3','4','5','6','7','8','9','10','11','12','13','14','16','17','15')) AND ( .NOT. EMPTY(AGE_AGRN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_EDEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA,'1','2')) AND ( .NOT. EMPTY(EDEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DOLOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOLOR,'1','2')) AND ( .NOT. EMPTY(DOLOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ERITEMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ERITEMA,'1','2')) AND ( .NOT. EMPTY(ERITEMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FLICTENAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FLICTENAS,'1','2')) AND ( .NOT. EMPTY(FLICTENAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_PARESTESIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PARESTESIA,'1','2')) AND ( .NOT. EMPTY(PARESTESIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_EQUIMOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EQUIMOSIS,'1','2')) AND ( .NOT. EMPTY(EQUIMOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HEMATOMAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATOMAS,'1','2')) AND ( .NOT. EMPTY(HEMATOMAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_OTRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO,'1','2')) AND ( .NOT. EMPTY(OTRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_NAUSEAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NAUSEAS,'1','2')) AND ( .NOT. EMPTY(NAUSEAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SIALORREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIALORREA,'1','2')) AND ( .NOT. EMPTY(SIALORREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_BRADICARDI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BRADICARDI,'1','2')) AND ( .NOT. EMPTY(BRADICARDI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HIPOTENSIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIPOTENSIO,'1','2')) AND ( .NOT. EMPTY(HIPOTENSIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DOL_ABD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DOL_ABD,'1','2')) AND ( .NOT. EMPTY(DOL_ABD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FAS_NEU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FAS_NEU,'1','2')) AND ( .NOT. EMPTY(FAS_NEU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ALT_VIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALT_VIS,'1','2')) AND ( .NOT. EMPTY(ALT_VIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ALT_SEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALT_SEN,'1','2')) AND ( .NOT. EMPTY(ALT_SEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DEB_MUS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DEB_MUS,'1','2')) AND ( .NOT. EMPTY(DEB_MUS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_OLIGURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OLIGURIA,'1','2')) AND ( .NOT. EMPTY(OLIGURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_CIANOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CIANOSIS,'1','2')) AND ( .NOT. EMPTY(CIANOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_EPISTAXIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPISTAXIS,'1','2')) AND ( .NOT. EMPTY(EPISTAXIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_GINGIVORRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GINGIVORRA,'1','2')) AND ( .NOT. EMPTY(GINGIVORRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HEMATEMESI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATEMESI,'1','2')) AND ( .NOT. EMPTY(HEMATEMESI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HEMATURIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATURIA,'1','2')) AND ( .NOT. EMPTY(HEMATURIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HEMATOQUEX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HEMATOQUEX,'1','2')) AND ( .NOT. EMPTY(HEMATOQUEX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_VERTIGO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VERTIGO,'1','2')) AND ( .NOT. EMPTY(VERTIGO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_PTO_PALPEB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PTO_PALPEB,'1','2')) AND ( .NOT. EMPTY(PTO_PALPEB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DIF_HABLAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIF_HABLAR,'1','2')) AND ( .NOT. EMPTY(DIF_HABLAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_DISFAGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DISFAGIA,'1','2')) AND ( .NOT. EMPTY(DISFAGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_OTRO_MS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO_MS,'1','2')) AND ( .NOT. EMPTY(OTRO_MS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_CELULITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CELULITIS,'1','2')) AND ( .NOT. EMPTY(CELULITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ABSCESO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ABSCESO,'1','2')) AND ( .NOT. EMPTY(ABSCESO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_NECROSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NECROSIS,'1','2')) AND ( .NOT. EMPTY(NECROSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_MIONECROSI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIONECROSI,'1','2')) AND ( .NOT. EMPTY(MIONECROSI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FASCEITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FASCEITIS,'1','2')) AND ( .NOT. EMPTY(FASCEITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ALTER_CIR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ALTER_CIR,'1','2')) AND ( .NOT. EMPTY(ALTER_CIR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_OTRO_CL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO_CL,'1','2')) AND ( .NOT. EMPTY(OTRO_CL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_ANE_AGU
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ANE_AGU,'1','2')) AND ( .NOT. EMPTY(ANE_AGU)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SHO_HIP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SHO_HIP,'1','2')) AND ( .NOT. EMPTY(SHO_HIP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SHO_SEP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SHO_SEP,'1','2')) AND ( .NOT. EMPTY(SHO_SEP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_IRA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(IRA,'1','2')) AND ( .NOT. EMPTY(IRA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_CID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CID,'1','2')) AND ( .NOT. EMPTY(CID)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_HSA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HSA,'1','2')) AND ( .NOT. EMPTY(HSA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_EDEMA_CEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EDEMA_CEL,'1','2')) AND ( .NOT. EMPTY(EDEMA_CEL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FALLA_VENT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FALLA_VENT,'1','2')) AND ( .NOT. EMPTY(FALLA_VENT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_COMA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COMA,'1','2')) AND ( .NOT. EMPTY(COMA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_OTRA_COM_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRA_COM_S,'1','2')) AND ( .NOT. EMPTY(OTRA_COM_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SEV_ACC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEV_ACC,'1','2','3','4')) AND ( .NOT. EMPTY(SEV_ACC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_EMP_SUE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EMP_SUE,'1','2')) AND ( .NOT. EMPTY(EMP_SUE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_TIP_SA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_SA,'1','3')) OR ( EMPTY(TIP_SA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_REACC_APL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REACC_APL,'1','2','3')) OR ( EMPTY(REACC_APL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_REMITIDO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(REMITIDO,'1','2')) AND ( .NOT. EMPTY(REMITIDO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_TTO_QX
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TTO_QX,'1','2')) AND ( .NOT. EMPTY(TTO_QX)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_TIP_TTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_TTO,'1','2','3','4','5','6')) OR ( EMPTY(TIP_TTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_SIND_COMPA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SIND_COMPA,'1','2')) AND ( .NOT. EMPTY(SIND_COMPA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_08_FABRI_SUER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FABRI_SUER,'1','2','3','4')) OR ( EMPTY(FABRI_SUER)))
	ENDIF
ENDFUNC


