FUNCTION FieldRuleFor_eventos_56_EMB_MULTIP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EMB_MULTIP,'1','2')) AND ( .NOT. EMPTY(EMB_MULTIP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NATIVIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NATIVIVO,'1','2','3')) AND ( .NOT. EMPTY(NATIVIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_EDAD_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDAD_GES)>= 10  AND  VAL(EDAD_GES) <=45 AND ISNUMERIC(EDAD_GES)) OR ( EMPTY(EDAD_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_PESO_NAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PESO_NAC)>=50  AND  VAL(PESO_NAC) <=6000 AND ISNUMERIC(PESO_NAC)) OR ( EMPTY(PESO_NAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_EDADGE_DIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDADGE_DIA)>= 1  AND  VAL(EDADGE_DIA) <= 45 AND ISNUMERIC(EDADGE_DIA)) AND ( .NOT. EMPTY(EDADGE_DIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_PATOL_CRON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PATOL_CRON,'1','2')) AND ( .NOT. EMPTY(PATOL_CRON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NOM_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NOM_MADRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_TIP_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE_MA,'RC','TI','CC','CE','PA','MS','AS','PE')) AND ( .NOT. EMPTY(TIP_IDE_MA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NUM_IDE_MA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE_MA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_EDAD_MADRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((EDAD_MADRE>=9 AND ISNUMERIC(EDAD_MADRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NO_EMBARAZ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_EMBARAZ>=1  AND NO_EMBARAZ <=30 AND ISNUMERIC(NO_EMBARAZ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NO_NAC_VIV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_NAC_VIV>= 0  AND NO_NAC_VIV <= 20 AND ISNUMERIC(NO_NAC_VIV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NO_ABORTOS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_ABORTOS>= 0 AND ISNUMERIC(NO_ABORTOS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_NO_MORTINA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((NO_MORTINA>= 0 AND ISNUMERIC(NO_MORTINA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_DIAGNOSTIC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIAGNOSTIC,'1','2')) AND ( .NOT. EMPTY(DIAGNOSTIC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_STORCH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(STORCH,'1','2')) AND ( .NOT. EMPTY(STORCH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_T4_TOTAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(T4_TOTAL,'1','2')) AND ( .NOT. EMPTY(T4_TOTAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_RES_T4_TOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_T4_TOT,'2','3')) OR ( EMPTY(RES_T4_TOT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_T4_LIBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(T4_LIBRE,'1','2')) AND ( .NOT. EMPTY(T4_LIBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_RES_T4_LIB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_T4_LIB,'2','3')) OR ( EMPTY(RES_T4_LIB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_PER_CEFALI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PER_CEFALI>=10.0  AND PER_CEFALI <= 60.0 AND ISNUMERIC(PER_CEFALI)) OR (PER_CEFALI=0))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_TSH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TSH,'1','2')) AND ( .NOT. EMPTY(TSH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_56_RES_TSH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_TSH,'1','2')) OR ( EMPTY(RES_TSH)))
	ENDIF
ENDFUNC


