FUNCTION FieldRuleFor_eventos_86_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_PIEL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PIEL,'1','2')) OR ( EMPTY(PIEL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_HIGADO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HIGADO,'1','2')) OR ( EMPTY(HIGADO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_BAZO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BAZO,'1','2')) OR ( EMPTY(BAZO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_PULMON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PULMON,'1','2')) OR ( EMPTY(PULMON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_CEREBRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEREBRO,'1','2')) OR ( EMPTY(CEREBRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_MIOCARDIO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MIOCARDIO,'1','2')) OR ( EMPTY(MIOCARDIO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_MEDULA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MEDULA,'1','2')) OR ( EMPTY(MEDULA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_RIÑON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RIÑON,'1','2')) OR ( EMPTY(RIÑON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_FIEBRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FIEBRE,'1','2')) AND ( .NOT. EMPTY(FIEBRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_ARTRALGIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRALGIA,'1','2')) AND ( .NOT. EMPTY(ARTRALGIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_CEFALEA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CEFALEA,'1','2')) AND ( .NOT. EMPTY(CEFALEA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_RASH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RASH,'1','2')) AND ( .NOT. EMPTY(RASH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_VOMITO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VOMITO,'1','2')) AND ( .NOT. EMPTY(VOMITO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_86_DIARREA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIARREA,'1','2')) AND ( .NOT. EMPTY(DIARREA)))
	ENDIF
ENDFUNC


