FUNCTION FieldRuleFor_eventos_79_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_TIPO_CANCE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_CANCE,'1','2','3')) AND ( .NOT. EMPTY(TIPO_CANCE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_RES_BIOPS9
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BIOPS9,'1','2')) OR ( EMPTY(RES_BIOPS9)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_GRAD_HISTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GRAD_HISTO,'1','2','3')) OR ( EMPTY(GRAD_HISTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_BIOP_EXOCE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BIOP_EXOCE,'1','2')) OR ( EMPTY(BIOP_EXOCE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_BIOP_ENDOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BIOP_ENDOC,'1','2')) OR ( EMPTY(BIOP_ENDOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_RES_B_EXOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_B_EXOC,'1','2')) OR ( EMPTY(RES_B_EXOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_GRADO_HIST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(GRADO_HIST,'1','2','3')) OR ( EMPTY(GRADO_HIST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_RES_B_ADEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_B_ADEN,'1','2')) OR ( EMPTY(RES_B_ADEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_RES_B_HIST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_B_HIST,'1','2','3')) OR ( EMPTY(RES_B_HIST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_SEG_TRAT_I
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SEG_TRAT_I,'1','2')) AND ( .NOT. EMPTY(SEG_TRAT_I)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_RADIOTERAP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RADIOTERAP,'1','2')) OR ( EMPTY(RADIOTERAP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_QUIRURGICO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUIRURGICO,'1','2')) OR ( EMPTY(QUIRURGICO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_QUIMIOTERA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUIMIOTERA,'1','2')) OR ( EMPTY(QUIMIOTERA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_HORMONOTER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(HORMONOTER,'1','2')) OR ( EMPTY(HORMONOTER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_CUID_PALIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CUID_PALIA,'1','2')) OR ( EMPTY(CUID_PALIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_79_INMUNOTERA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INMUNOTERA,'1','2')) OR ( EMPTY(INMUNOTERA)))
	ENDIF
ENDFUNC


