FUNCTION FieldRuleFor_eventos_50_INYECTABLE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(INYECTABLE,'1','2','3')) OR ( EMPTY(INYECTABLE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_NITRAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_NITRAT,'1','2')) OR ( EMPTY(RES_NITRAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_PROPOR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_PROPOR,'1','2')) OR ( EMPTY(RES_PROPOR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_BATECM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BATECM,'1','2')) OR ( EMPTY(RES_BATECM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_PRO_AG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_PRO_AG,'1','2')) OR ( EMPTY(RES_PRO_AG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_PR_MOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_PR_MOL,'1','2')) OR ( EMPTY(RES_PR_MOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TIPO_TB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_TB,'1','2')) AND ( .NOT. EMPTY(TIPO_TB)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_LOCALIZA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(LOCALIZA,'1','2','3','4','5','7','8','9','10','11','12')) OR ( EMPTY(LOCALIZA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CLAS_ANT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_ANT,'1','2')) AND ( .NOT. EMPTY(CLAS_ANT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CLAS_MED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_MED,'1','3','4')) AND ( .NOT. EMPTY(CLAS_MED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CLAS_ING
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CLAS_ING,'10','11','12','9')) OR ( EMPTY(CLAS_ING)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_FEC_CONF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(FEC_CONF))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_BACILOSC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(BACILOSC,'1','2')) AND ( .NOT. EMPTY(BACILOSC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_BACI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_BACI,'1','2','3','4')) OR ( EMPTY(RES_BACI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CULTIVO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CULTIVO,'1','2')) AND ( .NOT. EMPTY(CULTIVO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_CULT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_CULT,'1','2','3','4','5','6','7')) OR ( EMPTY(RES_CULT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PSF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSF,'1','2')) OR ( EMPTY(PSF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RES_PSF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RES_PSF,'1','2','3','4','5')) OR ( EMPTY(RES_PSF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PSF_1_LINE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSF_1_LINE,'1','2')) OR ( EMPTY(PSF_1_LINE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_ESTREPTOMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ESTREPTOMI,'1','2','3')) OR ( EMPTY(ESTREPTOMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_ISONIAZIDA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ISONIAZIDA,'1','2','3')) OR ( EMPTY(ISONIAZIDA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_RIFAMPI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RIFAMPI,'1','2','3')) OR ( EMPTY(RIFAMPI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_ETAMBUTOL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ETAMBUTOL,'1','2','3')) OR ( EMPTY(ETAMBUTOL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PIRAZINAMI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PIRAZINAMI,'1','2','3')) OR ( EMPTY(PIRAZINAMI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PSF_2_LINE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PSF_2_LINE,'1','2')) OR ( EMPTY(PSF_2_LINE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TIPO_RESIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIPO_RESIS,'1','2','3','4','6','7','8')) AND ( .NOT. EMPTY(TIPO_RESIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_NITRATO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NITRATO,'1','2')) AND ( .NOT. EMPTY(NITRATO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PROPOR_LJ
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PROPOR_LJ,'1','2')) AND ( .NOT. EMPTY(PROPOR_LJ)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_MGIT_960
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MGIT_960,'1','2')) AND ( .NOT. EMPTY(MGIT_960)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_P_AGAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(P_AGAR,'1','2')) AND ( .NOT. EMPTY(P_AGAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_P_MOLEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(P_MOLEC,'1','2')) AND ( .NOT. EMPTY(P_MOLEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_NOM_PMOLEC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(NOM_PMOLEC,'1','2','3')) OR ( EMPTY(NOM_PMOLEC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_FACT_RIESG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FACT_RIESG,'1','2')) AND ( .NOT. EMPTY(FACT_RIESG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CONTAC_PAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONTAC_PAC,'1','2')) OR ( EMPTY(CONTAC_PAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_FARMACOD
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(FARMACOD,'1','2')) OR ( EMPTY(FARMACOD)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_OTR_INMUNO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_INMUNO,'1','2')) OR ( EMPTY(OTR_INMUNO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_VIV_TBFAR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIV_TBFAR,'1','2')) OR ( EMPTY(VIV_TBFAR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TRAT_IRRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAT_IRRE,'1','2')) OR ( EMPTY(TRAT_IRRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_MENOS3MED
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(MENOS3MED,'1','2')) OR ( EMPTY(MENOS3MED)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_OTRO_FR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTRO_FR,'1','2')) OR ( EMPTY(OTRO_FR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_COOM_CESP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COOM_CESP,'1','2')) AND ( .NOT. EMPTY(COOM_CESP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_DIABETES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIABETES,'1','2')) OR ( EMPTY(DIABETES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_SILICOSIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(SILICOSIS,'1','2')) OR ( EMPTY(SILICOSIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_E_RENAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(E_RENAL,'1','2')) OR ( EMPTY(E_RENAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_EPOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(EPOC,'1','2')) OR ( EMPTY(EPOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_E_HEPAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(E_HEPAT,'1','2')) OR ( EMPTY(E_HEPAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CANCER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CANCER,'1','2')) OR ( EMPTY(CANCER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_ARTRITIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(ARTRITIS,'1','2')) OR ( EMPTY(ARTRITIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_DESNUTR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DESNUTR,'1','2')) OR ( EMPTY(DESNUTR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(VIH,'1','2')) OR ( EMPTY(VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_OTR_COOM
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(OTR_COOM,'1','2')) OR ( EMPTY(OTR_COOM)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_CONSEJERIA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONSEJERIA,'1','2')) OR ( EMPTY(CONSEJERIA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PR_VOL_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PR_VOL_VIH,'1','2')) OR ( EMPTY(PR_VOL_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_COINF_VIH
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(COINF_VIH,'1','2','3')) OR ( EMPTY(COINF_VIH)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TRIMETRO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRIMETRO,'1','2','3')) OR ( EMPTY(TRIMETRO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TRAT_ARV
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TRAT_ARV,'1','2','3')) OR ( EMPTY(TRAT_ARV)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_PESO_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((PESO_ACT>=2  AND PESO_ACT <=250.0 AND ISNUMERIC(PESO_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_TALLA_ACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ((TALLA_ACT>=0.20  AND TALLA_ACT <=2.50 AND ISNUMERIC(TALLA_ACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_QUINOLAS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUINOLAS,'1','2','3')) OR ( EMPTY(QUINOLAS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_50_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


