FUNCTION FieldRuleFor_eventos_32_MES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MES)>=1  AND  VAL(MES) <=12 AND ISNUMERIC(MES)) AND  (.NOT. EMPTY(MES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(AÑO)>=2011 AND ISNUMERIC(AÑO)) AND  (.NOT. EMPTY(AÑO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COD_DEP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_DEP))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COD_MUN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COD_MUN))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_FEC_NOT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(FEC_NOT))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_EXI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_EXI)>= 0 AND ISNUMERIC(VAC_EXI)) AND  (.NOT. EMPTY(VAC_EXI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_REC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_REC)>= 0 AND ISNUMERIC(VAC_REC)) AND  (.NOT. EMPTY(VAC_REC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_DIS
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_DIS)>=0 AND ISNUMERIC(VAC_DIS)) AND  (.NOT. EMPTY(VAC_DIS)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_PER
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_PER)>=0 AND ISNUMERIC(VAC_PER)) AND  (.NOT. EMPTY(VAC_PER)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_SAL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_SAL)>=0 AND ISNUMERIC(VAC_SAL)) AND  (.NOT. EMPTY(VAC_SAL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_VENC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_VENC)>=0 AND ISNUMERIC(PER_VENC)) AND  (.NOT. EMPTY(PER_VENC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_EXP_CA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_EXP_CA)>=0 AND ISNUMERIC(PER_EXP_CA)) AND  (.NOT. EMPTY(PER_EXP_CA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_CONG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_CONG)>=0 AND ISNUMERIC(PER_CONG)) AND  (.NOT. EMPTY(PER_CONG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_RUPT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_RUPT)>=0 AND ISNUMERIC(PER_RUPT)) AND  (.NOT. EMPTY(PER_RUPT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_HURTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_HURTO)>=0 AND ISNUMERIC(PER_HURTO)) AND  (.NOT. EMPTY(PER_HURTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_POL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_POL)>=0 AND ISNUMERIC(PER_POL)) AND  (.NOT. EMPTY(PER_POL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_ERR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_ERR)>=0 AND ISNUMERIC(PER_ERR)) AND  (.NOT. EMPTY(PER_ERR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_REAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_REAC)>=0 AND ISNUMERIC(PER_REAC)) AND  (.NOT. EMPTY(PER_REAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_CENSO_PC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CENSO_PC)>=1 AND ISNUMERIC(CENSO_PC)) AND  (.NOT. EMPTY(CENSO_PC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PERROS_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PERROS_VAC)>=0 AND ISNUMERIC(PERROS_VAC)) AND  (.NOT. EMPTY(PERROS_VAC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VACPRIPERR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VACPRIPERR)>=0 AND ISNUMERIC(VACPRIPERR)) AND  (.NOT. EMPTY(VACPRIPERR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COBMENPERR
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(COBMENPERR)>=0 AND ISNUMERIC(COBMENPERR)) AND  (.NOT. EMPTY(COBMENPERR)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COB_ACU_VC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COB_ACU_VC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_CENSO_PF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(CENSO_PF)>=1 AND ISNUMERIC(CENSO_PF)) AND  (.NOT. EMPTY(CENSO_PF)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GATOS_VAC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(GATOS_VAC))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_VAC_PRIGAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(VAC_PRIGAT)>=0 AND ISNUMERIC(VAC_PRIGAT)) AND  (.NOT. EMPTY(VAC_PRIGAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COB_MENGAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(COB_MENGAT)>=0 AND ISNUMERIC(COB_MENGAT)) AND  (.NOT. EMPTY(COB_MENGAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_COB_ACU_VF
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(COB_ACU_VF))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PERROS_ELI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PERROS_ELI)>=0 AND ISNUMERIC(PERROS_ELI)) AND  (.NOT. EMPTY(PERROS_ELI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GATOS_ELI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GATOS_ELI)>=0 AND ISNUMERIC(GATOS_ELI)) AND  (.NOT. EMPTY(GATOS_ELI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_HEMBP_EST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(HEMBP_EST)>=0 AND ISNUMERIC(HEMBP_EST)) AND  (.NOT. EMPTY(HEMBP_EST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_MACHOP_EST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MACHOP_EST)>=0 AND ISNUMERIC(MACHOP_EST)) AND  (.NOT. EMPTY(MACHOP_EST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_HEMBG_EST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(HEMBG_EST)>=0 AND ISNUMERIC(HEMBG_EST)) AND  (.NOT. EMPTY(HEMBG_EST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_MACHOG_EST
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(MACHOG_EST)>=0 AND ISNUMERIC(MACHOG_EST)) AND  (.NOT. EMPTY(MACHOG_EST)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_OB_DOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_OB_DOC)>=0 AND ISNUMERIC(PER_OB_DOC)) AND  (.NOT. EMPTY(PER_OB_DOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_OB_CLI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_OB_CLI)>=0 AND ISNUMERIC(PER_OB_CLI)) AND  (.NOT. EMPTY(PER_OB_CLI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_OB_CEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_OB_CEN)>=0 AND ISNUMERIC(PER_OB_CEN)) AND  (.NOT. EMPTY(PER_OB_CEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_OB_DOC
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_OB_DOC)>=0 AND ISNUMERIC(GAT_OB_DOC)) AND  (.NOT. EMPTY(GAT_OB_DOC)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_OB_CLI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_OB_CLI)>=0 AND ISNUMERIC(GAT_OB_CLI)) AND  (.NOT. EMPTY(GAT_OB_CLI)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_OB_CEN
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_OB_CEN)>=0 AND ISNUMERIC(GAT_OB_CEN)) AND  (.NOT. EMPTY(GAT_OB_CEN)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_CON_RA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_CON_RA)>=0 AND ISNUMERIC(PER_CON_RA)) AND  (.NOT. EMPTY(PER_CON_RA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_SIN_RA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_SIN_RA)>=0 AND ISNUMERIC(PER_SIN_RA)) AND  (.NOT. EMPTY(PER_SIN_RA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_PER_MUERTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(PER_MUERTO)>=0 AND ISNUMERIC(PER_MUERTO)) AND  (.NOT. EMPTY(PER_MUERTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_CON_RA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_CON_RA)>=0 AND ISNUMERIC(GAT_CON_RA)) AND  (.NOT. EMPTY(GAT_CON_RA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_SIN_RA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_SIN_RA)>=0 AND ISNUMERIC(GAT_SIN_RA)) AND  (.NOT. EMPTY(GAT_SIN_RA)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_GAT_MUERTO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(GAT_MUERTO)>=0 AND ISNUMERIC(GAT_MUERTO)) AND  (.NOT. EMPTY(GAT_MUERTO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_NOM_DIL_FI
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(NOM_DIL_FI))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_FEC_DILIGE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN  (.NOT. EMPTY(FEC_DILIGE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_32_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','7','D')) OR  (EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


