FUNCTION FieldRuleFor_eventos_11_SEMANA
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(SEMANA))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_AÑO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(AÑO))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_COD_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_PRE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_COD_SUB
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_SUB))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_COD_EVE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(COD_EVE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_TIP_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIP_IDE,'RC','TI','CC','CE','PA','MS','AS','PE','CN')) AND ( .NOT. EMPTY(TIP_IDE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_NUM_IDE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN ( .NOT. EMPTY(NUM_IDE))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_CONDENDIAG
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CONDENDIAG,'1','2','3','4')) AND ( .NOT. EMPTY(CONDENDIAG)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_CON_PRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(CON_PRE,'1','2')) AND ( .NOT. EMPTY(CON_PRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_EDA_GES
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EDA_GES)>= 2  AND  VAL(EDA_GES) <= 42 AND ISNUMERIC(EDA_GES)) OR ( EMPTY(EDA_GES)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_PR_NO_TREP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PR_NO_TREP,'1','2')) AND ( .NOT. EMPTY(PR_NO_TREP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_EG_PRI_S
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EG_PRI_S)>= 2  AND  VAL(EG_PRI_S) <= 42 AND ISNUMERIC(EG_PRI_S)) OR ( EMPTY(EG_PRI_S)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_RESSERVDRL
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESSERVDRL,'3','4','5','6','7','8','9','10','11','12','13')) OR ( EMPTY(RESSERVDRL)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_PRUETREPON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PRUETREPON,'1','2')) AND ( .NOT. EMPTY(PRUETREPON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_EG_PR_TREP
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( VAL(EG_PR_TREP)>= 2  AND  VAL(EG_PR_TREP) <= 42 AND ISNUMERIC(EG_PR_TREP)) OR ( EMPTY(EG_PR_TREP)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_QUE_PR_TRE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(QUE_PR_TRE,'4','5')) OR ( EMPTY(QUE_PR_TRE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_RESULTREPO
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(RESULTREPO,'1','2')) OR ( EMPTY(RESULTREPO)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_PEN_BENZAT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(PEN_BENZAT,'0','1','2','3')) AND ( .NOT. EMPTY(PEN_BENZAT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_TTO_CON
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TTO_CON,'1','2')) AND ( .NOT. EMPTY(TTO_CON)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_AJUSTE
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(AJUSTE,'0','3','4','5','6','7','D')) OR ( EMPTY(AJUSTE)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_DIA_EMBACT
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(DIA_EMBACT,'1','2')) AND ( .NOT. EMPTY(DIA_EMBACT)))
	ENDIF
ENDFUNC


FUNCTION FieldRuleFor_eventos_11_TIEM_RESID
	IF DoNotApplyRules() THEN
		RETURN .T.
	ELSE
		RETURN (( INLIST(TIEM_RESID,'1','2')) OR ( EMPTY(TIEM_RESID)))
	ENDIF
ENDFUNC


