FUNCTION RecValidationRuleFor_eventos_43

	bIsValid=.T.
	sRuleViolated=''

	IF !DoNotApplyRules() THEN
		IF bIsValid THEN
			sRuleViolated = 'Al menos uno de los grupos de edad correspondientes a Todas las causas de Hospitalización, Todas las causas de Hosp. en UCI, Todas las causas de muerte y Total  consulta externa y urgencias, debe ser mayor que cero'
			bIsValid = HOSPITAL_1+HOSPITAL_2+HOSPITAL_3+HOSPITAL_4+HOSPITAL_5+HOSPITAL_6+HOSPITAL_7+ TOTUCI_1+TOTUCI_2+TOTUCI_3+TOTUCI_4+TOTUCI_5+TOTUCI_6+TOTUCI_7+ MTETOT_1+MTETOT_2+MTETOT_3+MTETOT_4+MTETOT_5+MTETOT_6+MTETOT_7+ TOTCEXT_1 + TOTCEXT_2  + TOTCEXT_3  +  TOTCEXT_4  + TOTCEXT_5  + TOTCEXT_6  + TOTCEXT_7 > 0
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'En todo grupo de edad los denominadores no pueden ser inferiores a los numeradores'
			bIsValid = EVENTOS_43.HOSPITAL_1 >= EVENTOS_43.GRUPOH_1 AND EVENTOS_43.HOSPITAL_2 >= EVENTOS_43.GRUPOH_2 AND EVENTOS_43.HOSPITAL_3 >= EVENTOS_43.GRUPOH_3 AND EVENTOS_43.HOSPITAL_4 >= EVENTOS_43.GRUPOH_4 AND EVENTOS_43.HOSPITAL_5 >= EVENTOS_43.GRUPOH_5 AND EVENTOS_43.HOSPITAL_6 >= EVENTOS_43.GRUPOH_6 AND EVENTOS_43.HOSPITAL_7 >= EVENTOS_43.GRUPOH_7 AND EVENTOS_43.TOTUCI_1 >= EVENTOS_43.IRAUCI_1 AND EVENTOS_43.TOTUCI_2 >= EVENTOS_43.IRAUCI_2 AND EVENTOS_43.TOTUCI_3 >= EVENTOS_43.IRAUCI_3 AND EVENTOS_43.TOTUCI_4 >= EVENTOS_43.IRAUCI_4 AND EVENTOS_43.TOTUCI_5 >= EVENTOS_43.IRAUCI_5 AND EVENTOS_43.TOTUCI_6 >= EVENTOS_43.IRAUCI_6 AND EVENTOS_43.TOTUCI_7 >= EVENTOS_43.IRAUCI_7 AND EVENTOS_43.MTETOT_1 >= EVENTOS_43.MTEIRA_1 AND EVENTOS_43.MTETOT_2 >= EVENTOS_43.MTEIRA_2 AND EVENTOS_43.MTETOT_3 >= EVENTOS_43.MTEIRA_3 AND EVENTOS_43.MTETOT_4 >= EVENTOS_43.MTEIRA_4 AND EVENTOS_43.MTETOT_5 >= EVENTOS_43.MTEIRA_5 AND EVENTOS_43.MTETOT_6 >= EVENTOS_43.MTEIRA_6 AND EVENTOS_43.MTETOT_7 >= EVENTOS_43.MTEIRA_7 AND EVENTOS_43.TOTCEXT_1 >= EVENTOS_43.IRACEXT_1 AND EVENTOS_43.TOTCEXT_2 >= EVENTOS_43.IRACEXT_2 AND EVENTOS_43.TOTCEXT_3 >= EVENTOS_43.IRACEXT_3 AND EVENTOS_43.TOTCEXT_4 >= EVENTOS_43.IRACEXT_4 AND EVENTOS_43.TOTCEXT_5 >= EVENTOS_43.IRACEXT_5 AND EVENTOS_43.TOTCEXT_6 >= EVENTOS_43.IRACEXT_6 AND EVENTOS_43.TOTCEXT_7 >= EVENTOS_43.IRACEXT_7
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'El municipio no es coherente con el código de UPGD'
			bIsValid = LEFT(EVENTOS_43.COD_PRE,2)!='11' OR LEFT(EVENTOS_43.COD_MUN,2)='11'
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'El municipio no es coherente con el código de UPGD'
			bIsValid = LEFT(EVENTOS_43.COD_PRE,2)='11' OR (LEFT(EVENTOS_43.COD_PRE,5)=EVENTOS_43.COD_MUN)
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'La semana epidemiológica NO debe ser superior a la determinada por la fecha actual de grabación'
			bIsValid = isValidEpidemiologicalWeek(EVENTOS_43.SEMANA,EVENTOS_43.AÑO)
		ENDIF


		IF VARTYPE(gsErrorMsg)='C' AND !bIsValid THEN
			gsErrorMsg = sRuleViolated
		ENDIF
	ENDIF
	RETURN bIsValid
ENDFUNC

