FUNCTION RecValidationRuleFor_eventos_58

	bIsValid=.T.
	sRuleViolated=''

	IF !DoNotApplyRules() THEN
		IF bIsValid THEN
			sRuleViolated = 'Si hay antecedentes de riesgo, alguno de ellos  debe quedar como 1=Sí'
			bIsValid = EVENTOS_58.NINGUNO!='2' OR (EVENTOS_58.HIP_CRO='1' OR EVENTOS_58.CARDIOPATÍ='1' OR EVENTOS_58.DIABETES='1' OR EVENTOS_58.MOLA_HIDA='1' OR EVENTOS_58.PRETERMINO='1' OR EVENTOS_58.BAJO_PESO='1' OR EVENTOS_58.MACROSOMIC='1' OR 	EVENTOS_58.TRANSTORNO='1' OR EVENTOS_58.OBESIDAD='1' OR EVENTOS_58.D_CRONICA='1' OR EVENTOS_58.INTER_GENE='1' OR EVENTOS_58.ITS_DIS='1' OR EVENTOS_58.VIH_SIDA='1' OR EVENTOS_58.OTRAS='1' OR EVENTOS_58.RH_NEGATIV='1' OR EVENTOS_58.TABAQUISMO='1' OR EVENTOS_58.ALCOHOLISM='1' OR EVENTOS_58.PSICOACTIV='1' OR EVENTOS_58.DEF_CONDIC='1' OR EVENTOS_58.SIFILIS='1' OR EVENTOS_58.HEPATITISB='1' OR EVENTOS_58.OTROS_FR='1' OR EVENTOS_58.GINGIVITIS='1' )
		ENDIF


		IF VARTYPE(gsErrorMsg)='C' AND !bIsValid THEN
			gsErrorMsg = sRuleViolated
		ENDIF
	ENDIF
	RETURN bIsValid
ENDFUNC

