FUNCTION RecValidationRuleFor_eventos_84

	bIsValid=.T.
	sRuleViolated=''

	IF !DoNotApplyRules() THEN
		IF bIsValid THEN
			sRuleViolated = 'Si "SEAN/SSSN" es 2=NO, debe diigenciar: Politrauma,Quemadura,Perforacion,Hemorragia,Craneo,Cara,Ojos,Nariz,Orejas,Boca_dient,Cuello,Brazo,Antebrazo,Mano,Dedos_mano,Torx_anter,Torx_post,Abdomen,Muslos,Piernas,Pies,Dedos_pies,Org_intern,Piel'
			bIsValid = EVENTOS_84.SEAN_SSSN!='2' OR (!EMPTY(EVENTOS_84.politrauma) AND !EMPTY(EVENTOS_84.QUEMADURAS) AND !EMPTY(EVENTOS_84.PERFORACIO) AND !EMPTY(EVENTOS_84.HEMORRAGIA) AND !EMPTY(EVENTOS_84.CRANEO) AND !EMPTY(EVENTOS_84.CARA) AND !EMPTY(EVENTOS_84.OJOS) AND !EMPTY(EVENTOS_84.NARIZ) AND !EMPTY(EVENTOS_84.OREJAS) AND !EMPTY(EVENTOS_84.BOCA_DIENT) AND !EMPTY(EVENTOS_84.CUELLO) AND !EMPTY(EVENTOS_84.BRAZO) AND !EMPTY(EVENTOS_84.ANTEBRAZO) AND !EMPTY(EVENTOS_84.MANO) AND !EMPTY(EVENTOS_84.DEDOS_MANO) AND !EMPTY(EVENTOS_84.TORX_ANTER) AND !EMPTY(EVENTOS_84.TORX_POST) AND !EMPTY(EVENTOS_84.ABDOMEN) AND !EMPTY(EVENTOS_84.MUSLOS) AND !EMPTY(EVENTOS_84.PIERNAS) AND !EMPTY(EVENTOS_84.PIES) AND !EMPTY(EVENTOS_84.DEDOS_PIES) AND !EMPTY(EVENTOS_84.ORG_INTERN) AND !EMPTY(EVENTOS_84.PIEL))
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'Por lo menos una variable del bloque mecanismo o agente que ocasionó la lesión debe estar marcada en la opción 1=sí'
			bIsValid = OCCURS('1', EVENTOS_84.MAQUINA + EVENTOS_84.MEDIOS_TRA + EVENTOS_84.PROD_QUIMI + EVENTOS_84.ANIMALES  + EVENTOS_84.JUGUETES + EVENTOS_84.ELECTR_ILU + EVENTOS_84.VEST_ACCES + EVENTOS_84.UTIL_ESCOL + EVENTOS_84.UTEN_COMED + EVENTOS_84.ACC_INFAN + EVENTOS_84.EQU_DEPORT + EVENTOS_84.ELECT_AUDI + EVENTOS_84.BELLEZA + EVENTOS_84.MEDICAMEN  + EVENTOS_84.APAR_ESTET + EVENTOS_84.EQU_BIOMED + EVENTOS_84.SEAN_SSSN  )  >= 1
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'Por lo menos una variable del bloque sitio anatómico debe estar marcada en la opción 1=sí'
			bIsValid = EVENTOS_84.SEAN_SSSN = '1' OR OCCURS('1',EVENTOS_84.CRANEO + EVENTOS_84.CARA + EVENTOS_84.OJOS + EVENTOS_84.NARIZ + EVENTOS_84.OREJAS + EVENTOS_84.BOCA_DIENT + EVENTOS_84.CUELLO + EVENTOS_84.BRAZO + EVENTOS_84.ANTEBRAZO + EVENTOS_84.MANO + EVENTOS_84.DEDOS_MANO + EVENTOS_84.TORX_ANTER + EVENTOS_84.TORX_POST + EVENTOS_84.MAMAS + EVENTOS_84.ABDOMEN + EVENTOS_84.PELV_PERIN + EVENTOS_84.GENITALES + EVENTOS_84.MUSLOS + EVENTOS_84.PIERNAS + EVENTOS_84.PIES + EVENTOS_84.DEDOS_PIES + EVENTOS_84.ORG_INTERN + EVENTOS_84.PIEL +  + EVENTOS_84.GLUTEOS )  >= 1
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'Por lo menos una variable del bloque lugar de ocurrencia debe estar marcada en la opción 1=sí'
			bIsValid = EVENTOS_84.SEAN_SSSN = '1' OR OCCURS('1', EVENTOS_84.HOGAR + EVENTOS_84.COLEGIO +  EVENTOS_84.CALLE + EVENTOS_84.PARQUE +   EVENTOS_84.INDUSTRIA + EVENTOS_84.ZONA_CULT + EVENTOS_84.CENTR_ESTE + EVENTOS_84.SPA + EVENTOS_84.IPS + EVENTOS_84.ESTABLECIM )  >= 1
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'Si "SEAN/SSSN" es diferente de 1, por lo menos una de las variables del bloque tipo de lesión debe estar marcada en la opción 1=sí'
			bIsValid = EVENTOS_84.SEAN_SSSN='1' OR OCCURS('1',EVENTOS_84.ASFIXIA + EVENTOS_84.ESTRANGULA + EVENTOS_84.HERIDA + EVENTOS_84.TRAUMA + EVENTOS_84.CHOQ_ELECT + EVENTOS_84.FRACTURA  + EVENTOS_84.POLITRAUMA + EVENTOS_84.AMPUTACION + EVENTOS_84.QUEMADURAS + EVENTOS_84.INTOXICAC + EVENTOS_84.INFECCION + EVENTOS_84.SEPSIS + EVENTOS_84.PERFORACIO + EVENTOS_84.HEMORRAGIA + EVENTOS_84.NECROSIS + EVENTOS_84.EMBOLIA + EVENTOS_84.DEPRE_RESP)  >= 1
		ENDIF

		IF bIsValid THEN
			sRuleViolated = 'Si "SEAN/SSSN" es 1=Sí, por lo menos una de las variables del bloque "Manifestaciones clínicas" debe estar marcada en la opción 1=sí'
			bIsValid = EVENTOS_84.SEAN_SSSN !='1' OR OCCURS('1',EVENTOS_84.TOS + EVENTOS_84.DISNEA + EVENTOS_84.DIF_RESPIR + EVENTOS_84.DOLOR_TORA + EVENTOS_84.NAUSEA + EVENTOS_84.VOMITO + EVENTOS_84.DIARREA + EVENTOS_84.DOLOR_ABDO + EVENTOS_84.OTRA_CLINI) >= 1
		ENDIF


		IF VARTYPE(gsErrorMsg)='C' AND !bIsValid THEN
			gsErrorMsg = sRuleViolated
		ENDIF
	ENDIF
	RETURN bIsValid
ENDFUNC

