#DEFINE CR_LF CHR(13) + CHR(10)
*/ Sentencia incluida en El módulo de depuración de datos básicos sivigilaDataProcessor02
*/ Sentencias incluidas en errorLog.prg

#DEFINE CrLf CHR(13) + CHR(10)

#DEFINE Cr CHR(13)

#DEFINE sTAB CHR(9)

#DEFINE YES 6

#DEFINE _NO 7

#DEFINE nMaxRowsForXLS 65000
*/ Sentencia incluida en EXPORTAR_A_XLS.PRG
*/ Sentencia incluida en SIVIGILAUTILITIES.DeleteSIVIGILAComplementaryData
*/ Sentencia incluida en SIVIGILAUTILITIES.UpdateSIVIGILAComplementaryData
*/ Sentencia incluida en SIVIGILAUTILITIES.exportDeletedRecsToXLS
